local packages = {
    "rdpopov/paq-nvim";
    "alaviss/nim.nvim";
    "rust-lang/rust.vim";
    "plasticboy/vim-markdown";
    {"nvim-treesitter/nvim-treesitter", run=function() vim.api.nvim_command("TSUpdate") end };
    "nvim-treesitter/playground";
    "danymat/neogen";
    "tpope/vim-commentary";
    "rafamadriz/friendly-snippets";
    "neovim/nvim-lspconfig";
    "ray-x/lsp_signature.nvim";
    "stevearc/aerial.nvim";
    "L3MON4D3/LuaSnip";
    "hrsh7th/nvim-cmp";
    "hrsh7th/cmp-nvim-lsp";
    "hrsh7th/cmp-buffer";
    "hrsh7th/cmp-nvim-lua";
    "hrsh7th/cmp-path";
    "f3fora/cmp-spell";
    "saadparwaiz1/cmp_luasnip";
    "nvim-telescope/telescope.nvim";
    "nvim-lua/plenary.nvim";
    "folke/todo-comments.nvim";
    {"nvim-telescope/telescope-fzf-native.nvim", run="make" };
    "nvim-telescope/telescope-symbols.nvim";
    "tpope/vim-abolish";
    "phaazon/hop.nvim";
    "mbbill/undotree";
    "antoinemadec/FixCursorHold.nvim";
    "elihunter173/dirbuf.nvim";
    "tpope/vim-fugitive";
    "TimUntersberger/neogit";
    "sindrets/diffview.nvim";
    "lewis6991/gitsigns.nvim";
    "tpope/vim-dispatch";
    "norcalli/nvim-colorizer.lua";
    "jpalardy/vim-slime";
    "dhruvasagar/vim-table-mode";
    "smithbm2316/centerpad.nvim";
    {"catppuccin/nvim", as="catppuccin"};
    "EdenEast/nightfox.nvim";
    "MunifTanjim/nui.nvim";
    "bennypowers/nvim-regexplainer";
}
require "paq_bootstrap".bootstrap(packages)
