local opts = {noremap = true, silent = true}
local keymap = vim.api.nvim_set_keymap
vim.g.mapleader = ' '
keymap('t','<Esc>', '<C-\\><C-n>',opts)
keymap('t','<C-w>', '<Esc><C-w>',opts)
keymap('n','gT', ':tabclose<CR>',opts)
keymap('n','<leader>gt', ':tabprevious<CR>',opts)
keymap('n','==', 'vi{=<Esc>',opts)
keymap('n','<Leader>=', '1z=',opts)
keymap('v','//',"y/\\V<C-R>=escape(@\",\'/\')<CR><CR>",opts)
keymap("v","<C-J>", ":m '>+1<CR>gv=gv",opts)
keymap("v","<C-K>", ":m '<-2<CR>gv=gv",opts)
keymap('n','<Leader>]', ':exec "ltag " . expand("<cword>")<CR>',opts)
keymap('n','<Leader>w', ':w<CR>',opts)
keymap('n','<Leader><leader>', ':',opts)
keymap('n','<Leader>q', ':q<cr>',opts)
keymap('n','<Leader>Q', ':qa<cr>',opts)
keymap('i','jk', '<Esc>',opts)
keymap('i','kj', '<Esc>',opts)
keymap('n','[c',':cnext<CR>',opts)
keymap('n',']c',':cprevious<CR>',opts)
keymap('n','[l',':lnext<CR>',opts)
keymap('n',']l',':lprevious<CR>',opts)
keymap('n','<C-h>','<C-w><',opts)
keymap('n','<C-l>','<C-w>>',opts)
keymap('n','<C-k>','<C-w>+',opts)
keymap('n','<C-j>','<C-w>-',opts)
