vim.api.nvim_set_hl(0,'SpellCap',{ sp = "#d09950", undercurl = true })
vim.api.nvim_set_hl(0,'SpellBad',{ sp = "#f498c0", undercurl = true })
vim.api.nvim_set_hl(0,'SpecialKey',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'QuickFixLine',{ bg = "#544a50", bold = true })
vim.api.nvim_set_hl(0,'Question',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'PreProc',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'PmenuMatchSel',{ bg = "#503240", bold = true, fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'PmenuMatch',{ bg = "#2a272c", bold = true, fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'NormalSB',{ bg = "#3b393e", fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'NormalNC',{ link = "Normal" })
vim.api.nvim_set_hl(0,'MsgArea',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'ModeMsg',{ bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'MiniTrailspace',{ bg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'MiniTestPass',{ bold = true, fg = "#51b04f" })
vim.api.nvim_set_hl(0,'MiniTestFail',{ bold = true, fg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'PmenuSel',{ bg = "#503240", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniTablineVisible',{ bg = "#232025", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniTablineTabpagesection',{ bg = "#8f8886", fg = "NONE" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedVisible',{ bg = "#4e3930", fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'LspReferenceWrite',{ bg = "#322f34" })
vim.api.nvim_set_hl(0,'LspReferenceText',{ bg = "#322f34" })
vim.api.nvim_set_hl(0,'LspReferenceRead',{ bg = "#322f34" })
vim.api.nvim_set_hl(0,'LspKindVariable',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'LspKindValue',{ fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'LspKindUnit',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindTypeParameter',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindText',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'LspKindStruct',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindString',{ fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'LspKindSnippet',{ fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'LspKindReference',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'LspKindProperty',{}) 
vim.api.nvim_set_hl(0,'LspKindPackage',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'LspKindOperator',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'LspKindObject',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'LspKindNumber',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'LspKindNull',{ fg = "#e3b0c0" })
vim.api.nvim_set_hl(0,'LspKindNamespace',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'LspKindModule',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'LspKindMethod',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'LspKindKeyword',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'LspKindKey',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'LspKindInterface',{ fg = "#e47980" })
vim.api.nvim_set_hl(0,'LspKindFunction',{ fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'LspKindFolder',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'LspKindFile',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'LspKindField',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'LspKindEvent',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'LspKindEnumMember',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindEnum',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindConstructor',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'LspKindConstant',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'LspKindColor',{ fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'LspKindClass',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'LspKindBoolean',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'LspKindArray',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'LspInlayHint',{ bg = "#2a272c", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'LspInfoBorder',{ bg = "#322f34", fg = "#635850" })
vim.api.nvim_set_hl(0,'LspCodeLens',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'LineNrBelow',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'LineNrAbove',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'Italic',{ fg = "#efd5c5", italic = true })
vim.api.nvim_set_hl(0,'Folded',{ bg = "#3b393e", fg = "#635850" })
vim.api.nvim_set_hl(0,'FoldColumn',{ bg = "#232025", fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'EndOfBuffer',{ fg = "#232025" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextWarn',{ bg = "#4e3930", fg = "#d09950" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextInfo',{ bg = "#0f3f4f", fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextHint',{ bg = "#0f3f4f", fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'Whitespace',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineWarn',{ sp = "#d09950", undercurl = true })
vim.api.nvim_set_hl(0,'@markup.math',{ link = "Special" })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineHint',{ sp = "#6fb3c0", undercurl = true })
vim.api.nvim_set_hl(0,'SignColumn',{ bg = "#232025", fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'Debug',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'CursorLineNr',{ bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'CursorIM',{ link = "Cursor" })
vim.api.nvim_set_hl(0,'CurSearch',{ bg = "#8f665f" })
vim.api.nvim_set_hl(0,'Conceal',{ fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'Character',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'BlinkCmpSignatureHelpBorder',{ bg = "#322f34", fg = "#635850" })
vim.api.nvim_set_hl(0,'BlinkCmpSignatureHelp',{ bg = "#322f34", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'BlinkCmpMenuBorder',{ bg = "#322f34", fg = "#635850" })
vim.api.nvim_set_hl(0,'BlinkCmpMenu',{ bg = "#2a272c", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'BlinkCmpLabelMatch',{ bg = "NONE", bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'BlinkCmpLabelDeprecated',{ bg = "NONE", fg = "#8f8886", strikethrough = true })
vim.api.nvim_set_hl(0,'BlinkCmpLabel',{ bg = "NONE", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'@label',{ fg = "#57b0ff" })
vim.api.nvim_set_hl(0,'BlinkCmpKindValue',{ link = "LspKindValue" })
vim.api.nvim_set_hl(0,'ColorColumn',{ bg = "#3b393e" })
vim.api.nvim_set_hl(0,'BlinkCmpKindTypeParameter',{ link = "LspKindTypeParameter" })
vim.api.nvim_set_hl(0,'CursorColumn',{ bg = "#3b393e" })
vim.api.nvim_set_hl(0,'BlinkCmpKindTabNine',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'Visual',{ bg = "#544a50", fg = "NONE" })
vim.api.nvim_set_hl(0,'BlinkCmpKindStruct',{ link = "LspKindStruct" })
vim.api.nvim_set_hl(0,'BlinkCmpKindString',{ link = "LspKindString" })
vim.api.nvim_set_hl(0,'BlinkCmpKindSnippet',{ link = "LspKindSnippet" })
vim.api.nvim_set_hl(0,'BlinkCmpKindReference',{ link = "LspKindReference" })
vim.api.nvim_set_hl(0,'DiffText',{ bg = "#2f6767" })
vim.api.nvim_set_hl(0,'BlinkCmpKindPackage',{ link = "LspKindPackage" })
vim.api.nvim_set_hl(0,'BlinkCmpKindOperator',{ link = "LspKindOperator" })
vim.api.nvim_set_hl(0,'BlinkCmpKindObject',{ link = "LspKindObject" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNumber',{ link = "LspKindNumber" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNull',{ link = "LspKindNull" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNamespace',{ link = "LspKindNamespace" })
vim.api.nvim_set_hl(0,'BlinkCmpKindModule',{ link = "LspKindModule" })
vim.api.nvim_set_hl(0,'BlinkCmpKindMethod',{ link = "LspKindMethod" })
vim.api.nvim_set_hl(0,'BlinkCmpKindKeyword',{ link = "LspKindKeyword" })
vim.api.nvim_set_hl(0,'BlinkCmpKindKey',{ link = "LspKindKey" })
vim.api.nvim_set_hl(0,'BlinkCmpKindInterface',{ link = "LspKindInterface" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFunction',{ link = "LspKindFunction" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFolder',{ link = "LspKindFolder" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFile',{ link = "LspKindFile" })
vim.api.nvim_set_hl(0,'BlinkCmpKindField',{ link = "LspKindField" })
vim.api.nvim_set_hl(0,'BlinkCmpKindEvent',{ link = "LspKindEvent" })
vim.api.nvim_set_hl(0,'BlinkCmpKindEnumMember',{ link = "LspKindEnumMember" })
vim.api.nvim_set_hl(0,'BlinkCmpKindEnum',{ link = "LspKindEnum" })
vim.api.nvim_set_hl(0,'BlinkCmpKindDefault',{ bg = "NONE", fg = "#8f8886" })
vim.api.nvim_set_hl(0,'BlinkCmpKindCopilot',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindConstructor',{ link = "LspKindConstructor" })
vim.api.nvim_set_hl(0,'BlinkCmpKindConstant',{ link = "LspKindConstant" })
vim.api.nvim_set_hl(0,'BlinkCmpKindColor',{ link = "LspKindColor" })
vim.api.nvim_set_hl(0,'BlinkCmpKindCodeium',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindClass',{ link = "LspKindClass" })
vim.api.nvim_set_hl(0,'BlinkCmpKindBoolean',{ link = "LspKindBoolean" })
vim.api.nvim_set_hl(0,'BlinkCmpKindArray',{ link = "LspKindArray" })
vim.api.nvim_set_hl(0,'BlinkCmpGhostText',{ fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'BlinkCmpDocBorder',{ bg = "#322f34", fg = "#635850" })
vim.api.nvim_set_hl(0,'BlinkCmpDoc',{ bg = "#322f34", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'@variable.parameter',{ fg = "#c0b24f" })
vim.api.nvim_set_hl(0,'@variable.member',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'@variable.builtin',{ bold = true, fg = "#e3b0c0" })
vim.api.nvim_set_hl(0,'@variable',{ link = "Variable" })
vim.api.nvim_set_hl(0,'@type.qualifier',{ link = "@keyword" })
vim.api.nvim_set_hl(0,'@keyword',{ bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'@type.definition',{ link = "Typedef" })
vim.api.nvim_set_hl(0,'@type.builtin',{ bold = true, fg = "#e3b0c0" })
vim.api.nvim_set_hl(0,'@tag.tsx',{ fg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'@tag.javascript',{ fg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'@tag.delimiter',{ link = "Delimiter" })
vim.api.nvim_set_hl(0,'@tag.attribute',{ link = "@property" })
vim.api.nvim_set_hl(0,'@tag',{ link = "Label" })
vim.api.nvim_set_hl(0,'@string.regexp',{ fg = "#12b4ff" })
vim.api.nvim_set_hl(0,'@string.escape',{ fg = "#65c5a8" })
vim.api.nvim_set_hl(0,'@string.documentation',{ fg = "#caa89f" })
vim.api.nvim_set_hl(0,'@string',{ link = "String" })
vim.api.nvim_set_hl(0,'@punctuation.special.markdown',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'@punctuation.special',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'@punctuation.bracket',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'@operator',{ bold = true, fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'@number.float',{ link = "Float" })
vim.api.nvim_set_hl(0,'@number',{ link = "Number" })
vim.api.nvim_set_hl(0,'@none',{}) vim.api.nvim_set_hl(0,'@namespace.builtin',{ link = "@variable.builtin" })
vim.api.nvim_set_hl(0,'@module.builtin',{ fg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'@module',{ link = "Include" })
vim.api.nvim_set_hl(0,'@markup.underline',{ underline = true })
vim.api.nvim_set_hl(0,'@markup.strong',{ bold = true })
vim.api.nvim_set_hl(0,'@markup.strikethrough',{ strikethrough = true })
vim.api.nvim_set_hl(0,'@markup.raw.markdown_inline',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'@markup.list.markdown',{ bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'@markup.list',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'@markup.link.url',{ fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'@markup.link.label.symbol',{ link = "Identifier" })
vim.api.nvim_set_hl(0,'@markup.link.label',{ fg = "#deb07a", underline = true })
vim.api.nvim_set_hl(0,'@markup.link',{ fg = "#deb07a", underline = true })
vim.api.nvim_set_hl(0,'@markup.italic',{ italic = true })
vim.api.nvim_set_hl(0,'@markup.environment.name',{ link = "Type" })
vim.api.nvim_set_hl(0,'@markup.environment',{ link = "Macro" })
vim.api.nvim_set_hl(0,'@markup.emphasis',{ italic = true })
vim.api.nvim_set_hl(0,'@markup',{ link = "@none" })
vim.api.nvim_set_hl(0,'@keyword.storage',{ link = "StorageClass" })
vim.api.nvim_set_hl(0,'@function.method.call',{ link = "@function.method" })
vim.api.nvim_set_hl(0,'@function.method',{ link = "Function" })
vim.api.nvim_set_hl(0,'@function.macro',{ link = "Macro" })
vim.api.nvim_set_hl(0,'@function.call',{ link = "@function" })
vim.api.nvim_set_hl(0,'@function',{ link = "Function" })
vim.api.nvim_set_hl(0,'@function.builtin',{ link = "Special" })
vim.api.nvim_set_hl(0,'@diff.plus',{ link = "DiffAdd" })
vim.api.nvim_set_hl(0,'@diff.minus',{ link = "DiffDelete" })
vim.api.nvim_set_hl(0,'@diff.delta',{ link = "DiffChange" })
vim.api.nvim_set_hl(0,'@constructor.tsx',{ fg = "#12b4ff" })
vim.api.nvim_set_hl(0,'@constructor',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'@constant.macro',{ link = "Define" })
vim.api.nvim_set_hl(0,'@constant.builtin',{ link = "Special" })
vim.api.nvim_set_hl(0,'@constant',{ link = "Constant" })
vim.api.nvim_set_hl(0,'@comment.warning',{ fg = "#d09950" })
vim.api.nvim_set_hl(0,'@comment.todo',{ fg = "#d09950" })
vim.api.nvim_set_hl(0,'@comment.note',{ fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'@comment.info',{ fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'@comment.hint',{ fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'@comment.error',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'@character.special',{ link = "SpecialChar" })
vim.api.nvim_set_hl(0,'@character.printf',{ link = "SpecialChar" })
vim.api.nvim_set_hl(0,'@character',{ link = "Character" })
vim.api.nvim_set_hl(0,'@boolean',{ link = "Boolean" })
vim.api.nvim_set_hl(0,'@attribute.diff',{ bg = "#3b393e", bold = true, fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'@attribute',{ link = "PreProc" })
vim.api.nvim_set_hl(0,'@annotation',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingOk',{ bg = "#322f34", fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingHint',{ bg = "#322f34", fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingInfo',{ bg = "#322f34", fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingError',{ bg = "#322f34", fg = "#f498c0" })
vim.api.nvim_set_hl(0,'Bold',{ bold = true, fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'PmenuSbar',{ bg = "#2a272c" })
vim.api.nvim_set_hl(0,'PmenuExtraSel',{ link = "PmenuSel" })
vim.api.nvim_set_hl(0,'PmenuExtra',{ link = "Pmenu" })
vim.api.nvim_set_hl(0,'Title',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'PmenuKind',{ link = "Pmenu" })
vim.api.nvim_set_hl(0,'FloatFooter',{ bg = "#322f34", fg = "#827973" })
vim.api.nvim_set_hl(0,'Special',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'Pmenu',{ bg = "#2a272c", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'markdownH6',{ bold = true, fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'PmenuThumb',{ bg = "#827973" })
vim.api.nvim_set_hl(0,'PmenuKindSel',{ link = "PmenuSel" })
vim.api.nvim_set_hl(0,'@comment',{ link = "Comment" })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineInfo',{ sp = "#6fb3c0", undercurl = true })
vim.api.nvim_set_hl(0,'MatchParen',{ bg = "#885566", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniTablineCurrent',{ bg = "#232025", fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'MiniTestEmphasis',{ bold = true })
vim.api.nvim_set_hl(0,'MiniAnimateNormalFloat',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextError',{ bg = "#501a2d", fg = "#f498c0" })
vim.api.nvim_set_hl(0,'Substitute',{ bg = "#a02f50", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'TabLine',{ bg = "#3b393e", fg = "#8f8886" })
vim.api.nvim_set_hl(0,'NormalFloat',{ bg = "#322f34", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniClueNextKeyWithPostkeys',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'LineNr',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'BlinkCmpKindVariable',{ link = "LspKindVariable" })
vim.api.nvim_set_hl(0,'MiniCompletionActiveParameter',{ underline = true })
vim.api.nvim_set_hl(0,'BlinkCmpKindUnit',{ link = "LspKindUnit" })
vim.api.nvim_set_hl(0,'FloatBorder',{ bg = "#322f34", fg = "#827973" })
vim.api.nvim_set_hl(0,'Underlined',{ underline = true })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineError',{ sp = "#f498c0", undercurl = true })
vim.api.nvim_set_hl(0,'VertSplit',{ fg = "#635850" })
vim.api.nvim_set_hl(0,'VisualNOS',{ bg = "#544a50" })
vim.api.nvim_set_hl(0,'BlinkCmpKindText',{ link = "LspKindText" })
vim.api.nvim_set_hl(0,'WildMenu',{ bg = "#544a50" })
vim.api.nvim_set_hl(0,'StatusLine',{ bg = "#675072", fg = "#fedeff" })
vim.api.nvim_set_hl(0,'BlinkCmpKindSupermaven',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'StatusLineNC',{ bg = "#3b393e", fg = "#8f8886" })
vim.api.nvim_set_hl(0,'MiniDepsTitleSame',{ link = "Comment" })
vim.api.nvim_set_hl(0,'BlinkCmpKindProperty',{ link = "LspKindProperty" })
vim.api.nvim_set_hl(0,'WinSeparator',{ bg = "#232025", fg = "#827973" })
vim.api.nvim_set_hl(0,'@markup.heading.6.markdown',{ link = "markdownH6" })
vim.api.nvim_set_hl(0,'MiniJump2dSpotUnique',{ bg = "#6f202a", bold = true, fg = "#f3a0a0", sp = "#ff6f6f", undercurl = true })
vim.api.nvim_set_hl(0,'DiagnosticHint',{ fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'MiniDiffOverChange',{ link = "DiffText" })
vim.api.nvim_set_hl(0,'@markup.heading.5.markdown',{ link = "markdownH5" })
vim.api.nvim_set_hl(0,'MiniFilesFile',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'DiagnosticWarn',{ fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniDiffOverDelete',{ link = "DiffDelete" })
vim.api.nvim_set_hl(0,'@markup.heading.4.markdown',{ link = "markdownH4" })
vim.api.nvim_set_hl(0,'Error',{ bold = true, fg = "#f498c0" })
vim.api.nvim_set_hl(0,'DiagnosticError',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedHidden',{ bg = "#675072", fg = "#501a2d" })
vim.api.nvim_set_hl(0,'@markup.heading.3.markdown',{ link = "markdownH3" })
vim.api.nvim_set_hl(0,'diffFile',{ fg = "#57b0ff" })
vim.api.nvim_set_hl(0,'@markup.heading.2.markdown',{ link = "markdownH2" })
vim.api.nvim_set_hl(0,'diffIndexLine',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'@markup.heading.1.markdown',{ link = "markdownH1" })
vim.api.nvim_set_hl(0,'diffLine',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'DiagnosticInfo',{ fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'Search',{ bg = "#4f509f", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'diffNewFile',{ fg = "#caa89f" })
vim.api.nvim_set_hl(0,'diffOldFile',{ fg = "#c0b24f" })
vim.api.nvim_set_hl(0,'Comment',{ fg = "#a0a0cf", italic = true })
vim.api.nvim_set_hl(0,'@markup.heading',{ link = "Title" })
vim.api.nvim_set_hl(0,'Todo',{ bg = "#d09950", fg = "#d09950" })
vim.api.nvim_set_hl(0,'@markup.raw',{ link = "String" })
vim.api.nvim_set_hl(0,'MiniFilesTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'@markup.list.checked',{ fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'Operator',{ link = "Bold" })
vim.api.nvim_set_hl(0,'@markup.list.unchecked',{ fg = "#57b0ff" })
vim.api.nvim_set_hl(0,'CursorLine',{ bg = "#412f4f" })
vim.api.nvim_set_hl(0,'healthError',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'MiniHipatternsTodo',{ bg = "#0f3f4f", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'Identifier',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'healthSuccess',{ fg = "#51b04f" })
vim.api.nvim_set_hl(0,'Keyword',{ bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'healthWarning',{ fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniPickMatchCurrent',{ bg = "#503240" })
vim.api.nvim_set_hl(0,'helpExample',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'htmlH1',{ link = "markdownH1" })
vim.api.nvim_set_hl(0,'NonText',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'qfLineNr',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'htmlH4',{ link = "markdownH4" })
vim.api.nvim_set_hl(0,'Variable',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'htmlH5',{ link = "markdownH5" })
vim.api.nvim_set_hl(0,'htmlH6',{ link = "markdownH6" })
vim.api.nvim_set_hl(0,'Function',{ fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'Cursor',{ bg = "#f3c09a", fg = "#232025" })
vim.api.nvim_set_hl(0,'Directory',{ fg = "#deb07a" })
vim.api.nvim_set_hl(0,'lCursor',{ link = "Cursor" })
vim.api.nvim_set_hl(0,'markdownH1',{ bold = true, fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'markdownH2',{ bold = true, fg = "#80aadf" })
vim.api.nvim_set_hl(0,'String',{ fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'MiniIconsGreen',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedCurrent',{ bg = "#4e3930", fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniTablineHidden',{ bg = "#322f34", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniTablineFill',{ bg = "#3b393e" })
vim.api.nvim_set_hl(0,'Statement',{ fg = "#d0b0ff" })
vim.api.nvim_set_hl(0,'MiniSurround',{ bg = "#deb07a", fg = "black" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeVisual',{ bg = "#d09950", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeReplace',{ bg = "#f498c0", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeOther',{ bg = "#a9c99f", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeNormal',{ bg = "#deb07a", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeInsert',{ bg = "#57b0ff", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'markdownH3',{ bold = true, fg = "#e47980" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeCommand',{ bg = "#d09950", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineInactive',{ link = "StatusLineNC" })
vim.api.nvim_set_hl(0,'MiniStatuslineFilename',{ bg = "#322f34", fg = "#fedeff" })
vim.api.nvim_set_hl(0,'MiniStatuslineFileinfo',{ bg = "#675072", fg = "#fedeff" })
vim.api.nvim_set_hl(0,'MiniStatuslineDevinfo',{ bg = "#675072", fg = "#fedeff" })
vim.api.nvim_set_hl(0,'MiniStarterSection',{ bold = true, fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniStarterQuery',{ fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'MiniStarterItemPrefix',{ fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniStarterItemBullet',{ fg = "#635850" })
vim.api.nvim_set_hl(0,'MiniStarterItem',{ bg = "#232025", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniStarterInactive',{ fg = "#a0a0cf", italic = true })
vim.api.nvim_set_hl(0,'MiniStarterHeader',{ fg = "#57b0ff" })
vim.api.nvim_set_hl(0,'MiniStarterFooter',{ fg = "#c0b24f", italic = true })
vim.api.nvim_set_hl(0,'MiniStarterCurrent',{ nocombine = true })
vim.api.nvim_set_hl(0,'markdownH4',{ bold = true, fg = "#d0b0ff" })
vim.api.nvim_set_hl(0,'MiniPickPrompt',{ bg = "#322f34", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniPickPreviewRegion',{ link = "IncSearch" })
vim.api.nvim_set_hl(0,'IncSearch',{ bg = "#8f665f", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniPickPreviewLine',{ link = "CursorLine" })
vim.api.nvim_set_hl(0,'Type',{ bold = true, fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'MiniPickNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniPickMatchRanges',{ bold = true, fg = "#deb07a" })
vim.api.nvim_set_hl(0,'MiniPickMatchMarked',{ bg = "#0f3f4f", bold = true })
vim.api.nvim_set_hl(0,'markdownH5',{ bold = true, fg = "#3fc489" })
vim.api.nvim_set_hl(0,'ErrorMsg',{ fg = "#f498c0" })
vim.api.nvim_set_hl(0,'MoreMsg',{ fg = "#57b0ff" })
vim.api.nvim_set_hl(0,'MiniPickIconDirectory',{ link = "Directory" })
vim.api.nvim_set_hl(0,'MiniPickHeader',{ bold = true, fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'MiniPickBorderText',{ bg = "#322f34", bold = true, fg = "#ffaacf" })
vim.api.nvim_set_hl(0,'MiniPickBorderBusy',{ link = "DiagnosticFloatingWarn" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingWarn',{ bg = "#322f34", fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniPickBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniOperatorsExchangeFrom',{ link = "IncSearch" })
vim.api.nvim_set_hl(0,'MiniNotifyTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'FloatTitle',{ bg = "#322f34", bold = true, fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'MiniNotifyNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniNotifyBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniMapSymbolView',{ link = "Delimiter" })
vim.api.nvim_set_hl(0,'Delimiter',{ link = "Comment" })
vim.api.nvim_set_hl(0,'MiniMapSymbolLine',{ link = "Title" })
vim.api.nvim_set_hl(0,'MiniMapSymbolCount',{ link = "Special" })
vim.api.nvim_set_hl(0,'MiniMapNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'DiffDelete',{ bg = "#5a3142", fg = "#f0bfcf" })
vim.api.nvim_set_hl(0,'MiniPickIconFile',{ link = "MiniPickNormal" })
vim.api.nvim_set_hl(0,'MiniJump2dSpotAhead',{ fg = "#e47980", nocombine = true })
vim.api.nvim_set_hl(0,'MiniJump2dSpot',{ bold = true, fg = "#deb07a", nocombine = true, underline = true })
vim.api.nvim_set_hl(0,'MiniJump2dDim',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'MiniJump',{ bg = "#66345a", sp = "#f498c0", undercurl = true })
vim.api.nvim_set_hl(0,'qfFileName',{ fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'MiniIndentscopeSymbol',{ fg = "#80aadf", nocombine = true })
vim.api.nvim_set_hl(0,'MiniIndentscopePrefix',{ nocombine = true })
vim.api.nvim_set_hl(0,'MiniIconsYellow',{ fg = "#caa89f" })
vim.api.nvim_set_hl(0,'MiniIconsRed',{ fg = "#ff6f6f" })
vim.api.nvim_set_hl(0,'MiniIconsPurple',{ fg = "#d0b0ff" })
vim.api.nvim_set_hl(0,'MiniIconsOrange',{ fg = "#f3a0a0" })
vim.api.nvim_set_hl(0,'MiniIconsGrey',{ fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'htmlH3',{ link = "markdownH3" })
vim.api.nvim_set_hl(0,'htmlH2',{ link = "markdownH2" })
vim.api.nvim_set_hl(0,'MiniIconsCyan',{ fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'MiniIconsBlue',{ fg = "#a0a0cf" })
vim.api.nvim_set_hl(0,'MiniIconsAzure',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'Constant',{ fg = "#80aadf" })
vim.api.nvim_set_hl(0,'MiniHipatternsNote',{ bg = "#4f509f", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniHipatternsHack',{ bg = "#4e3930", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniHipatternsFixme',{ bg = "#501a2d", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniFilesTitleFocused',{ bg = "#322f34", bold = true, fg = "#8fcfd0" })
vim.api.nvim_set_hl(0,'diffRemoved',{ fg = "#f0bfcf" })
vim.api.nvim_set_hl(0,'MiniFilesNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'DiffAdd',{ bg = "#304a4f", fg = "#a0d0f0" })
vim.api.nvim_set_hl(0,'MiniFilesDirectory',{ link = "Directory" })
vim.api.nvim_set_hl(0,'MiniFilesCursorLine',{ link = "CursorLine" })
vim.api.nvim_set_hl(0,'MiniFilesBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniDiffSignDelete',{ fg = "#f0bfcf" })
vim.api.nvim_set_hl(0,'MiniDiffSignChange',{ fg = "#dada90" })
vim.api.nvim_set_hl(0,'MiniDiffSignAdd',{ fg = "#a0d0f0" })
vim.api.nvim_set_hl(0,'diffChanged',{ fg = "#dada90" })
vim.api.nvim_set_hl(0,'MiniDiffOverContext',{ link = "DiffChange" })
vim.api.nvim_set_hl(0,'diffAdded',{ fg = "#a0d0f0" })
vim.api.nvim_set_hl(0,'MiniDiffOverAdd',{ link = "DiffAdd" })
vim.api.nvim_set_hl(0,'MiniDepsTitleUpdate',{ bg = "#62432a", fg = "#c0b24f" })
vim.api.nvim_set_hl(0,'DiffChange',{ bg = "#51512f", fg = "#dada90" })
vim.api.nvim_set_hl(0,'WinBarNC',{ link = "StatusLineNC" })
vim.api.nvim_set_hl(0,'MiniDepsTitleError',{ bg = "#5a3142", fg = "#f498c0" })
vim.api.nvim_set_hl(0,'WinBar',{ link = "StatusLine" })
vim.api.nvim_set_hl(0,'MiniDepsTitle',{ link = "Title" })
vim.api.nvim_set_hl(0,'MiniDepsPlaceholder',{ link = "Comment" })
vim.api.nvim_set_hl(0,'MiniDepsMsgBreaking',{ link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0,'MiniDepsInfo',{ link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0,'MiniDepsHint',{ link = "DiagnosticHint" })
vim.api.nvim_set_hl(0,'MiniDepsChangeRemoved',{ link = "diffRemoved" })
vim.api.nvim_set_hl(0,'MiniDepsChangeAdded',{ link = "diffAdded" })
vim.api.nvim_set_hl(0,'MiniCursorwordCurrent',{ underline = true })
vim.api.nvim_set_hl(0,'MiniCursorword',{ underline = true })
vim.api.nvim_set_hl(0,'TabLineSel',{ bg = "#232025", fg = "#b0a0cf" })
vim.api.nvim_set_hl(0,'MiniClueTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'MiniClueSeparator',{ fg = "#8f8886" })
vim.api.nvim_set_hl(0,'TabLineFill',{ bg = "#232025" })
vim.api.nvim_set_hl(0,'MiniClueNextKey',{ bold = true, fg = "#6fb3c0" })
vim.api.nvim_set_hl(0,'MiniClueDescSingle',{ fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'MiniClueDescGroup',{ bg = "#322f34", fg = "#deb07a" })
vim.api.nvim_set_hl(0,'MiniClueBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'WarningMsg',{ bold = true, fg = "#d09950" })
vim.api.nvim_set_hl(0,'MiniAnimateCursor',{ nocombine = true, reverse = true })
vim.api.nvim_set_hl(0,'Normal',{ bg = "#232025", fg = "#efd5c5" })
vim.api.nvim_set_hl(0,'LspSignatureActiveParameter',{ bg = "#957856", bold = true })
vim.api.nvim_set_hl(0,'SpellRare',{ sp = "#d09950", undercurl = true })
vim.api.nvim_set_hl(0,'SpellLocal',{ sp = "#d09950", undercurl = true })
