vim.api.nvim_set_hl(0,'helpExample',{ fg = "#cac89f" })
vim.api.nvim_set_hl(0,'healthWarning',{ fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'PmenuSel',{ bg = "#37493f", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'healthError',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'diffRemoved',{ fg = "#ffbfbf" })
vim.api.nvim_set_hl(0,'diffOldFile',{ fg = "#cac85f" })
vim.api.nvim_set_hl(0,'diffNewFile',{ fg = "#cac89f" })
vim.api.nvim_set_hl(0,'diffLine',{ fg = "#cac89f" })
vim.api.nvim_set_hl(0,'diffIndexLine',{ fg = "#f59acf" })
vim.api.nvim_set_hl(0,'diffFile',{ fg = "#57aff6" })
vim.api.nvim_set_hl(0,'diffChanged',{ fg = "#dada90" })
vim.api.nvim_set_hl(0,'diffAdded',{ fg = "#a0e0a0" })
vim.api.nvim_set_hl(0,'WinSeparator',{ bg = "#222524", fg = "#7d7f82" })
vim.api.nvim_set_hl(0,'WinBarNC',{ link = "StatusLineNC" })
vim.api.nvim_set_hl(0,'StatusLineNC',{ bg = "#3e4140", fg = "#969faf" })
vim.api.nvim_set_hl(0,'WinBar',{ link = "StatusLine" })
vim.api.nvim_set_hl(0,'StatusLine',{ bg = "#35605d", fg = "#ecf0ff" })
vim.api.nvim_set_hl(0,'WildMenu',{ bg = "#543040" })
vim.api.nvim_set_hl(0,'VisualNOS',{ bg = "#543040" })
vim.api.nvim_set_hl(0,'VertSplit',{ fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'Underlined',{ underline = true })
vim.api.nvim_set_hl(0,'TabLineSel',{ bg = "#222524", fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'TabLineFill',{ bg = "#222524" })
vim.api.nvim_set_hl(0,'TabLine',{ bg = "#3e4140", fg = "#969faf" })
vim.api.nvim_set_hl(0,'Substitute',{ bg = "#bd1f30", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'SpellRare',{ sp = "#e0b02f", undercurl = true })
vim.api.nvim_set_hl(0,'SpellLocal',{ sp = "#e0b02f", undercurl = true })
vim.api.nvim_set_hl(0,'SpellCap',{ sp = "#e0b02f", undercurl = true })
vim.api.nvim_set_hl(0,'SpellBad',{ sp = "#ff7a5f", undercurl = true })
vim.api.nvim_set_hl(0,'SpecialKey',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'QuickFixLine',{ bg = "#543040", bold = true })
vim.api.nvim_set_hl(0,'Question',{ fg = "#78afff" })
vim.api.nvim_set_hl(0,'PreProc',{ fg = "#fa90ea" })
vim.api.nvim_set_hl(0,'PmenuMatchSel',{ bg = "#37493f", bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'PmenuMatch',{ bg = "#2b2e2d", bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'NormalSB',{ bg = "#3e4140", fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'NormalNC',{ link = "Normal" })
vim.api.nvim_set_hl(0,'MsgArea',{ fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'ModeMsg',{ bold = true, fg = "#50cf89" })
vim.api.nvim_set_hl(0,'MiniTrailspace',{ bg = "#ff656a" })
vim.api.nvim_set_hl(0,'MiniTestPass',{ bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'MiniTestFail',{ bold = true, fg = "#ff656a" })
vim.api.nvim_set_hl(0,'MiniTestEmphasis',{ bold = true })
vim.api.nvim_set_hl(0,'MiniTablineVisible',{ bg = "#222524", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniTablineTabpagesection',{ bg = "#969faf", fg = "NONE" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedVisible',{ bg = "#424223", fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'@character',{ link = "Character" })
vim.api.nvim_set_hl(0,'@boolean',{ link = "Boolean" })
vim.api.nvim_set_hl(0,'@attribute.diff',{ bg = "#3e4140", bold = true, fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'@attribute',{ link = "PreProc" })
vim.api.nvim_set_hl(0,'@annotation',{ fg = "#f59acf" })
vim.api.nvim_set_hl(0,'MiniTablineCurrent',{ bg = "#222524", fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'MiniSurround',{ bg = "#cfb27f", fg = "black" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeVisual',{ bg = "#e0b02f", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeReplace',{ bg = "#ff7a5f", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeOther',{ bg = "#6fcfd2", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeNormal',{ bg = "#50cf89", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeInsert',{ bg = "#57aff6", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineModeCommand',{ bg = "#e0b02f", bold = true, fg = "#000000" })
vim.api.nvim_set_hl(0,'MiniStatuslineInactive',{ link = "StatusLineNC" })
vim.api.nvim_set_hl(0,'MiniStatuslineFilename',{ bg = "#303332", fg = "#ecf0ff" })
vim.api.nvim_set_hl(0,'MiniStatuslineFileinfo',{ bg = "#35605d", fg = "#ecf0ff" })
vim.api.nvim_set_hl(0,'MiniStatuslineDevinfo',{ bg = "#35605d", fg = "#ecf0ff" })
vim.api.nvim_set_hl(0,'MiniStarterSection',{ bold = true, fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniStarterQuery',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'MiniStarterItemPrefix',{ fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'MiniStarterItemBullet',{ fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'MiniStarterItem',{ bg = "#222524", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniStarterInactive',{ fg = "#cac89f", italic = true })
vim.api.nvim_set_hl(0,'MiniStarterHeader',{ fg = "#57aff6" })
vim.api.nvim_set_hl(0,'MiniStarterFooter',{ fg = "#cac85f", italic = true })
vim.api.nvim_set_hl(0,'MiniStarterCurrent',{ nocombine = true })
vim.api.nvim_set_hl(0,'PmenuThumb',{ bg = "#7d7f82" })
vim.api.nvim_set_hl(0,'MiniPickPrompt',{ bg = "#303332", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniPickPreviewRegion',{ link = "IncSearch" })
vim.api.nvim_set_hl(0,'IncSearch',{ bg = "#847020", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniPickPreviewLine',{ link = "CursorLine" })
vim.api.nvim_set_hl(0,'CursorLine',{ bg = "#2f413f" })
vim.api.nvim_set_hl(0,'MiniPickNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniPickMatchRanges',{ bold = true, fg = "#50cf89" })
vim.api.nvim_set_hl(0,'MiniPickMatchMarked',{ bg = "#104420", bold = true })
vim.api.nvim_set_hl(0,'DiagnosticHint',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'MiniPickMatchCurrent',{ bg = "#37493f" })
vim.api.nvim_set_hl(0,'MiniPickIconFile',{ link = "MiniPickNormal" })
vim.api.nvim_set_hl(0,'MiniPickIconDirectory',{ link = "Directory" })
vim.api.nvim_set_hl(0,'MiniPickHeader',{ bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'MiniPickBorderText',{ bg = "#303332", bold = true, fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'MiniPickBorderBusy',{ link = "DiagnosticFloatingWarn" })
vim.api.nvim_set_hl(0,'Error',{ bold = true, fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'MiniPickBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniOperatorsExchangeFrom',{ link = "IncSearch" })
vim.api.nvim_set_hl(0,'MiniNotifyTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'FloatTitle',{ bg = "#303332", bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'MiniNotifyNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniNotifyBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniMapSymbolView',{ link = "Delimiter" })
vim.api.nvim_set_hl(0,'Delimiter',{ link = "Comment" })
vim.api.nvim_set_hl(0,'MiniMapSymbolLine',{ link = "Title" })
vim.api.nvim_set_hl(0,'MiniMapSymbolCount',{ link = "Special" })
vim.api.nvim_set_hl(0,'MiniMapNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniJump2dSpotUnique',{ bg = "#6c2a2a", bold = true, fg = "#eba8a8", sp = "#ff656a", undercurl = true })
vim.api.nvim_set_hl(0,'MiniJump2dSpotAhead',{ fg = "#f59acf", nocombine = true })
vim.api.nvim_set_hl(0,'MiniJump2dSpot',{ bold = true, fg = "#50cf89", nocombine = true, underline = true })
vim.api.nvim_set_hl(0,'@markup.raw',{ link = "String" })
vim.api.nvim_set_hl(0,'MiniJump',{ bg = "#59335b", sp = "#fa90ea", undercurl = true })
vim.api.nvim_set_hl(0,'@markup.list.checked',{ fg = "#7fca5a" })
vim.api.nvim_set_hl(0,'MiniIndentscopeSymbol',{ fg = "#78afff", nocombine = true })
vim.api.nvim_set_hl(0,'@markup.list.unchecked',{ fg = "#57aff6" })
vim.api.nvim_set_hl(0,'@comment',{ link = "Comment" })
vim.api.nvim_set_hl(0,'Whitespace',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'@markup.math',{ link = "Special" })
vim.api.nvim_set_hl(0,'SignColumn',{ bg = "#222524", fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'FloatBorder',{ bg = "#303332", fg = "#7d7f82" })
vim.api.nvim_set_hl(0,'LineNr',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'NormalFloat',{ bg = "#303332", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'LspKindUnit',{ fg = "#6fcfd2" })
vim.api.nvim_set_hl(0,'LspKindTypeParameter',{ fg = "#6fcfd2" })
vim.api.nvim_set_hl(0,'LspKindText',{ fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'LspKindStruct',{ fg = "#6fcfd2" })
vim.api.nvim_set_hl(0,'LspKindString',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'LspKindSnippet',{ fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'LspKindReference',{ fg = "#7fca5a" })
vim.api.nvim_set_hl(0,'LspKindProperty',{}) vim.api.nvim_set_hl(0,'LspKindPackage',{ fg = "#fa90ea" })
vim.api.nvim_set_hl(0,'LspKindOperator',{ fg = "#969faf" }) vim.api.nvim_set_hl(0,'LspKindObject',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'LspKindNumber',{ fg = "#cfaaff" }) vim.api.nvim_set_hl(0,'LspKindNull',{ fg = "#d0b9f0" })
vim.api.nvim_set_hl(0,'LspKindNamespace',{ fg = "#fa90ea" }) vim.api.nvim_set_hl(0,'LspKindModule',{ fg = "#fa90ea" })
vim.api.nvim_set_hl(0,'LspKindMethod',{ fg = "#fa90ea" }) vim.api.nvim_set_hl(0,'LspKindKeyword',{ fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'LspKindKey',{ fg = "#cfaaff" }) vim.api.nvim_set_hl(0,'LspKindInterface',{ fg = "#f59acf" }) 
vim.api.nvim_set_hl(0,'LspKindFunction',{ fg = "#7fca5a" }) vim.api.nvim_set_hl(0,'LspKindFolder',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'LspKindFile',{ fg = "#eaf2ef" }) vim.api.nvim_set_hl(0,'LspKindField',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'LspKindEvent',{ fg = "#cfaaff" }) vim.api.nvim_set_hl(0,'LspKindEnumMember',{
  fg = "#6fcfd2"
})
vim.api.nvim_set_hl(0,'LspKindEnum',{ fg = "#6fcfd2" }) vim.api.nvim_set_hl(0,'LspKindConstructor',{ fg = "#f59acf"
})
vim.api.nvim_set_hl(0,'LspKindConstant',{ fg = "#cfaaff" }) vim.api.nvim_set_hl(0,'LspKindColor',{
  fg = "#50cf89"
})
vim.api.nvim_set_hl(0,'LspKindClass',{ fg = "#6fcfd2" }) vim.api.nvim_set_hl(0,'LspKindBoolean',{ fg = "#cfaaff"
})
vim.api.nvim_set_hl(0,'LspKindArray',{ fg = "#969faf" }) vim.api.nvim_set_hl(0,'LspInlayHint',{
  bg = "#2b2e2d",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0,'LspInfoBorder',{ bg = "#303332", fg = "#5d5f63" }) vim.api.nvim_set_hl(0,'LspCodeLens',{ fg = "#cac89f" })
vim.api.nvim_set_hl(0,'LineNrBelow',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'LineNrAbove',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'Italic',{ fg = "#eaf2ef", italic = true })
vim.api.nvim_set_hl(0,'Folded',{ bg = "#3e4140", fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'FoldColumn',{ bg = "#222524", fg = "#cac89f" })
vim.api.nvim_set_hl(0,'EndOfBuffer',{ fg = "#222524" })
vim.api.nvim_set_hl(0,'DiffText',{ bg = "#136244" })
vim.api.nvim_set_hl(0,'MiniIconsRed',{ fg = "#ff656a" })
vim.api.nvim_set_hl(0,'MiniIconsPurple',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextWarn',{ bg = "#424223", fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextInfo',{ bg = "#104420", fg = "#50cf89" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextHint',{ bg = "#104420", fg = "#50cf89" })
vim.api.nvim_set_hl(0,'DiagnosticVirtualTextError',{ bg = "#551525", fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineWarn',{ sp = "#e0b02f", undercurl = true })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineInfo',{ sp = "#50cf89", undercurl = true })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineHint',{ sp = "#50cf89", undercurl = true })
vim.api.nvim_set_hl(0,'DiagnosticUnderlineError',{ sp = "#ff7a5f", undercurl = true })
vim.api.nvim_set_hl(0,'Debug',{ fg = "#cfb27f" })
vim.api.nvim_set_hl(0,'CursorLineNr',{ bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniHipatternsFixme',{ bg = "#551525", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'CursorIM',{ link = "Cursor" })
vim.api.nvim_set_hl(0,'MiniFilesTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'CurSearch',{ bg = "#847020" })
vim.api.nvim_set_hl(0,'Conceal',{ fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'MiniFilesDirectory',{ link = "Directory" })
vim.api.nvim_set_hl(0,'MiniFilesCursorLine',{ link = "CursorLine" })
vim.api.nvim_set_hl(0,'MiniFilesBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniDiffSignDelete',{ fg = "#ffbfbf" })
vim.api.nvim_set_hl(0,'MiniDiffSignChange',{ fg = "#dada90" })
vim.api.nvim_set_hl(0,'MiniDiffSignAdd',{ fg = "#a0e0a0" })
vim.api.nvim_set_hl(0,'MiniDiffOverDelete',{ link = "DiffDelete" })
vim.api.nvim_set_hl(0,'MiniDiffOverContext',{ link = "DiffChange" })
vim.api.nvim_set_hl(0,'MiniDiffOverChange',{ link = "DiffText" })
vim.api.nvim_set_hl(0,'MiniDiffOverAdd',{ link = "DiffAdd" })
vim.api.nvim_set_hl(0,'MiniDepsTitleUpdate',{ bg = "#62432a", fg = "#cac85f" })
vim.api.nvim_set_hl(0,'MatchParen',{ bg = "#3f6f5f", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniDepsTitleSame',{ link = "Comment" })
vim.api.nvim_set_hl(0,'MiniDepsTitleError',{ bg = "#5e242f", fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'BlinkCmpKindSupermaven',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'MiniDepsTitle',{ link = "Title" })
vim.api.nvim_set_hl(0,'MiniDepsPlaceholder',{ link = "Comment" })
vim.api.nvim_set_hl(0,'MiniDepsMsgBreaking',{ link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0,'MiniDepsInfo',{ link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0,'MiniDepsHint',{ link = "DiagnosticHint" })
vim.api.nvim_set_hl(0,'MiniDepsChangeRemoved',{ link = "diffRemoved" })
vim.api.nvim_set_hl(0,'MiniDepsChangeAdded',{ link = "diffAdded" })
vim.api.nvim_set_hl(0,'MiniCursorwordCurrent',{ underline = true })
vim.api.nvim_set_hl(0,'MiniCursorword',{ underline = true })
vim.api.nvim_set_hl(0,'MiniCompletionActiveParameter',{ underline = true })
vim.api.nvim_set_hl(0,'MiniClueTitle',{ link = "FloatTitle" })
vim.api.nvim_set_hl(0,'MiniClueSeparator',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'MiniClueNextKeyWithPostkeys',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'MiniClueNextKey',{ bold = true, fg = "#f59acf" })
vim.api.nvim_set_hl(0,'MiniClueDescSingle',{ fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniClueDescGroup',{ bg = "#303332", fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'MiniClueBorder',{ link = "FloatBorder" })
vim.api.nvim_set_hl(0,'MiniAnimateNormalFloat',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniAnimateCursor',{ nocombine = true, reverse = true })
vim.api.nvim_set_hl(0,'BlinkCmpKindField',{ link = "LspKindField" })
vim.api.nvim_set_hl(0,'LspSignatureActiveParameter',{ bg = "#894f7a", bold = true })
vim.api.nvim_set_hl(0,'BlinkCmpKindEnumMember',{ link = "LspKindEnumMember" })
vim.api.nvim_set_hl(0,'LspReferenceWrite',{ bg = "#303332" })
vim.api.nvim_set_hl(0,'LspReferenceText',{ bg = "#303332" })
vim.api.nvim_set_hl(0,'LspReferenceRead',{ bg = "#303332" })
vim.api.nvim_set_hl(0,'LspKindVariable',{ fg = "#f59acf" })
vim.api.nvim_set_hl(0,'LspKindValue',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'BlinkCmpKindColor',{ link = "LspKindColor" })
vim.api.nvim_set_hl(0,'BlinkCmpKindCodeium',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindClass',{ link = "LspKindClass" })
vim.api.nvim_set_hl(0,'BlinkCmpKindBoolean',{ link = "LspKindBoolean" })
vim.api.nvim_set_hl(0,'BlinkCmpKindArray',{ link = "LspKindArray" })
vim.api.nvim_set_hl(0,'BlinkCmpGhostText',{ fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'BlinkCmpDocBorder',{ bg = "#303332", fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'BlinkCmpDoc',{ bg = "#303332", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'@variable.parameter',{ fg = "#cac85f" })
vim.api.nvim_set_hl(0,'@variable.member',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'@variable.builtin',{ bold = true, fg = "#d0b9f0" })
vim.api.nvim_set_hl(0,'@variable',{ link = "Variable" })
vim.api.nvim_set_hl(0,'@type.qualifier',{ link = "@keyword" })
vim.api.nvim_set_hl(0,'@keyword',{ bold = true, fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'@type.definition',{ link = "Typedef" })
vim.api.nvim_set_hl(0,'@type.builtin',{ bold = true, fg = "#d0b9f0" })
vim.api.nvim_set_hl(0,'@tag.tsx',{ fg = "#ff656a" })
vim.api.nvim_set_hl(0,'@tag.javascript',{ fg = "#ff656a" })
vim.api.nvim_set_hl(0,'@tag.delimiter',{ link = "Delimiter" })
vim.api.nvim_set_hl(0,'@tag.attribute',{ link = "@property" })
vim.api.nvim_set_hl(0,'@tag',{ link = "Label" })
vim.api.nvim_set_hl(0,'@string.regexp',{ fg = "#62cfef" })
vim.api.nvim_set_hl(0,'@string.escape',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'@string.documentation',{ fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'@string',{ link = "String" })
vim.api.nvim_set_hl(0,'@punctuation.special.markdown',{ fg = "#78afff" })
vim.api.nvim_set_hl(0,'@punctuation.special',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'@punctuation.bracket',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'@operator',{ bold = true, fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'@number.float',{ link = "Float" })
vim.api.nvim_set_hl(0,'@number',{ link = "Number" })
vim.api.nvim_set_hl(0,'@none',{})
vim.api.nvim_set_hl(0,'@namespace.builtin',{ link = "@variable.builtin" })
vim.api.nvim_set_hl(0,'@module.builtin',{ fg = "#ff656a" })
vim.api.nvim_set_hl(0,'@module',{ link = "Include" })
vim.api.nvim_set_hl(0,'@markup.underline',{ underline = true }) 
vim.api.nvim_set_hl(0,'@markup.strong',{ bold = true })
vim.api.nvim_set_hl(0,'@markup.strikethrough',{ strikethrough = true })
vim.api.nvim_set_hl(0,'@markup.raw.markdown_inline',{ fg = "#f59acf" })
vim.api.nvim_set_hl(0,'@markup.list.markdown',{ bold = true, fg = "#cfb27f" })
vim.api.nvim_set_hl(0,'@markup.list',{ fg = "#6ab4ef" })
vim.api.nvim_set_hl(0,'@markup.link.url',{ fg = "#8fcfbb" })
vim.api.nvim_set_hl(0,'@markup.link.label.symbol',{ link = "Identifier" })
vim.api.nvim_set_hl(0,'@markup.link.label',{ fg = "#7fca5a", underline = true })
vim.api.nvim_set_hl(0,'@markup.link',{ fg = "#7fca5a", underline = true })
vim.api.nvim_set_hl(0,'@markup.italic',{ italic = true }) vim.api.nvim_set_hl(0,'@markup.environment.name',{ link = "Type" })
vim.api.nvim_set_hl(0,'@markup.environment',{ link = "Macro" })
vim.api.nvim_set_hl(0,'@markup.emphasis',{ italic = true })
vim.api.nvim_set_hl(0,'@markup',{ link = "@none" })
vim.api.nvim_set_hl(0,'@keyword.storage',{ link = "StorageClass" })
vim.api.nvim_set_hl(0,'Identifier',{ fg = "#d0b9f0" })
vim.api.nvim_set_hl(0,'@function.method',{ link = "Function" })
vim.api.nvim_set_hl(0,'@function.macro',{ link = "Macro" })
vim.api.nvim_set_hl(0,'@function.call',{ link = "@function" })
vim.api.nvim_set_hl(0,'@function',{ link = "Function" })
vim.api.nvim_set_hl(0,'@function.builtin',{ link = "Special" })
vim.api.nvim_set_hl(0,'@diff.plus',{ link = "DiffAdd" })
vim.api.nvim_set_hl(0,'@diff.minus',{ link = "DiffDelete" })
vim.api.nvim_set_hl(0,'@diff.delta',{ link = "DiffChange" })
vim.api.nvim_set_hl(0,'@constructor.tsx',{ fg = "#62cfef" })
vim.api.nvim_set_hl(0,'@constructor',{ fg = "#f59acf" })
vim.api.nvim_set_hl(0,'@constant.macro',{ link = "Define" })
vim.api.nvim_set_hl(0,'@constant.builtin',{ link = "Special" })
vim.api.nvim_set_hl(0,'@constant',{ link = "Constant" })
vim.api.nvim_set_hl(0,'Directory',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'@comment.todo',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'@comment.note',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'@comment.info',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'String',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'@comment.error',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'@character.special',{ link = "SpecialChar" })
vim.api.nvim_set_hl(0,'@character.printf',{ link = "SpecialChar" })
vim.api.nvim_set_hl(0,'Statement',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'Bold',{ bold = true, fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'Search',{ bg = "#2f5f9f", fg = "#ffffff" })
vim.api.nvim_set_hl(0,'Title',{ fg = "#7fca5a" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingOk',{ bg = "#303332", fg = "#50cf89" })
vim.api.nvim_set_hl(0,'Comment',{ fg = "#cac89f", italic = true })
vim.api.nvim_set_hl(0,'DiagnosticFloatingHint',{ bg = "#303332", fg = "#50cf89" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingInfo',{ bg = "#303332", fg = "#50cf89" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingWarn',{ bg = "#303332", fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'DiagnosticFloatingError',{ bg = "#303332", fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'PmenuSbar',{ bg = "#2b2e2d" })
vim.api.nvim_set_hl(0,'PmenuExtraSel',{ link = "PmenuSel" })
vim.api.nvim_set_hl(0,'ErrorMsg',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'MoreMsg',{ fg = "#57aff6" })
vim.api.nvim_set_hl(0,'PmenuExtra',{ link = "Pmenu" })
vim.api.nvim_set_hl(0,'PmenuKindSel',{ link = "PmenuSel" })
vim.api.nvim_set_hl(0,'PmenuKind',{ link = "Pmenu" })
vim.api.nvim_set_hl(0,'FloatFooter',{ bg = "#303332", fg = "#7d7f82" })
vim.api.nvim_set_hl(0,'@markup.heading.6.markdown',{ link = "markdownH6" })
vim.api.nvim_set_hl(0,'@markup.heading.5.markdown',{ link = "markdownH5" })
vim.api.nvim_set_hl(0,'Type',{ bold = true, fg = "#6fcfd2" })
vim.api.nvim_set_hl(0,'DiagnosticWarn',{ fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'@markup.heading.4.markdown',{ link = "markdownH4" })
vim.api.nvim_set_hl(0,'DiagnosticError',{ fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'@markup.heading.3.markdown',{ link = "markdownH3" })
vim.api.nvim_set_hl(0,'@markup.heading.2.markdown',{ link = "markdownH2" })
vim.api.nvim_set_hl(0,'@comment.warning',{ fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'DiagnosticInfo',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'BlinkCmpKindString',{ link = "LspKindString" })
vim.api.nvim_set_hl(0,'Todo',{ bg = "#e0b02f", fg = "#ff7a5f" })
vim.api.nvim_set_hl(0,'BlinkCmpKindStruct',{ link = "LspKindStruct" })
vim.api.nvim_set_hl(0,'BlinkCmpKindVariable',{ link = "LspKindVariable" })
vim.api.nvim_set_hl(0,'MiniHipatternsTodo',{ bg = "#104420", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniIconsCyan',{ fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindPackage',{ link = "LspKindPackage" })
vim.api.nvim_set_hl(0,'BlinkCmpKindOperator',{ link = "LspKindOperator" })
vim.api.nvim_set_hl(0,'BlinkCmpKindReference',{ link = "LspKindReference" })
vim.api.nvim_set_hl(0,'BlinkCmpKindObject',{ link = "LspKindObject" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNumber',{ link = "LspKindNumber" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNull',{ link = "LspKindNull" })
vim.api.nvim_set_hl(0,'BlinkCmpKindNamespace',{ link = "LspKindNamespace" })
vim.api.nvim_set_hl(0,'BlinkCmpKindModule',{ link = "LspKindModule" })
vim.api.nvim_set_hl(0,'Normal',{ bg = "#222524", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'BlinkCmpKindMethod',{ link = "LspKindMethod" })
vim.api.nvim_set_hl(0,'BlinkCmpKindKeyword',{ link = "LspKindKeyword" })
vim.api.nvim_set_hl(0,'BlinkCmpKindKey',{ link = "LspKindKey" })
vim.api.nvim_set_hl(0,'BlinkCmpKindInterface',{ link = "LspKindInterface" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFunction',{ link = "LspKindFunction" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFolder',{ link = "LspKindFolder" })
vim.api.nvim_set_hl(0,'Operator',{ link = "Bold" })
vim.api.nvim_set_hl(0,'BlinkCmpKindFile',{ link = "LspKindFile" })
vim.api.nvim_set_hl(0,'BlinkCmpKindEvent',{ link = "LspKindEvent" })
vim.api.nvim_set_hl(0,'MiniIconsGrey',{ fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindEnum',{ link = "LspKindEnum" })
vim.api.nvim_set_hl(0,'DiffDelete',{ bg = "#5e242f", fg = "#ffbfbf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindDefault',{ bg = "NONE", fg = "#969faf" })
vim.api.nvim_set_hl(0,'Keyword',{ bold = true, fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'BlinkCmpKindCopilot',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindConstructor',{ link = "LspKindConstructor" })
vim.api.nvim_set_hl(0,'BlinkCmpKindConstant',{ link = "LspKindConstant" })
vim.api.nvim_set_hl(0,'BlinkCmpSignatureHelp',{ bg = "#303332", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'BlinkCmpMenuBorder',{ bg = "#303332", fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'BlinkCmpMenu',{ bg = "#2b2e2d", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedHidden',{ bg = "#35605d", fg = "#551525" })
vim.api.nvim_set_hl(0,'Variable',{ fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'MiniTablineModifiedCurrent',{ bg = "#424223", fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'MiniTablineHidden',{ bg = "#303332", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'Function',{ fg = "#7fca5a" })
vim.api.nvim_set_hl(0,'MiniIconsGreen',{ fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'NonText',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'MiniTablineFill',{ bg = "#3e4140" })
vim.api.nvim_set_hl(0,'Pmenu',{ bg = "#2b2e2d", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'CursorColumn',{ bg = "#3e4140" })
vim.api.nvim_set_hl(0,'Constant',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'ColorColumn',{ bg = "#3e4140" })
vim.api.nvim_set_hl(0,'@label',{ fg = "#57aff6" })
vim.api.nvim_set_hl(0,'MiniJump2dDim',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'MiniIndentscopePrefix',{ nocombine = true })
vim.api.nvim_set_hl(0,'MiniIconsYellow',{ fg = "#cac89f" })
vim.api.nvim_set_hl(0,'MiniIconsOrange',{ fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'DiffAdd',{ bg = "#20493f", fg = "#a0e0a0" })
vim.api.nvim_set_hl(0,'MiniIconsBlue',{ fg = "#6ab4ef" })
vim.api.nvim_set_hl(0,'MiniIconsAzure',{ fg = "#78afff" })
vim.api.nvim_set_hl(0,'MiniHipatternsNote',{ bg = "#2f5f9f", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniHipatternsHack',{ bg = "#424223", bold = true, fg = "#ffffff" })
vim.api.nvim_set_hl(0,'MiniFilesTitleFocused',{ bg = "#303332", bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'MiniFilesNormal',{ link = "NormalFloat" })
vim.api.nvim_set_hl(0,'MiniFilesFile',{ fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'Special',{ fg = "#6ab4ef" })
vim.api.nvim_set_hl(0,'BlinkCmpLabel',{ bg = "NONE", fg = "#eaf2ef" })
vim.api.nvim_set_hl(0,'BlinkCmpKindUnit',{ link = "LspKindUnit" })
vim.api.nvim_set_hl(0,'BlinkCmpKindText',{ link = "LspKindText" })
vim.api.nvim_set_hl(0,'DiffChange',{ bg = "#51512f", fg = "#dada90" })
vim.api.nvim_set_hl(0,'BlinkCmpKindTabNine',{ bg = "NONE", fg = "#99bfcf" })
vim.api.nvim_set_hl(0,'@function.method.call',{ link = "@function.method" })
vim.api.nvim_set_hl(0,'Visual',{ bg = "#543040", fg = "NONE" })
vim.api.nvim_set_hl(0,'WarningMsg',{ bold = true, fg = "#e0b02f" })
vim.api.nvim_set_hl(0,'healthSuccess',{ fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'BlinkCmpSignatureHelpBorder',{ bg = "#303332", fg = "#5d5f63" })
vim.api.nvim_set_hl(0,'BlinkCmpLabelMatch',{ bg = "NONE", bold = true, fg = "#50cf89" })
vim.api.nvim_set_hl(0,'BlinkCmpLabelDeprecated',{ bg = "NONE", fg = "#969faf", strikethrough = true })
vim.api.nvim_set_hl(0,'BlinkCmpKindValue',{ link = "LspKindValue" })
vim.api.nvim_set_hl(0,'BlinkCmpKindTypeParameter',{ link = "LspKindTypeParameter" })
vim.api.nvim_set_hl(0,'@comment.hint',{ fg = "#50cf89" })
vim.api.nvim_set_hl(0,'BlinkCmpKindSnippet',{ link = "LspKindSnippet" })
vim.api.nvim_set_hl(0,'Character',{ fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'qfLineNr',{ fg = "#969faf" })
vim.api.nvim_set_hl(0,'BlinkCmpKindProperty',{ link = "LspKindProperty" })
vim.api.nvim_set_hl(0,'qfFileName',{ fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'markdownH6',{ bold = true, fg = "#7fc87f" })
vim.api.nvim_set_hl(0,'markdownH5',{ bold = true, fg = "#f59acf" })
vim.api.nvim_set_hl(0,'markdownH4',{ bold = true, fg = "#cfaaff" })
vim.api.nvim_set_hl(0,'markdownH3',{ bold = true, fg = "#60d5c2" })
vim.api.nvim_set_hl(0,'markdownH2',{ bold = true, fg = "#a9c99f" })
vim.api.nvim_set_hl(0,'@markup.heading',{ link = "Title" })
vim.api.nvim_set_hl(0,'markdownH1',{ bold = true, fg = "#eba8a8" })
vim.api.nvim_set_hl(0,'@markup.heading.1.markdown',{ link = "markdownH1" })
vim.api.nvim_set_hl(0,'lCursor',{ link = "Cursor" })
vim.api.nvim_set_hl(0,'Cursor',{ bg = "#ef7fa8", fg = "#222524" })
vim.api.nvim_set_hl(0,'htmlH6',{ link = "markdownH6" })
vim.api.nvim_set_hl(0,'htmlH5',{ link = "markdownH5" })
vim.api.nvim_set_hl(0,'htmlH4',{ link = "markdownH4" })
vim.api.nvim_set_hl(0,'htmlH3',{ link = "markdownH3" })
vim.api.nvim_set_hl(0,'htmlH2',{ link = "markdownH2" })
vim.api.nvim_set_hl(0,'htmlH1',{ link = "markdownH1" })
