vim.api.nvim_set_hl(0, "@annotation",{ link = "TSAnnotation" })
vim.api.nvim_set_hl(0, "@attribute",{ link = "TSAttribute" })
vim.api.nvim_set_hl(0, "@boolean",{ link = "TSBoolean" })
vim.api.nvim_set_hl(0, "@boolean.yaml",{ link = "yamlTSBoolean" })
vim.api.nvim_set_hl(0, "@character",{ link = "TSCharacter" })
vim.api.nvim_set_hl(0, "@character.special",{ link = "TSCharacterSpecial" })
vim.api.nvim_set_hl(0, "@comment",{ link = "TSComment" })
vim.api.nvim_set_hl(0, "@conceal",{ link = "Grey" })
vim.api.nvim_set_hl(0, "@conditional",{ link = "TSConditional" })
vim.api.nvim_set_hl(0, "@constant",{ link = "TSConstant" })
vim.api.nvim_set_hl(0, "@constant.builtin",{ link = "TSConstBuiltin" })
vim.api.nvim_set_hl(0, "@constant.builtin.go",{ link = "goTSConstBuiltin" })
vim.api.nvim_set_hl(0, "@constant.builtin.yaml",{ link = "yamlTSConstBuiltin" })
vim.api.nvim_set_hl(0, "@constant.macro",{ link = "TSConstMacro" })
vim.api.nvim_set_hl(0, "@constructor",{ link = "TSConstructor" })
vim.api.nvim_set_hl(0, "@constructor.javascript",{ link = "javascriptTSConstructor" })
vim.api.nvim_set_hl(0, "@constructor.lua",{ link = "luaTSConstructor" })
vim.api.nvim_set_hl(0, "@debug",{ link = "TSDebug" })
vim.api.nvim_set_hl(0, "@define",{ link = "TSDefine" })
vim.api.nvim_set_hl(0, "@error",{ link = "TSError" })
vim.api.nvim_set_hl(0, "@exception",{ link = "TSException" })
vim.api.nvim_set_hl(0, "@field",{ link = "TSField" })
vim.api.nvim_set_hl(0, "@field.lua",{ link = "luaTSField" })
vim.api.nvim_set_hl(0, "@field.yaml",{ link = "yamlTSField" })
vim.api.nvim_set_hl(0, "@float",{ link = "TSFloat" })
vim.api.nvim_set_hl(0, "@function",{ link = "TSFunction" })
vim.api.nvim_set_hl(0, "@function.builtin",{ link = "TSFuncBuiltin" })
vim.api.nvim_set_hl(0, "@function.call",{ link = "TSFunctionCall" })
vim.api.nvim_set_hl(0, "@function.macro",{ link = "TSFuncMacro" })
vim.api.nvim_set_hl(0, "@include",{ link = "TSInclude" })
vim.api.nvim_set_hl(0, "@include.go",{ link = "goTSInclude" })
vim.api.nvim_set_hl(0, "@include.javascript",{ link = "javascriptTSInclude" })
vim.api.nvim_set_hl(0, "@keyword",{ link = "TSKeyword" })
vim.api.nvim_set_hl(0, "@keyword.function",{ link = "TSKeywordFunction" })
vim.api.nvim_set_hl(0, "@keyword.operator",{ link = "TSKeywordOperator" })
vim.api.nvim_set_hl(0, "@keyword.return",{ link = "TSKeywordReturn" })
vim.api.nvim_set_hl(0, "@label",{ link = "TSLabel" })
vim.api.nvim_set_hl(0, "@label.json",{ link = "jsonTSLabel" })
vim.api.nvim_set_hl(0, "@math",{ link = "TSMath" })
vim.api.nvim_set_hl(0, "@method",{ link = "TSMethod" })
vim.api.nvim_set_hl(0, "@method.call",{ link = "TSMethodCall" })
vim.api.nvim_set_hl(0, "@namespace",{ link = "TSNamespace" })
vim.api.nvim_set_hl(0, "@namespace.go",{ link = "goTSNamespace" })
vim.api.nvim_set_hl(0, "@none",{ link = "TSNone" })
vim.api.nvim_set_hl(0, "@number",{ link = "TSNumber" })
vim.api.nvim_set_hl(0, "@operator",{ link = "TSOperator" })
vim.api.nvim_set_hl(0, "@parameter",{ link = "TSParameter" })
vim.api.nvim_set_hl(0, "@parameter.reference",{ link = "TSParameterReference" })
vim.api.nvim_set_hl(0, "@preproc",{ link = "TSPreProc" })
vim.api.nvim_set_hl(0, "@property",{ link = "TSProperty" })
vim.api.nvim_set_hl(0, "@property.go",{ link = "goTSProperty" })
vim.api.nvim_set_hl(0, "@property.toml",{ link = "tomlTSProperty" })
vim.api.nvim_set_hl(0, "@punctuation.bracket",{ link = "TSPunctBracket" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter",{ link = "TSPunctDelimiter" })
vim.api.nvim_set_hl(0, "@punctuation.special",{ link = "TSPunctSpecial" })
vim.api.nvim_set_hl(0, "@repeat",{ link = "TSRepeat" })
vim.api.nvim_set_hl(0, "@storageclass",{ link = "TSStorageClass" })
vim.api.nvim_set_hl(0, "@storageclass.lifetime",{ link = "TSStorageClassLifetime" })
vim.api.nvim_set_hl(0, "@strike",{ link = "TSStrike" })
vim.api.nvim_set_hl(0, "@string",{ link = "TSString" })
vim.api.nvim_set_hl(0, "@string.escape",{ link = "TSStringEscape" })
vim.api.nvim_set_hl(0, "@string.escape.yaml",{ link = "yamlTSStringEscape" })
vim.api.nvim_set_hl(0, "@string.json",{ link = "jsonTSString" })
vim.api.nvim_set_hl(0, "@string.regex",{ link = "TSStringRegex" })
vim.api.nvim_set_hl(0, "@string.special",{ link = "TSStringSpecial" })
vim.api.nvim_set_hl(0, "@string.toml",{ link = "tomlTSString" })
vim.api.nvim_set_hl(0, "@string.yaml",{ link = "yamlTSString" })
vim.api.nvim_set_hl(0, "@symbol",{ link = "TSSymbol" })
vim.api.nvim_set_hl(0, "@tag",{ link = "TSTag" })
vim.api.nvim_set_hl(0, "@tag.delimiter",{ link = "TSTagDelimiter" })
vim.api.nvim_set_hl(0, "@text",{ link = "TSText" })
vim.api.nvim_set_hl(0, "@text.danger",{ link = "TSDanger" })
vim.api.nvim_set_hl(0, "@text.diff.add",{ link = "diffAdded" })
vim.api.nvim_set_hl(0, "@text.diff.delete",{ link = "diffRemoved" })
vim.api.nvim_set_hl(0, "@text.emphasis",{ link = "TSEmphasis" })
vim.api.nvim_set_hl(0, "@text.environment",{ link = "TSEnvironment" })
vim.api.nvim_set_hl(0, "@text.environment.name",{ link = "TSEnvironmentName" })
vim.api.nvim_set_hl(0, "@text.literal",{ link = "TSLiteral" })
vim.api.nvim_set_hl(0, "@text.math",{ link = "TSMath" })
vim.api.nvim_set_hl(0, "@text.note",{ link = "TSNote" })
vim.api.nvim_set_hl(0, "@text.reference",{ link = "TSTextReference" })
vim.api.nvim_set_hl(0, "@text.strong",{ link = "TSStrong" })
vim.api.nvim_set_hl(0, "@text.title",{ link = "TSTitle" })
vim.api.nvim_set_hl(0, "@text.todo",{ link = "TSTodo" })
vim.api.nvim_set_hl(0, "@text.underline",{ link = "TSUnderline" })
vim.api.nvim_set_hl(0, "@text.uri",{ link = "TSURI" })
vim.api.nvim_set_hl(0, "@text.warning",{ link = "TSWarning" })
vim.api.nvim_set_hl(0, "@todo",{ link = "TSTodo" })
vim.api.nvim_set_hl(0, "@type",{ link = "TSType" })
vim.api.nvim_set_hl(0, "@type.builtin",{ link = "TSTypeBuiltin" })
vim.api.nvim_set_hl(0, "@type.definition",{ link = "TSTypeDefinition" })
vim.api.nvim_set_hl(0, "@type.qualifier",{ link = "TSTypeQualifier" })
vim.api.nvim_set_hl(0, "@uri",{ link = "TSURI" })
vim.api.nvim_set_hl(0, "@variable",{ link = "TSVariable" })
vim.api.nvim_set_hl(0, "@variable.builtin",{ link = "TSVariableBuiltin" })
vim.api.nvim_set_hl(0, "AerialArrayIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialBooleanIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialClassIcon",{ link = "Red" })
vim.api.nvim_set_hl(0, "AerialConstantIcon",{ link = "Blue" })
vim.api.nvim_set_hl(0, "AerialConstructorIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "AerialEnumIcon",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "AerialEnumMemberIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialEventIcon",{ link = "Orange" })
vim.api.nvim_set_hl(0, "AerialFieldIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "AerialFileIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "AerialFunctionIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "AerialGuide",{ link = "LineNr" })
vim.api.nvim_set_hl(0, "AerialInterfaceIcon",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "AerialKeyIcon",{ link = "Red" })
vim.api.nvim_set_hl(0, "AerialLine",{ link = "CursorLine" })
vim.api.nvim_set_hl(0, "AerialMethodIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "AerialModuleIcon",{ link = "Purple" })
vim.api.nvim_set_hl(0, "AerialNamespaceIcon",{ link = "Purple" })
vim.api.nvim_set_hl(0, "AerialNullIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialNumberIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialObjectIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialOperatorIcon",{ link = "Orange" })
vim.api.nvim_set_hl(0, "AerialPackageIcon",{ link = "Purple" })
vim.api.nvim_set_hl(0, "AerialPropertyIcon",{ link = "Blue" })
vim.api.nvim_set_hl(0, "AerialStringIcon",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "AerialStructIcon",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "AerialTypeParameterIcon",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "AerialVariableIcon",{ link = "Blue" })
vim.api.nvim_set_hl(0, "Aqua",{ bg = "NONE", fg = "#83c092" })
vim.api.nvim_set_hl(0, "AquaItalic",{ bg = "NONE", fg = "#83c092" })
vim.api.nvim_set_hl(0, "AquaSign",{ bg = "#2e383c", fg = "#83c092" })
vim.api.nvim_set_hl(0, "Blamer",{ link = "Grey" })
vim.api.nvim_set_hl(0, "Blue",{ bg = "NONE", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "BlueItalic",{ bg = "NONE", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "BlueSign",{ bg = "#2e383c", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "BookmarkAnnotationLine",{ link = "DiffAdd" })
vim.api.nvim_set_hl(0, "BookmarkAnnotationSign",{ link = "GreenSign" })
vim.api.nvim_set_hl(0, "BookmarkLine",{ link = "DiffChange" })
vim.api.nvim_set_hl(0, "BookmarkSign",{ link = "BlueSign" })
vim.api.nvim_set_hl(0, "Boolean",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "BufTabLineActive",{ link = "TabLine" })
vim.api.nvim_set_hl(0, "BufTabLineCurrent",{ link = "TabLineSel" })
vim.api.nvim_set_hl(0, "BufTabLineFill",{ link = "TabLineFill" })
vim.api.nvim_set_hl(0, "BufTabLineHidden",{ link = "TabLineFill" })
vim.api.nvim_set_hl(0, "BufferCurrent",{ bg = "#272e33", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "BufferCurrentIndex",{ bg = "#272e33", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "BufferCurrentMod",{ bg = "#272e33", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "BufferCurrentSign",{ bg = "#272e33", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "BufferCurrentTarget",{ bg = "#272e33", bold = true, fg = "#e67e80" })
vim.api.nvim_set_hl(0, "BufferInactive",{ bg = "#1e2326", fg = "#859289" })
vim.api.nvim_set_hl(0, "BufferInactiveIndex",{ bg = "#1e2326", fg = "#859289" })
vim.api.nvim_set_hl(0, "BufferInactiveMod",{ bg = "#1e2326", fg = "#859289" })
vim.api.nvim_set_hl(0, "BufferInactiveSign",{ bg = "#1e2326", fg = "#7a8478" })
vim.api.nvim_set_hl(0, "BufferInactiveTarget",{ bg = "#1e2326", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "BufferLineIndicatorSelected",{ link = "GreenSign" })
vim.api.nvim_set_hl(0, "BufferTabpageFill",{ bg = "#1e2326", fg = "#1e2326" })
vim.api.nvim_set_hl(0, "BufferTabpages",{ bg = "#1e2326", bold = true, fg = "#859289" })
vim.api.nvim_set_hl(0, "BufferVisible",{ bg = "#1e2326", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "BufferVisibleIndex",{ bg = "#1e2326", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "BufferVisibleMod",{ bg = "#1e2326", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "BufferVisibleSign",{ bg = "#1e2326", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "BufferVisibleTarget",{ bg = "#1e2326", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "Character",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "CleverFDefaultLabel",{ link = "Search" })
vim.api.nvim_set_hl(0, "CmpItemAbbr",{ link = "Fg" })
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated",{ link = "Grey" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch",{ bg = "NONE", bold = true, fg = "#a7c080" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy",{ bg = "NONE", bold = true, fg = "#a7c080" })
vim.api.nvim_set_hl(0, "CmpItemKind",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindClass",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindColor",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "CmpItemKindConstant",{ link = "Blue" })
vim.api.nvim_set_hl(0, "CmpItemKindConstructor",{ link = "Green" })
vim.api.nvim_set_hl(0, "CmpItemKindEnum",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember",{ link = "Purple" })
vim.api.nvim_set_hl(0, "CmpItemKindEvent",{ link = "Orange" })
vim.api.nvim_set_hl(0, "CmpItemKindField",{ link = "Green" })
vim.api.nvim_set_hl(0, "CmpItemKindFile",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "CmpItemKindFolder",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "CmpItemKindFunction",{ link = "Green" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword",{ link = "Red" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod",{ link = "Green" })
vim.api.nvim_set_hl(0, "CmpItemKindModule",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindOperator",{ link = "Orange" })
vim.api.nvim_set_hl(0, "CmpItemKindProperty",{ link = "Blue" })
vim.api.nvim_set_hl(0, "CmpItemKindReference",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "CmpItemKindStruct",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindText",{ link = "Fg" })
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "CmpItemKindUnit",{ link = "Purple" })
vim.api.nvim_set_hl(0, "CmpItemKindValue",{ link = "Purple" })
vim.api.nvim_set_hl(0, "CmpItemKindVariable",{ link = "Blue" })
vim.api.nvim_set_hl(0, "CmpItemMenu",{ link = "Fg" })
vim.api.nvim_set_hl(0, "ColorColumn",{ bg = "#2e383c", fg = "NONE" })
vim.api.nvim_set_hl(0, "Comment",{ bg = "NONE", fg = "#859289", italic = true })
vim.api.nvim_set_hl(0, "Conceal",{ bg = "NONE", fg = "#4f5b58" })
vim.api.nvim_set_hl(0, "Conditional",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "Constant",{ bg = "NONE", fg = "#83c092" })
vim.api.nvim_set_hl(0, "CurrentWord",{ bg = "NONE", bold = true, fg = "NONE" })
vim.api.nvim_set_hl(0, "CurrentWordTwins",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "Cursor",{ bg = "NONE", fg = "NONE", reverse = true })
vim.api.nvim_set_hl(0, "CursorColumn",{ bg = "#2e383c", fg = "NONE" })
vim.api.nvim_set_hl(0, "CursorIM",{ link = "Cursor" })
vim.api.nvim_set_hl(0, "CursorLine",{ bg = "#2e383c", fg = "NONE" })
vim.api.nvim_set_hl(0, "CursorLineNr",{ bg = "NONE", fg = "#859289" })
vim.api.nvim_set_hl(0, "CursorWord0",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "CursorWord1",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "DapUIBreakpointsCurrentLine",{ bg = "NONE", bold = true, fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "DapUIBreakpointsInfo",{ link = "Green" })
vim.api.nvim_set_hl(0, "DapUIBreakpointsPath",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUIDecoration",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUIFloatBorder",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUILineNumber",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUIModifiedValue",{ bg = "NONE", bold = true, fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "DapUIScope",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUISource",{ link = "Purple" })
vim.api.nvim_set_hl(0, "DapUIStoppedThread",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DapUIThread",{ link = "Green" })
vim.api.nvim_set_hl(0, "DapUIType",{ link = "Purple" })
vim.api.nvim_set_hl(0, "DapUIWatchesEmpty",{ link = "Red" })
vim.api.nvim_set_hl(0, "DapUIWatchesError",{ link = "Red" })
vim.api.nvim_set_hl(0, "DapUIWatchesValue",{ link = "Green" })
vim.api.nvim_set_hl(0, "Debug",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "Define",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "DefinitionCount",{ link = "Grey" })
vim.api.nvim_set_hl(0, "DefinitionIcon",{ link = "Blue" })
vim.api.nvim_set_hl(0, "DefinitionPreviewTitle",{ bg = "NONE", bold = true, fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "Delimiter",{ bg = "NONE", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "DiagnosticError",{ link = "Error" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError",{ link = "ErrorFloat" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint",{ link = "HintFloat" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo",{ link = "InfoFloat" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn",{ link = "WarningFloat" })
vim.api.nvim_set_hl(0, "DiagnosticHint",{ link = "Hint" })
vim.api.nvim_set_hl(0, "DiagnosticInfo",{ link = "InfoText" })
vim.api.nvim_set_hl(0, "DiagnosticInformation",{ link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "DiagnosticSignError",{ link = "RedSign" })
vim.api.nvim_set_hl(0, "DiagnosticSignHint",{ link = "GreenSign" })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo",{ link = "BlueSign" })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn",{ link = "YellowSign" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError",{ link = "ErrorText" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint",{ link = "HintText" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo",{ link = "InfoText" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn",{ link = "WarningText" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError",{ link = "VirtualTextError" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint",{ link = "VirtualTextHint" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo",{ link = "VirtualTextInfo" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn",{ link = "VirtualTextWarning" })
vim.api.nvim_set_hl(0, "DiagnosticWarn",{ link = "WarningText" })
vim.api.nvim_set_hl(0, "DiagnosticWarning",{ link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "DiffAdd",{ bg = "#3c4841", fg = "NONE" })
vim.api.nvim_set_hl(0, "DiffChange",{ bg = "#384b55", fg = "NONE" })
vim.api.nvim_set_hl(0, "DiffDelete",{ bg = "#493b40", fg = "NONE" })
vim.api.nvim_set_hl(0, "DiffText",{ bg = "#7fbbb3", fg = "#272e33" })
vim.api.nvim_set_hl(0, "Directory",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "EndOfBuffer",{ bg = "#272e33", fg = "#495156" })
vim.api.nvim_set_hl(0, "Error",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "ErrorFloat",{ bg = "#374145", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "ErrorMsg",{ bg = "NONE", bold = true, fg = "#e67e80", underline = true })
vim.api.nvim_set_hl(0, "ErrorText",{ bg = "NONE", fg = "NONE", sp = "#e67e80", undercurl = true })
vim.api.nvim_set_hl(0, "Exception",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "FSPrefix",{ bg = "#272e33", bold = true, fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "FSSuffix",{ bg = "NONE", fg = "#859289" })
vim.api.nvim_set_hl(0, "Fg",{ bg = "NONE", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "Float",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "FloatBorder",{ bg = "#374145", fg = "#859289" })
vim.api.nvim_set_hl(0, "FloatermBorder",{ link = "Grey" })
vim.api.nvim_set_hl(0, "FocusedSymbol",{ link = "NormalFloat" })
vim.api.nvim_set_hl(0, "FoldColumn",{ bg = "NONE", fg = "#4f5b58" })
vim.api.nvim_set_hl(0, "Folded",{ bg = "#2e383c", fg = "#859289" })
vim.api.nvim_set_hl(0, "Function",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "GitGutterAdd",{ link = "GreenSign" })
vim.api.nvim_set_hl(0, "GitGutterAddLine",{ link = "DiffAdd" })
vim.api.nvim_set_hl(0, "GitGutterAddLineNr",{ link = "Green" })
vim.api.nvim_set_hl(0, "GitGutterChange",{ link = "BlueSign" })
vim.api.nvim_set_hl(0, "GitGutterChangeDelete",{ link = "PurpleSign" })
vim.api.nvim_set_hl(0, "GitGutterChangeDeleteLine",{ link = "DiffChange" })
vim.api.nvim_set_hl(0, "GitGutterChangeDeleteLineNr",{ link = "Purple" })
vim.api.nvim_set_hl(0, "GitGutterChangeLine",{ link = "DiffChange" })
vim.api.nvim_set_hl(0, "GitGutterChangeLineNr",{ link = "Blue" })
vim.api.nvim_set_hl(0, "GitGutterDelete",{ link = "RedSign" })
vim.api.nvim_set_hl(0, "GitGutterDeleteLine",{ link = "DiffDelete" })
vim.api.nvim_set_hl(0, "GitGutterDeleteLineNr",{ link = "Red" })
vim.api.nvim_set_hl(0, "GitSignsAdd",{ link = "GreenSign" })
vim.api.nvim_set_hl(0, "GitSignsAddLn",{ link = "DiffAdd" })
vim.api.nvim_set_hl(0, "GitSignsAddNr",{ link = "Green" })
vim.api.nvim_set_hl(0, "GitSignsChange",{ link = "BlueSign" })
vim.api.nvim_set_hl(0, "GitSignsChangeLn",{ link = "DiffChange" })
vim.api.nvim_set_hl(0, "GitSignsChangeNr",{ link = "Blue" })
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame",{ link = "Grey" })
vim.api.nvim_set_hl(0, "GitSignsDelete",{ link = "RedSign" })
vim.api.nvim_set_hl(0, "GitSignsDeleteLn",{ link = "DiffDelete" })
vim.api.nvim_set_hl(0, "GitSignsDeleteNr",{ link = "Red" })
vim.api.nvim_set_hl(0, "GlyphPalette1",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "GlyphPalette2",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "GlyphPalette3",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "GlyphPalette4",{ bg = "NONE", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "GlyphPalette6",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "GlyphPalette7",{ bg = "NONE", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "GlyphPalette9",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "Green",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "GreenItalic",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "GreenSign",{ bg = "#2e383c", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "Grey",{ bg = "NONE", fg = "#859289" })
vim.api.nvim_set_hl(0, "HighlightedyankRegion",{ link = "Visual" })
vim.api.nvim_set_hl(0, "HintFloat",{ bg = "#374145", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "HintText",{ bg = "NONE", fg = "NONE", sp = "#a7c080", undercurl = true })
vim.api.nvim_set_hl(0, "Identifier",{ bg = "NONE", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "Ignore",{ bg = "NONE", fg = "#859289" })
vim.api.nvim_set_hl(0, "IncSearch",{ bg = "#e67e80", fg = "#272e33" })
vim.api.nvim_set_hl(0, "InclineNormalNC",{ bg = "#374145", fg = "#859289" })
vim.api.nvim_set_hl(0, "Include",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "IndentBlanklineChar",{ bg = "NONE", fg = "#4f5b58", nocombine = true })
vim.api.nvim_set_hl(0, "IndentBlanklineContextChar",{ bg = "NONE", fg = "#859289", nocombine = true })
vim.api.nvim_set_hl(0, "IndentBlanklineSpaceChar",{ link = "IndentBlanklineChar" })
vim.api.nvim_set_hl(0, "IndentBlanklineSpaceCharBlankline",{ link = "IndentBlanklineChar" })
vim.api.nvim_set_hl(0, "InfoFloat",{ bg = "#374145", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "InfoText",{ bg = "NONE", fg = "NONE", sp = "#7fbbb3", undercurl = true })
vim.api.nvim_set_hl(0, "Keyword",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "Label",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "LineDiagTuncateLine",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "LineNr",{ bg = "NONE", fg = "#4f5b58" })
vim.api.nvim_set_hl(0, "LspCodeLens",{ link = "VirtualTextInfo" })
vim.api.nvim_set_hl(0, "LspCodeLensSeparator",{ link = "VirtualTextHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultError",{ link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultHint",{ link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultInformation",{ link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultWarning",{ link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingError",{ link = "DiagnosticFloatingError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingHint",{ link = "DiagnosticFloatingHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingInformation",{ link = "DiagnosticFloatingInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingWarning",{ link = "DiagnosticFloatingWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignError",{ link = "DiagnosticSignError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignHint",{ link = "DiagnosticSignHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignInformation",{ link = "DiagnosticSignInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignWarning",{ link = "DiagnosticSignWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineError",{ link = "DiagnosticUnderlineError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineHint",{ link = "DiagnosticUnderlineHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineInformation",{ link = "DiagnosticUnderlineInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineWarning",{ link = "DiagnosticUnderlineWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextError",{ link = "DiagnosticVirtualTextError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextHint",{ link = "DiagnosticVirtualTextHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextInformation",{ link = "DiagnosticVirtualTextInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextWarning",{ link = "DiagnosticVirtualTextWarn" })
vim.api.nvim_set_hl(0, "LspErrorHighlight",{ link = "ErrorText" })
vim.api.nvim_set_hl(0, "LspErrorVirtual",{ link = "VirtualTextError" })
vim.api.nvim_set_hl(0, "LspFloatWinBorder",{ bg = "#272e33", fg = "#272e33" })
vim.api.nvim_set_hl(0, "LspHintHighlight",{ link = "HintText" })
vim.api.nvim_set_hl(0, "LspHintVirtual",{ link = "VirtualTextHint" })
vim.api.nvim_set_hl(0, "LspInformationHighlight",{ link = "InfoText" })
vim.api.nvim_set_hl(0, "LspInformationVirtual",{ link = "VirtualTextInfo" })
vim.api.nvim_set_hl(0, "LspLinesDiagBorder",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "LspReferenceRead",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "LspReferenceText",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "LspReferenceWrite",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "LspSagaAutoPreview",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaCodeActionBorder",{ link = "Purple" })
vim.api.nvim_set_hl(0, "LspSagaCodeActionContent",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaCodeActionTitle",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "LspSagaCodeActionTruncateLine",{ link = "Purple" })
vim.api.nvim_set_hl(0, "LspSagaDefPreviewBorder",{ link = "Blue" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticBorder",{ link = "Orange" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticError",{ link = "Red" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticHeader",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticHint",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticInfo",{ link = "Blue" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticSource",{ link = "Orange" })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticWarn",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "LspSagaDocTruncateLine",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaErrorTrunCateLine",{ link = "LspSagaDiagnosticError" })
vim.api.nvim_set_hl(0, "LspSagaFinderSelection",{ link = "Fg" })
vim.api.nvim_set_hl(0, "LspSagaHintTrunCateLine",{ link = "LspSagaDiagnosticHint" })
vim.api.nvim_set_hl(0, "LspSagaHoverBorder",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaInfoTrunCateLine",{ link = "LspSagaDiagnosticInfo" })
vim.api.nvim_set_hl(0, "LspSagaRenameBorder",{ link = "Purple" })
vim.api.nvim_set_hl(0, "LspSagaRenamePromptPrefix",{ link = "Blue" })
vim.api.nvim_set_hl(0, "LspSagaShTruncateLine",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaSignatureHelpBorder",{ link = "Green" })
vim.api.nvim_set_hl(0, "LspSagaWarnTrunCateLine",{ link = "LspSagaDiagnosticWarn" })
vim.api.nvim_set_hl(0, "LspSemanticClass",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticComment",{ link = "TSComment" })
vim.api.nvim_set_hl(0, "LspSemanticEnum",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticEnumMember",{ link = "TSVariableBuiltin" })
vim.api.nvim_set_hl(0, "LspSemanticEvents",{ link = "TSLabel" })
vim.api.nvim_set_hl(0, "LspSemanticFunction",{ link = "TSFunction" })
vim.api.nvim_set_hl(0, "LspSemanticInterface",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticKeyword",{ link = "TSKeyword" })
vim.api.nvim_set_hl(0, "LspSemanticMethod",{ link = "TSMethod" })
vim.api.nvim_set_hl(0, "LspSemanticModifier",{ link = "TSOperator" })
vim.api.nvim_set_hl(0, "LspSemanticNumber",{ link = "TSNumber" })
vim.api.nvim_set_hl(0, "LspSemanticOperator",{ link = "TSOperator" })
vim.api.nvim_set_hl(0, "LspSemanticParameter",{ link = "TSParameter" })
vim.api.nvim_set_hl(0, "LspSemanticProperty",{ link = "TSProperty" })
vim.api.nvim_set_hl(0, "LspSemanticRegexp",{ link = "TSStringRegex" })
vim.api.nvim_set_hl(0, "LspSemanticString",{ link = "TSString" })
vim.api.nvim_set_hl(0, "LspSemanticStruct",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticType",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticTypeParameter",{ link = "TSType" })
vim.api.nvim_set_hl(0, "LspSemanticVariable",{ link = "TSVariable" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter",{ link = "Search" })
vim.api.nvim_set_hl(0, "LspWarningHighlight",{ link = "WarningText" })
vim.api.nvim_set_hl(0, "LspWarningVirtual",{ link = "VirtualTextWarning" })
vim.api.nvim_set_hl(0, "Macro",{ bg = "NONE", fg = "#83c092" })
vim.api.nvim_set_hl(0, "MatchParen",{ bg = "#495156", fg = "NONE" })
vim.api.nvim_set_hl(0, "MatchParenCur",{ bg = "NONE", bold = true, fg = "NONE" })
vim.api.nvim_set_hl(0, "MatchWord",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "MatchWordCur",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "ModeMsg",{ bg = "NONE", bold = true, fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "MoreMsg",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "NonText",{ bg = "NONE", fg = "#495156" })
vim.api.nvim_set_hl(0, "Normal",{ bg = "#272e33", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "NormalFloat",{ bg = "#374145", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "NormalNC",{ bg = "#2e383c", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "Number",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "Operator",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "Orange",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "OrangeItalic",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "OrangeSign",{ bg = "#2e383c", fg = "#e69875" })
vim.api.nvim_set_hl(0, "Pmenu",{ bg = "#374145", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "PmenuSbar",{ bg = "#374145", fg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuSel",{ bg = "#a7c080", fg = "#272e33" })
vim.api.nvim_set_hl(0, "PmenuThumb",{ bg = "#7a8478", fg = "NONE" })
vim.api.nvim_set_hl(0, "PreCondit",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "PreProc",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "Purple",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "PurpleItalic",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "PurpleSign",{ bg = "#2e383c", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "Question",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "QuickFixLine",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "Red",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "RedItalic",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "RedSign",{ bg = "#2e383c", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "ReferencesCount",{ link = "Grey" })
vim.api.nvim_set_hl(0, "Repeat",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "Search",{ bg = "#a7c080", fg = "#272e33" })
vim.api.nvim_set_hl(0, "SignColumn",{ bg = "NONE", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "SignatureMarkText",{ link = "BlueSign" })
vim.api.nvim_set_hl(0, "SignatureMarkerText",{ link = "PurpleSign" })
vim.api.nvim_set_hl(0, "Special",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "SpecialChar",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "SpecialComment",{ bg = "NONE", fg = "#859289", italic = true })
vim.api.nvim_set_hl(0, "SpecialKey",{ bg = "NONE", fg = "#414b50" })
vim.api.nvim_set_hl(0, "SpellBad",{ bg = "NONE", fg = "NONE", sp = "#e67e80", undercurl = true })
vim.api.nvim_set_hl(0, "SpellCap",{ bg = "NONE", fg = "NONE", sp = "#7fbbb3", undercurl = true })
vim.api.nvim_set_hl(0, "SpellLocal",{ bg = "NONE", fg = "NONE", sp = "#83c092", undercurl = true })
vim.api.nvim_set_hl(0, "SpellRare",{ bg = "NONE", fg = "NONE", sp = "#d699b6", undercurl = true })
vim.api.nvim_set_hl(0, "Statement",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "StatusLine",{ bg = "#374145", fg = "#859289" })
vim.api.nvim_set_hl(0, "StatusLineNC",{ bg = "#2e383c", fg = "#859289" })
vim.api.nvim_set_hl(0, "StatusLineTerm",{ bg = "#2e383c", fg = "#859289" })
vim.api.nvim_set_hl(0, "StatusLineTermNC",{ bg = "#272e33", fg = "#859289" })
vim.api.nvim_set_hl(0, "StorageClass",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "String",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "Structure",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "Substitute",{ bg = "#dbbc7f", fg = "#272e33" })
vim.api.nvim_set_hl(0, "TSAnnotation",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSAttribute",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSBoolean",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSCharacter",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "TSCharacterSpecial",{ link = "SpecialChar" })
vim.api.nvim_set_hl(0, "TSComment",{ link = "Comment" })
vim.api.nvim_set_hl(0, "TSConditional",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSConstBuiltin",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "TSConstMacro",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "TSConstant",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSConstructor",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSDanger",{ bg = "#e67e80", bold = true, fg = "#272e33" })
vim.api.nvim_set_hl(0, "TSDebug",{ link = "Debug" })
vim.api.nvim_set_hl(0, "TSDefine",{ link = "Define" })
vim.api.nvim_set_hl(0, "TSEmphasis",{ bg = "NONE", fg = "NONE", italic = true })
vim.api.nvim_set_hl(0, "TSEnvironment",{ link = "Macro" })
vim.api.nvim_set_hl(0, "TSEnvironmentName",{ link = "Type" })
vim.api.nvim_set_hl(0, "TSError",{ link = "Error" })
vim.api.nvim_set_hl(0, "TSException",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSField",{ link = "Blue" })
vim.api.nvim_set_hl(0, "TSFloat",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSFuncBuiltin",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSFuncMacro",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSFunction",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSFunctionCall",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSInclude",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSKeyword",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSKeywordFunction",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSKeywordOperator",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSKeywordReturn",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSLabel",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSLiteral",{ link = "String" })
vim.api.nvim_set_hl(0, "TSMath",{ link = "Blue" })
vim.api.nvim_set_hl(0, "TSMethod",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSMethodCall",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSNamespace",{ link = "YellowItalic" })
vim.api.nvim_set_hl(0, "TSNone",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSNote",{ bg = "#7fbbb3", bold = true, fg = "#272e33" })
vim.api.nvim_set_hl(0, "TSNumber",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSOperator",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSParameter",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSParameterReference",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSPreProc",{ link = "PreProc" })
vim.api.nvim_set_hl(0, "TSProperty",{ link = "Blue" })
vim.api.nvim_set_hl(0, "TSPunctBracket",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSPunctDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TSPunctSpecial",{ link = "Blue" })
vim.api.nvim_set_hl(0, "TSRainbowBlue",{ link = "rainbowcol6" })
vim.api.nvim_set_hl(0, "TSRainbowCyan",{ link = "rainbowcol5" })
vim.api.nvim_set_hl(0, "TSRainbowGreen",{ link = "rainbowcol4" })
vim.api.nvim_set_hl(0, "TSRainbowOrange",{ link = "rainbowcol2" })
vim.api.nvim_set_hl(0, "TSRainbowRed",{ link = "rainbowcol1" })
vim.api.nvim_set_hl(0, "TSRainbowViolet",{ link = "rainbowcol7" })
vim.api.nvim_set_hl(0, "TSRainbowYellow",{ link = "rainbowcol3" })
vim.api.nvim_set_hl(0, "TSRepeat",{ link = "Red" })
vim.api.nvim_set_hl(0, "TSStorageClass",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSStorageClassLifetime",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSStrike",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TSString",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "TSStringEscape",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSStringRegex",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSStringSpecial",{ link = "SpecialChar" })
vim.api.nvim_set_hl(0, "TSStrong",{ bg = "NONE", bold = true, fg = "NONE" })
vim.api.nvim_set_hl(0, "TSSymbol",{ link = "Purple" })
vim.api.nvim_set_hl(0, "TSTag",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSTagAttribute",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSTagDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSText",{ link = "Green" })
vim.api.nvim_set_hl(0, "TSTextReference",{ link = "Constant" })
vim.api.nvim_set_hl(0, "TSTitle",{ link = "Title" })
vim.api.nvim_set_hl(0, "TSTodo",{ link = "Todo" })
vim.api.nvim_set_hl(0, "TSType",{ link = "YellowItalic" })
vim.api.nvim_set_hl(0, "TSTypeBuiltin",{ link = "YellowItalic" })
vim.api.nvim_set_hl(0, "TSTypeDefinition",{ link = "YellowItalic" })
vim.api.nvim_set_hl(0, "TSTypeQualifier",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TSURI",{ link = "markdownUrl" })
vim.api.nvim_set_hl(0, "TSUnderline",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "TSVariable",{ link = "Fg" })
vim.api.nvim_set_hl(0, "TSVariableBuiltin",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "TSWarning",{ bg = "#dbbc7f", bold = true, fg = "#272e33" })
vim.api.nvim_set_hl(0, "TabLine",{ bg = "#414b50", fg = "#9da9a0" })
vim.api.nvim_set_hl(0, "TabLineFill",{ bg = "#2e383c", fg = "#859289" })
vim.api.nvim_set_hl(0, "TabLineSel",{ bg = "#a7c080", fg = "#272e33" })
vim.api.nvim_set_hl(0, "Tag",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "TagbarFoldIcon",{ link = "Green" })
vim.api.nvim_set_hl(0, "TagbarKind",{ link = "Red" })
vim.api.nvim_set_hl(0, "TagbarNestedKind",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "TagbarScope",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TagbarSignature",{ link = "Green" })
vim.api.nvim_set_hl(0, "TagbarVisibilityPrivate",{ link = "Red" })
vim.api.nvim_set_hl(0, "TagbarVisibilityPublic",{ link = "Blue" })
vim.api.nvim_set_hl(0, "TargetFileName",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TelescopeBorder",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TelescopeMatching",{ bg = "NONE", bold = true, fg = "#a7c080" })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix",{ link = "Orange" })
vim.api.nvim_set_hl(0, "TelescopeSelection",{ link = "DiffAdd" })
vim.api.nvim_set_hl(0, "TermCursor",{ link = "Cursor" })
vim.api.nvim_set_hl(0, "Terminal",{ bg = "#272e33", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "Title",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "Todo",{ bg = "NONE", fg = "#d699b6", italic = true })
vim.api.nvim_set_hl(0, "ToolbarButton",{ bg = "#a7c080", fg = "#272e33" })
vim.api.nvim_set_hl(0, "ToolbarLine",{ bg = "#374145", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "TroubleCode",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TroubleSource",{ link = "Grey" })
vim.api.nvim_set_hl(0, "TroubleText",{ link = "Fg" })
vim.api.nvim_set_hl(0, "Type",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "Typedef",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "Underlined",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "UndotreeBranch",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "UndotreeCurrent",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "UndotreeHead",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "UndotreeNext",{ link = "Blue" })
vim.api.nvim_set_hl(0, "UndotreeNode",{ link = "Orange" })
vim.api.nvim_set_hl(0, "UndotreeNodeCurrent",{ link = "Red" })
vim.api.nvim_set_hl(0, "UndotreeSavedBig",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "UndotreeSavedSmall",{ link = "Purple" })
vim.api.nvim_set_hl(0, "UndotreeSeq",{ link = "Green" })
vim.api.nvim_set_hl(0, "UndotreeTimeStamp",{ link = "Grey" })
vim.api.nvim_set_hl(0, "VertSplit",{ bg = "NONE", fg = "#495156" })
vim.api.nvim_set_hl(0, "VirtualTextError",{ link = "Red" })
vim.api.nvim_set_hl(0, "VirtualTextHint",{ link = "Green" })
vim.api.nvim_set_hl(0, "VirtualTextInfo",{ link = "Blue" })
vim.api.nvim_set_hl(0, "VirtualTextWarning",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "Visual",{ bg = "#4c3743", fg = "NONE" })
vim.api.nvim_set_hl(0, "VisualNOS",{ bg = "#4c3743", fg = "NONE" })
vim.api.nvim_set_hl(0, "WarningFloat",{ bg = "#374145", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "WarningMsg",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "WarningText",{ bg = "NONE", fg = "NONE", sp = "#dbbc7f", undercurl = true })
vim.api.nvim_set_hl(0, "WhichKey",{ link = "Red" })
vim.api.nvim_set_hl(0, "WhichKeyDesc",{ link = "Blue" })
vim.api.nvim_set_hl(0, "WhichKeyFloat",{ bg = "#2e383c", fg = "NONE" })
vim.api.nvim_set_hl(0, "WhichKeyGroup",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "WhichKeySeparator",{ link = "Green" })
vim.api.nvim_set_hl(0, "WhichKeyValue",{ bg = "NONE", fg = "#d3c6aa" })
vim.api.nvim_set_hl(0, "Whitespace",{ bg = "NONE", fg = "#495156" })
vim.api.nvim_set_hl(0, "WildMenu",{ link = "PmenuSel" })
vim.api.nvim_set_hl(0, "WinBarNC",{ link = "Grey" })
vim.api.nvim_set_hl(0, "WinSeparator",{ link = "VertSplit" })
vim.api.nvim_set_hl(0, "Yellow",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "YellowItalic",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "YellowSign",{ bg = "#2e383c", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "bashStatement",{ link = "Orange" })
vim.api.nvim_set_hl(0, "cssAttr",{ link = "Orange" })
vim.api.nvim_set_hl(0, "cssAttrComma",{ link = "Fg" })
vim.api.nvim_set_hl(0, "cssAttributeSelector",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "cssBraces",{ link = "Fg" })
vim.api.nvim_set_hl(0, "cssClassName",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "cssClassNameDot",{ link = "Red" })
vim.api.nvim_set_hl(0, "cssColor",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssCommonAttr",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "cssFunctionName",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "cssImportant",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "cssNoise",{ link = "Grey" })
vim.api.nvim_set_hl(0, "cssProp",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "cssPseudoClass",{ link = "Purple" })
vim.api.nvim_set_hl(0, "cssPseudoClassFn",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssPseudoClassId",{ link = "Blue" })
vim.api.nvim_set_hl(0, "cssSelectorOp",{ link = "Orange" })
vim.api.nvim_set_hl(0, "cssSelectorOp2",{ link = "Orange" })
vim.api.nvim_set_hl(0, "cssTagName",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "cssUnitDecorators",{ link = "Orange" })
vim.api.nvim_set_hl(0, "cssValueAngle",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssValueFrequency",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssValueInteger",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssValueLength",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssValueNumber",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssValueTime",{ link = "Green" })
vim.api.nvim_set_hl(0, "cssVendor",{ link = "Grey" })
vim.api.nvim_set_hl(0, "debugBreakpoint",{ bg = "#e67e80", fg = "#272e33" })
vim.api.nvim_set_hl(0, "debugPC",{ bg = "#a7c080", fg = "#272e33" })
vim.api.nvim_set_hl(0, "diffAdded",{ link = "Green" })
vim.api.nvim_set_hl(0, "diffChanged",{ link = "Blue" })
vim.api.nvim_set_hl(0, "diffFile",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "diffIndexLine",{ link = "Purple" })
vim.api.nvim_set_hl(0, "diffLine",{ link = "Grey" })
vim.api.nvim_set_hl(0, "diffNewFile",{ link = "Orange" })
vim.api.nvim_set_hl(0, "diffOldFile",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "diffRemoved",{ link = "Red" })
vim.api.nvim_set_hl(0, "elixirBlockDefinition",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirCallbackDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirDelegateDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirExUnitMacro",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirExceptionDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirGuard",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirImplDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirInterpolation",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "elixirInterpolationDelimiter",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "elixirKeyword",{ link = "Orange" })
vim.api.nvim_set_hl(0, "elixirMacroDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirModuleDefine",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "elixirOverridableDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirPrivateDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirPrivateGuard",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirPrivateMacroDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirPrivateRecordDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirProtocolDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirPseudoVariable",{ link = "Purple" })
vim.api.nvim_set_hl(0, "elixirRecordDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "elixirSelf",{ link = "Purple" })
vim.api.nvim_set_hl(0, "elixirStringDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "elixirStructDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "gitcommitArrow",{ link = "Grey" })
vim.api.nvim_set_hl(0, "gitcommitDiscarded",{ link = "Grey" })
vim.api.nvim_set_hl(0, "gitcommitFile",{ link = "Green" })
vim.api.nvim_set_hl(0, "gitcommitOnBranch",{ link = "Grey" })
vim.api.nvim_set_hl(0, "gitcommitSelected",{ link = "Grey" })
vim.api.nvim_set_hl(0, "gitcommitSummary",{ link = "Green" })
vim.api.nvim_set_hl(0, "gitcommitUnmerged",{ link = "Grey" })
vim.api.nvim_set_hl(0, "gitcommitUntracked",{ link = "Grey" })
vim.api.nvim_set_hl(0, "goBuiltins",{ link = "Function" })
vim.api.nvim_set_hl(0, "goComplexes",{ link = "goType" })
vim.api.nvim_set_hl(0, "goConst",{ link = "goVar" })
vim.api.nvim_set_hl(0, "goDeclType",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "goFloats",{ link = "goType" })
vim.api.nvim_set_hl(0, "goFunctionCall",{ link = "Function" })
vim.api.nvim_set_hl(0, "goImport",{ link = "Include" })
vim.api.nvim_set_hl(0, "goPackage",{ link = "Define" })
vim.api.nvim_set_hl(0, "goPredefinedIdentifiers",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "goSignedInts",{ link = "goType" })
vim.api.nvim_set_hl(0, "goTSConstBuiltin",{ link = "AquaItalic" })
vim.api.nvim_set_hl(0, "goTSInclude",{ link = "Purple" })
vim.api.nvim_set_hl(0, "goTSNamespace",{ link = "Fg" })
vim.api.nvim_set_hl(0, "goTSProperty",{ link = "Identifier" })
vim.api.nvim_set_hl(0, "goType",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "goUnsignedInts",{ link = "goType" })
vim.api.nvim_set_hl(0, "goVar",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "goVarArgs",{ link = "Grey" })
vim.api.nvim_set_hl(0, "goVarDefs",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "healthError",{ link = "Red" })
vim.api.nvim_set_hl(0, "healthSuccess",{ link = "Green" })
vim.api.nvim_set_hl(0, "healthWarning",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "helpCommand",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "helpExample",{ link = "Green" })
vim.api.nvim_set_hl(0, "helpHeader",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "helpHeadline",{ bg = "NONE", bold = true, fg = "#e67e80" })
vim.api.nvim_set_hl(0, "helpHyperTextEntry",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "helpHyperTextJump",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "helpNote",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "helpSectionDelim",{ link = "Grey" })
vim.api.nvim_set_hl(0, "helpSpecial",{ link = "Blue" })
vim.api.nvim_set_hl(0, "helpURL",{ bg = "NONE", fg = "#a7c080", underline = true })
vim.api.nvim_set_hl(0, "htmlArg",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "htmlBold",{ bg = "NONE", bold = true, fg = "NONE" })
vim.api.nvim_set_hl(0, "htmlBoldItalic",{ bg = "NONE", bold = true, fg = "NONE", italic = true })
vim.api.nvim_set_hl(0, "htmlBoldUnderline",{ bg = "NONE", bold = true, fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "htmlBoldUnderlineItalic",{ bg = "NONE", bold = true, fg = "NONE", italic = true, underline = true })
vim.api.nvim_set_hl(0, "htmlEndTag",{ link = "Blue" })
vim.api.nvim_set_hl(0, "htmlH1",{ bg = "NONE", bold = true, fg = "#e67e80" })
vim.api.nvim_set_hl(0, "htmlH2",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "htmlH3",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "htmlH4",{ bg = "NONE", bold = true, fg = "#a7c080" })
vim.api.nvim_set_hl(0, "htmlH5",{ bg = "NONE", bold = true, fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "htmlH6",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "htmlItalic",{ bg = "NONE", fg = "NONE", italic = true })
vim.api.nvim_set_hl(0, "htmlLink",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "htmlScriptTag",{ link = "Purple" })
vim.api.nvim_set_hl(0, "htmlSpecialTagName",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "htmlTag",{ link = "Green" })
vim.api.nvim_set_hl(0, "htmlTagN",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "htmlTagName",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "htmlUnderline",{ bg = "NONE", fg = "NONE", underline = true })
vim.api.nvim_set_hl(0, "htmlUnderlineItalic",{ bg = "NONE", fg = "NONE", italic = true, underline = true })
vim.api.nvim_set_hl(0, "illuminatedWord",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "javaAnnotation",{ link = "Blue" })
vim.api.nvim_set_hl(0, "javaClassDecl",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "javaMethodDecl",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "javaParen",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaParen1",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaParen2",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaParen3",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaParen4",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaParen5",{ link = "Fg" })
vim.api.nvim_set_hl(0, "javaScriptFunction",{ link = "Keyword" })
vim.api.nvim_set_hl(0, "javaScriptGlobal",{ link = "Purple" })
vim.api.nvim_set_hl(0, "javaScriptIdentifier",{ link = "Orange" })
vim.api.nvim_set_hl(0, "javaScriptMember",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "javaScriptMessage",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "javaScriptNull",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "javaScriptNumber",{ link = "Number" })
vim.api.nvim_set_hl(0, "javaScriptOperator",{ link = "Orange" })
vim.api.nvim_set_hl(0, "javaTypedef",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "javaUserLabel",{ link = "Purple" })
vim.api.nvim_set_hl(0, "javaVarArg",{ link = "Green" })
vim.api.nvim_set_hl(0, "javascriptTSConstructor",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "javascriptTSInclude",{ link = "Purple" })
vim.api.nvim_set_hl(0, "jsonKeyword",{ link = "Green" })
vim.api.nvim_set_hl(0, "jsonQuote",{ link = "Grey" })
vim.api.nvim_set_hl(0, "jsonString",{ link = "Fg" })
vim.api.nvim_set_hl(0, "jsonTSLabel",{ link = "jsonKeyword" })
vim.api.nvim_set_hl(0, "jsonTSString",{ link = "jsonString" })
vim.api.nvim_set_hl(0, "jsonTSStringEscape",{ link = "SpecialChar" })
vim.api.nvim_set_hl(0, "lCursor",{ link = "Cursor" })
vim.api.nvim_set_hl(0, "lessAmpersandChar",{ link = "Orange" })
vim.api.nvim_set_hl(0, "lessClass",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "lessFunction",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "lessMixinChar",{ link = "Grey" })
vim.api.nvim_set_hl(0, "lessVariable",{ link = "Blue" })
vim.api.nvim_set_hl(0, "lspInlayHintsParameter",{ link = "LineNr" })
vim.api.nvim_set_hl(0, "lspInlayHintsType",{ link = "LineNr" })
vim.api.nvim_set_hl(0, "lspReference",{ link = "CurrentWord" })
vim.api.nvim_set_hl(0, "luaFunc",{ link = "Green" })
vim.api.nvim_set_hl(0, "luaFunction",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "luaIn",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "luaTSConstructor",{ link = "TSPunctBracket" })
vim.api.nvim_set_hl(0, "luaTSField",{ link = "Fg" })
vim.api.nvim_set_hl(0, "luaTable",{ link = "Fg" })
vim.api.nvim_set_hl(0, "makeCommands",{ link = "Orange" })
vim.api.nvim_set_hl(0, "makeIdent",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "makeSpecTarget",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "makeTarget",{ link = "Blue" })
vim.api.nvim_set_hl(0, "markdownBlockquote",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownBold",{ bg = "NONE", bold = true, fg = "NONE" })
vim.api.nvim_set_hl(0, "markdownBoldDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownCode",{ link = "Green" })
vim.api.nvim_set_hl(0, "markdownCodeBlock",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "markdownCodeDelimiter",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "markdownH1",{ bg = "NONE", bold = true, fg = "#e67e80" })
vim.api.nvim_set_hl(0, "markdownH2",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "markdownH3",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "markdownH4",{ bg = "NONE", bold = true, fg = "#a7c080" })
vim.api.nvim_set_hl(0, "markdownH5",{ bg = "NONE", bold = true, fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "markdownH6",{ bg = "NONE", bold = true, fg = "#d699b6" })
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownHeadingRule",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownId",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "markdownIdDeclaration",{ link = "markdownLinkText" })
vim.api.nvim_set_hl(0, "markdownItalic",{ bg = "NONE", fg = "NONE", italic = true })
vim.api.nvim_set_hl(0, "markdownItalicDelimiter",{ bg = "NONE", fg = "#859289", italic = true })
vim.api.nvim_set_hl(0, "markdownLinkDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownLinkText",{ link = "Purple" })
vim.api.nvim_set_hl(0, "markdownLinkTextDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownListMarker",{ link = "Red" })
vim.api.nvim_set_hl(0, "markdownOrderedListMarker",{ link = "Red" })
vim.api.nvim_set_hl(0, "markdownRule",{ link = "Purple" })
vim.api.nvim_set_hl(0, "markdownUrl",{ bg = "NONE", fg = "#7fbbb3", underline = true })
vim.api.nvim_set_hl(0, "markdownUrlDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "markdownUrlTitleDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "netrwClassify",{ link = "Green" })
vim.api.nvim_set_hl(0, "netrwCmdSep",{ link = "Grey" })
vim.api.nvim_set_hl(0, "netrwComment",{ link = "Grey" })
vim.api.nvim_set_hl(0, "netrwDir",{ link = "Green" })
vim.api.nvim_set_hl(0, "netrwExe",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "netrwHelpCmd",{ link = "Blue" })
vim.api.nvim_set_hl(0, "netrwLink",{ link = "Grey" })
vim.api.nvim_set_hl(0, "netrwList",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "netrwSymLink",{ link = "Fg" })
vim.api.nvim_set_hl(0, "netrwVersion",{ link = "Orange" })
vim.api.nvim_set_hl(0, "packerFail",{ link = "Red" })
vim.api.nvim_set_hl(0, "packerHash",{ link = "Green" })
vim.api.nvim_set_hl(0, "packerOutput",{ link = "Orange" })
vim.api.nvim_set_hl(0, "packerPackageName",{ link = "Green" })
vim.api.nvim_set_hl(0, "packerPackageNotLoaded",{ link = "Grey" })
vim.api.nvim_set_hl(0, "packerRelDate",{ link = "Grey" })
vim.api.nvim_set_hl(0, "packerStatusFail",{ link = "Fg" })
vim.api.nvim_set_hl(0, "packerStatusSuccess",{ link = "Fg" })
vim.api.nvim_set_hl(0, "packerString",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "packerSuccess",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "packerTimeHigh",{ link = "Red" })
vim.api.nvim_set_hl(0, "packerTimeLow",{ link = "Green" })
vim.api.nvim_set_hl(0, "packerTimeMedium",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "packerTimeTrivial",{ link = "Blue" })
vim.api.nvim_set_hl(0, "packerWorking",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "phpComparison",{ link = "Orange" })
vim.api.nvim_set_hl(0, "phpDefine",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "phpInterpSimpleCurly",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "phpMemberSelector",{ link = "Green" })
vim.api.nvim_set_hl(0, "phpMethodsVar",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "phpSpecialFunction",{ link = "Green" })
vim.api.nvim_set_hl(0, "phpStructure",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "phpVarSelector",{ link = "Blue" })
vim.api.nvim_set_hl(0, "plug1",{ bg = "NONE", bold = true, fg = "#e69875" })
vim.api.nvim_set_hl(0, "plug2",{ link = "Green" })
vim.api.nvim_set_hl(0, "plugBracket",{ link = "Grey" })
vim.api.nvim_set_hl(0, "plugDash",{ link = "Orange" })
vim.api.nvim_set_hl(0, "plugDeleted",{ link = "Grey" })
vim.api.nvim_set_hl(0, "plugEdge",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "plugError",{ link = "Red" })
vim.api.nvim_set_hl(0, "plugH2",{ link = "Orange" })
vim.api.nvim_set_hl(0, "plugMessage",{ link = "Orange" })
vim.api.nvim_set_hl(0, "plugName",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "plugNotLoaded",{ link = "Grey" })
vim.api.nvim_set_hl(0, "plugNumber",{ bg = "NONE", bold = true, fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "plugRelDate",{ link = "Grey" })
vim.api.nvim_set_hl(0, "plugSha",{ link = "Green" })
vim.api.nvim_set_hl(0, "plugStar",{ link = "Red" })
vim.api.nvim_set_hl(0, "plugUpdate",{ link = "Blue" })
vim.api.nvim_set_hl(0, "pythonBuiltin",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "pythonDecoratorName",{ link = "Blue" })
vim.api.nvim_set_hl(0, "pythonExceptions",{ link = "Purple" })
vim.api.nvim_set_hl(0, "rainbowcol1",{ bg = "NONE", fg = "#e67e80" })
vim.api.nvim_set_hl(0, "rainbowcol2",{ bg = "NONE", fg = "#e69875" })
vim.api.nvim_set_hl(0, "rainbowcol3",{ bg = "NONE", fg = "#dbbc7f" })
vim.api.nvim_set_hl(0, "rainbowcol4",{ bg = "NONE", fg = "#a7c080" })
vim.api.nvim_set_hl(0, "rainbowcol5",{ bg = "NONE", fg = "#83c092" })
vim.api.nvim_set_hl(0, "rainbowcol6",{ bg = "NONE", fg = "#7fbbb3" })
vim.api.nvim_set_hl(0, "rainbowcol7",{ bg = "NONE", fg = "#d699b6" })
vim.api.nvim_set_hl(0, "rubyAccess",{ link = "Orange" })
vim.api.nvim_set_hl(0, "rubyAttribute",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "rubyBlockParameterList",{ link = "Blue" })
vim.api.nvim_set_hl(0, "rubyDefine",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "rubyInterpolation",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "rubyInterpolationDelimiter",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "rubyKeywordAsMethod",{ link = "Green" })
vim.api.nvim_set_hl(0, "rubyMacro",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "rubyModuleName",{ link = "Purple" })
vim.api.nvim_set_hl(0, "rubyStringDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "rustAssert",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "rustDeriveTrait",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "rustEnumVariant",{ link = "Purple" })
vim.api.nvim_set_hl(0, "rustIdentifier",{ link = "Purple" })
vim.api.nvim_set_hl(0, "rustMacroVariable",{ link = "Blue" })
vim.api.nvim_set_hl(0, "rustModPath",{ link = "Orange" })
vim.api.nvim_set_hl(0, "rustModPathSep",{ link = "Grey" })
vim.api.nvim_set_hl(0, "rustPanic",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "rustPubScopeCrate",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "rustSelf",{ link = "Blue" })
vim.api.nvim_set_hl(0, "rustStructure",{ link = "Orange" })
vim.api.nvim_set_hl(0, "rustSuper",{ link = "Blue" })
vim.api.nvim_set_hl(0, "sassAmpersand",{ link = "Orange" })
vim.api.nvim_set_hl(0, "sassClass",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "sassClassChar",{ link = "Red" })
vim.api.nvim_set_hl(0, "sassControl",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "sassCssAttribute",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "sassFor",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "sassFunction",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "sassFunctionName",{ link = "Green" })
vim.api.nvim_set_hl(0, "sassInterpolationDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "sassMixinName",{ link = "Orange" })
vim.api.nvim_set_hl(0, "sassMixing",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "sassProperty",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "scssAttribute",{ link = "Orange" })
vim.api.nvim_set_hl(0, "scssBoolean",{ link = "Purple" })
vim.api.nvim_set_hl(0, "scssForKeyword",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "scssFunctionName",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "scssInterpolationDelimiter",{ link = "Green" })
vim.api.nvim_set_hl(0, "scssMixinName",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "scssNull",{ link = "Purple" })
vim.api.nvim_set_hl(0, "scssSelectorChar",{ link = "Red" })
vim.api.nvim_set_hl(0, "scssSelectorName",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "scssVariableAssignment",{ link = "Grey" })
vim.api.nvim_set_hl(0, "scssVariableValue",{ link = "Green" })
vim.api.nvim_set_hl(0, "shCmdSubRegion",{ link = "Green" })
vim.api.nvim_set_hl(0, "shCommandSub",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shFunctionKey",{ link = "RedItalic" })
vim.api.nvim_set_hl(0, "shFunctionOne",{ link = "Green" })
vim.api.nvim_set_hl(0, "shOperator",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shOption",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "shQuote",{ link = "Green" })
vim.api.nvim_set_hl(0, "shRange",{ link = "Fg" })
vim.api.nvim_set_hl(0, "shSet",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shSetList",{ link = "Blue" })
vim.api.nvim_set_hl(0, "shSnglCase",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shTestOpr",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shVarAssign",{ link = "Orange" })
vim.api.nvim_set_hl(0, "shVariable",{ link = "Blue" })
vim.api.nvim_set_hl(0, "tomlKey",{ link = "Green" })
vim.api.nvim_set_hl(0, "tomlString",{ link = "Fg" })
vim.api.nvim_set_hl(0, "tomlTSProperty",{ link = "tomlKey" })
vim.api.nvim_set_hl(0, "tomlTSString",{ link = "tomlString" })
vim.api.nvim_set_hl(0, "vimAutoCmdSfxList",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "vimContinue",{ link = "Grey" })
vim.api.nvim_set_hl(0, "vimFuncName",{ link = "Green" })
vim.api.nvim_set_hl(0, "vimFunction",{ link = "Green" })
vim.api.nvim_set_hl(0, "vimHiBang",{ link = "Orange" })
vim.api.nvim_set_hl(0, "vimIsCommand",{ link = "Fg" })
vim.api.nvim_set_hl(0, "vimLet",{ link = "Orange" })
vim.api.nvim_set_hl(0, "vimMap",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "vimMapLhs",{ link = "Green" })
vim.api.nvim_set_hl(0, "vimMapRhs",{ link = "Green" })
vim.api.nvim_set_hl(0, "vimNotation",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "vimOption",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "vimSet",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "vimSetEqual",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "vimSetSep",{ link = "Grey" })
vim.api.nvim_set_hl(0, "vimSynType",{ link = "Orange" })
vim.api.nvim_set_hl(0, "vimUserAttrb",{ link = "Green" })
vim.api.nvim_set_hl(0, "vimUserAttrbKey",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "vimUserFunc",{ link = "Green" })
vim.api.nvim_set_hl(0, "xmlAttrib",{ link = "Aqua" })
vim.api.nvim_set_hl(0, "xmlCdataCdata",{ link = "Purple" })
vim.api.nvim_set_hl(0, "xmlCdataStart",{ link = "Grey" })
vim.api.nvim_set_hl(0, "xmlDocTypeDecl",{ link = "Grey" })
vim.api.nvim_set_hl(0, "xmlDocTypeKeyword",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "xmlEndTag",{ link = "Blue" })
vim.api.nvim_set_hl(0, "xmlEntity",{ link = "Red" })
vim.api.nvim_set_hl(0, "xmlEntityPunct",{ link = "Red" })
vim.api.nvim_set_hl(0, "xmlEqual",{ link = "Orange" })
vim.api.nvim_set_hl(0, "xmlTag",{ link = "Green" })
vim.api.nvim_set_hl(0, "xmlTagName",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "yamlBlockMappingKey",{ link = "Green" })
vim.api.nvim_set_hl(0, "yamlConstant",{ link = "OrangeItalic" })
vim.api.nvim_set_hl(0, "yamlKeyValueDelimiter",{ link = "Grey" })
vim.api.nvim_set_hl(0, "yamlString",{ link = "Fg" })
vim.api.nvim_set_hl(0, "yamlTSBoolean",{ link = "yamlConstant" })
vim.api.nvim_set_hl(0, "yamlTSConstBuiltin",{ link = "yamlConstant" })
vim.api.nvim_set_hl(0, "yamlTSField",{ link = "yamlBlockMappingKey" })
vim.api.nvim_set_hl(0, "yamlTSString",{ link = "yamlString" })
vim.api.nvim_set_hl(0, "yamlTSStringEscape",{ link = "SpecialChar" })
vim.api.nvim_set_hl(0, "zshDeref",{ link = "Blue" })
vim.api.nvim_set_hl(0, "zshFunction",{ link = "Green" })
vim.api.nvim_set_hl(0, "zshOptStart",{ link = "PurpleItalic" })
vim.api.nvim_set_hl(0, "zshOption",{ link = "Blue" })
vim.api.nvim_set_hl(0, "zshSubst",{ link = "Yellow" })
vim.api.nvim_set_hl(0, "zshTypes",{ link = "Orange" })
vim.api.nvim_set_hl(0, "zshVariableDef",{ link = "Blue" })
