local gruber_darker_fg        = "#e4e4e4"
local gruber_darker_fg__1     = "#f4f4ff"
local gruber_darker_fg__2     = "#f5f5f5"
local gruber_darker_white     = "#ffffff"
local gruber_darker_black     = "#000000"
local gruber_darker_bg_1      = "#101010"
local gruber_darker_bg        = "#181818"
local gruber_darker_bg__1     = "#282828"
local gruber_darker_bg__2     = "#453d41"
local gruber_darker_bg__3     = "#484848"
local gruber_darker_bg__4     = "#52494e"
local gruber_darker_red_1     = "#c73c3f"
local gruber_darker_red       = "#f43841"
local gruber_darker_red__1    = "#ff4f58"
local gruber_darker_green     = "#73d936"
local gruber_darker_yellow    = "#ffdd33"
local gruber_darker_brown     = "#cc8c3c"
local gruber_darker_quartz    = "#95a99f"
local gruber_darker_niagara_2 = "#303540"
local gruber_darker_niagara_1 = "#565f73"
local gruber_darker_niagara   = "#96a6c8"
local gruber_darker_wisteria  = "#9e95c7"



vim.api.nvim_set_hl(0,"GruberDarkerYellowBold", {   bold = true,   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"GruberDarkerBg_1", {   fg = gruber_darker_bg_1 })
vim.api.nvim_set_hl(0,"GruberDarkerYellow", {   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"GruberDarkerFg2", {   fg = gruber_darker_fg__2 })
vim.api.nvim_set_hl(0,"GruberDarkerGreen", {   fg = gruber_darker_green })
vim.api.nvim_set_hl(0,"GruberDarkerFg1", {   fg = gruber_darker_fg__1 })
vim.api.nvim_set_hl(0,"GruberDarkerLightRedBold", {   bold = true,   fg = gruber_darker_red__1 })
vim.api.nvim_set_hl(0,"GruberDarkerFg0", {   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"GruberDarkerLightRed", {   fg = gruber_darker_red__1 })
vim.api.nvim_set_hl(0,"GruberDarkerRedBold", {   bold = true,   fg = gruber_darker_red })
vim.api.nvim_set_hl(0,"GruberDarkerWisteriaUnderline", {   sp = gruber_darker_wisteria,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerRed", {   fg = gruber_darker_red })
vim.api.nvim_set_hl(0,"GruberDarkerNiagaraUnderline", {   sp = gruber_darker_niagara,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerDarkRedBold", {   bold = true,   fg = gruber_darker_red_1 })
vim.api.nvim_set_hl(0,"GruberDarkerQuartzUnderline", {   sp = gruber_darker_quartz,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerDarkRed", {   fg = gruber_darker_red_1 })
vim.api.nvim_set_hl(0,"GruberDarkerYellowUnderline", {   sp = gruber_darker_yellow,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerRedUnderline", {   sp = gruber_darker_red,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerWisteriaSign", {   fg = gruber_darker_wisteria,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerNiagaraSign", {   fg = gruber_darker_niagara,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerQuartzSign", {   fg = gruber_darker_quartz,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerGreenSign", {   fg = gruber_darker_green,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerYellowSign", {   fg = gruber_darker_yellow,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerRedSign", {   fg = gruber_darker_red,   reverse = false })
vim.api.nvim_set_hl(0,"GruberDarkerWisteriaBold", {   bold = true,   fg = gruber_darker_wisteria })
vim.api.nvim_set_hl(0,"GruberDarkerWisteria", {   fg = gruber_darker_wisteria })
vim.api.nvim_set_hl(0,"GruberDarkerNiagaraBold", {   bold = true,   fg = gruber_darker_niagara })
vim.api.nvim_set_hl(0,"GruberDarkerNiagara", {   fg = gruber_darker_niagara })
vim.api.nvim_set_hl(0,"GruberDarkerDarkNiagaraBold", {   bold = true,   fg = gruber_darker_niagara_1 })
vim.api.nvim_set_hl(0,"GruberDarkerDarkNiagara", {   fg = gruber_darker_niagara_1 })
vim.api.nvim_set_hl(0,"GruberDarkerBg4", {   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"GruberDarkerGreenUnderline", {   sp = gruber_darker_green,   undercurl = true })
vim.api.nvim_set_hl(0,"GruberDarkerGreenBold", {   bold = true,   fg = gruber_darker_green })
vim.api.nvim_set_hl(0,"GruberDarkerBg3", {   fg = gruber_darker_bg__3 })
vim.api.nvim_set_hl(0,"GruberDarkerBg0", {   fg = gruber_darker_bg })
vim.api.nvim_set_hl(0,"GruberDarkerQuartzBold", {   bold = true,   fg = gruber_darker_quartz })
vim.api.nvim_set_hl(0,"GruberDarkerBg2", {   fg = gruber_darker_bg__2 })
vim.api.nvim_set_hl(0,"GruberDarkerQuartz", {   fg = gruber_darker_quartz })
vim.api.nvim_set_hl(0,"GruberDarkerDarkestNiagara", {   fg = gruber_darker_niagara_2 })
vim.api.nvim_set_hl(0,"GruberDarkerBrownBold", {   bold = true,   fg = gruber_darker_brown })
vim.api.nvim_set_hl(0,"GruberDarkerBg1", {   fg = gruber_darker_bg__1 })
vim.api.nvim_set_hl(0,"GruberDarkerBrown", {   fg = gruber_darker_brown })
vim.api.nvim_set_hl(0,"GruberDarkerDarkestNiagaraBold", {   bold = true,   fg = gruber_darker_niagara_2 })
vim.api.nvim_set_hl(0,"DiagnosticError", {   link = "GruberDarkerRedBold" })
vim.api.nvim_set_hl(0,"SagaBorder", {   link = "FloatBorder" })
vim.api.nvim_set_hl(0,"DiagnosticSignInfo", {   link = "GruberDarkerGreenSign" })
vim.api.nvim_set_hl(0,"DiagnosticUnderlineHint", {   link = "GruberDarkerWisteriaUnderline" })
vim.api.nvim_set_hl(0,"DiagnosticInfo", {   link = "GruberDarkerGreenBold" })
vim.api.nvim_set_hl(0,"DiagnosticSignHint", {   link = "GruberDarkerWisteriaSign" })
vim.api.nvim_set_hl(0,"DiagnosticUnderlineWarn", {   link = "GruberDarkerYellowUnderline" })
vim.api.nvim_set_hl(0,"SagaNormal", {   link = "NormalFloat" })
vim.api.nvim_set_hl(0,"DiagnosticSignWarn", {   link = "GruberDarkerYellowSign" })
vim.api.nvim_set_hl(0,"DiagnosticUnnecessary", {   link = "DiagnosticUnderlineHint" })
vim.api.nvim_set_hl(0,"DiagnosticWarn", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"DiagnosticHint", {   link = "GruberDarkerWisteria" })
vim.api.nvim_set_hl(0,"DiagnosticUnderlineError", {   link = "GruberDarkerRedUnderline" })
vim.api.nvim_set_hl(0,"DiagnosticUnderlineInfo", {   link = "GruberDarkerGreenUnderline" })
vim.api.nvim_set_hl(0,"DiagnosticSignError", {   link = "GruberDarkerRedSign" })
vim.api.nvim_set_hl(0,"LineNr", {   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"Number", {   link = "GruberDarkerWisteria" })
vim.api.nvim_set_hl(0,"Type", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"FoldColumn", {   bg = gruber_darker_bg__2,   fg = gruber_darker_brown })
vim.api.nvim_set_hl(0,"Folded", {   bg = gruber_darker_bg__2,   fg = gruber_darker_brown,   italic = true })
vim.api.nvim_set_hl(0,"Cursor", {   bg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"WinSeparator", {   bold = true,   fg = gruber_darker_bg__2 })
vim.api.nvim_set_hl(0,"VertSplit", {   bg = gruber_darker_bg__1,   fg = gruber_darker_fg__2 })
vim.api.nvim_set_hl(0,"ErrorMsg", {   bg = gruber_darker_red,   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"TermCursor", {   bg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"Debug", {   link = "GruberDarkerFg2" })
vim.api.nvim_set_hl(0,"EndOfBuffer", {   bg = "NONE",   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"diffLine", {   link = "DiffChange" })
vim.api.nvim_set_hl(0,"diffRemoved", {   link = "DiffDelete" })
vim.api.nvim_set_hl(0,"diffAdded", {   link = "DiffAdd" })
vim.api.nvim_set_hl(0,"DiffText", {   bg = "NONE",   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"DiffDelete", {   bg = "NONE",   fg = gruber_darker_red__1 })
vim.api.nvim_set_hl(0,"DiffChange", {   bg = "NONE",   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"DiffAdd", {   bg = "NONE",   fg = gruber_darker_green })
vim.api.nvim_set_hl(0,"CursorColumn", {   bg = gruber_darker_bg__2 })
vim.api.nvim_set_hl(0,"CursorIM", {   bg = gruber_darker_yellow,   fg = "NONE" })
vim.api.nvim_set_hl(0,"lCursor", {   bg = gruber_darker_yellow,   fg = "NONE" })
vim.api.nvim_set_hl(0,"Macro", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"Keyword", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"Comment", {   fg = gruber_darker_brown,   italic = true })
vim.api.nvim_set_hl(0,"Operator", {   fg = gruber_darker_fg,   italic = false })
vim.api.nvim_set_hl(0,"markdownCodeBlock", {   fg = gruber_darker_green })
vim.api.nvim_set_hl(0,"Typedef", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"markdownCode", {   fg = gruber_darker_green })
vim.api.nvim_set_hl(0,"markdownHeadingDelimiter", {   bold = true,   fg = gruber_darker_niagara })
vim.api.nvim_set_hl(0,"Todo", {   bg = gruber_darker_yellow,   fg = gruber_darker_bg })
vim.api.nvim_set_hl(0,"Directory", {   link = "GruberDarkerNiagaraBold" })
vim.api.nvim_set_hl(0,"Underlined", {   fg = gruber_darker_wisteria,   underline = true })
vim.api.nvim_set_hl(0,"Delimiter", {   link = "GruberDarkerFg0" })
vim.api.nvim_set_hl(0,"Question", {   fg = gruber_darker_niagara })
vim.api.nvim_set_hl(0,"Special", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"Constant", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"Structure", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"StorageClass", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"PreCondit", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"Character", {   fg = gruber_darker_green,   italic = true })
vim.api.nvim_set_hl(0,"PreProc", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"Float", {   link = "GruberDarkerWisteria" })
vim.api.nvim_set_hl(0,"Normal", {   bg = gruber_darker_bg,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"Title", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"Repeat", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"Visual", {   bg = gruber_darker_bg__2,   reverse = false })
vim.api.nvim_set_hl(0,"markdownError", {   bg = gruber_darker_bg__1,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"WildMenu", {   bg = gruber_darker_yellow,   fg = gruber_darker_black })
vim.api.nvim_set_hl(0,"markdownCodeDelimiter", {   fg = gruber_darker_brown,   italic = true })
vim.api.nvim_set_hl(0,"WarningMsg", {   link = "GruberDarkerRed" })
vim.api.nvim_set_hl(0,"markdownBold", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"VisualNOS", {   link = "GruberDarkerRed" })
vim.api.nvim_set_hl(0,"Bold", {   bold = true })
vim.api.nvim_set_hl(0,"Italic", {   italic = true })
vim.api.nvim_set_hl(0,"TabLineSel", {   bg = "NONE",   bold = true,   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"Whitespace", {   bg = "NONE",   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"TabLineFill", {   bg = gruber_darker_bg__1,   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"markdownItalic", {   fg = gruber_darker_wisteria,   italic = true })
vim.api.nvim_set_hl(0,"TabLine", {   bg = "NONE" })
vim.api.nvim_set_hl(0,"SpecialComment", {   link = "GruberDarkerWisteriaBold" })
vim.api.nvim_set_hl(0,"StatusLineNC", {   bg = gruber_darker_bg__1,   fg = gruber_darker_quartz })
vim.api.nvim_set_hl(0,"Tag", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"StatusLine", {   bg = gruber_darker_bg__1,   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"SpecialChar", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"SpellRare", {   undercurl = true })
vim.api.nvim_set_hl(0,"Define", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"SpellLocal", {   undercurl = true })
vim.api.nvim_set_hl(0,"Include", {   link = "GruberDarkerQuartz" })
vim.api.nvim_set_hl(0,"SpellCap", {   undercurl = true })
vim.api.nvim_set_hl(0,"Exception", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"NormalFloat", {   bg = gruber_darker_bg,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"FloatBorder", {   bg = "NONE",   fg = gruber_darker_bg__4 })
vim.api.nvim_set_hl(0,"SpellBad", {   link = "GruberDarkerRedUnderline" })
vim.api.nvim_set_hl(0,"Conditional", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"SpecialKey", {   fg = gruber_darker_fg__2 })
vim.api.nvim_set_hl(0,"Statement", {   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"CurSearch", {   link = "IncSearch" })
vim.api.nvim_set_hl(0,"IncSearch", {   bg = gruber_darker_fg__2,   fg = gruber_darker_black })
vim.api.nvim_set_hl(0,"Function", {   link = "GruberDarkerNiagara" })
vim.api.nvim_set_hl(0,"QuickFixLine", {   bg = gruber_darker_bg__2,   bold = true })
vim.api.nvim_set_hl(0,"Identifier", {   link = "GruberDarkerFg1" })
vim.api.nvim_set_hl(0,"Boolean", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"PmenuThumb", {   bg = gruber_darker_bg })
vim.api.nvim_set_hl(0,"CursorLine", {   bg = gruber_darker_bg__1 })
vim.api.nvim_set_hl(0,"PmenuSbar", {   bg = gruber_darker_bg })
vim.api.nvim_set_hl(0,"PmenuSel", {   bg = gruber_darker_bg__2,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"Pmenu", {   bg = gruber_darker_bg__1,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"SignColumn", {   bg = "NONE",   fg = gruber_darker_bg__2 })
vim.api.nvim_set_hl(0,"NormalSB", {   bg = gruber_darker_bg_1,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"ColorColumn", {   bg = gruber_darker_bg__2 })
vim.api.nvim_set_hl(0,"NormalNC", {   bg = gruber_darker_bg,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"NonText", {   link = "EndOfBuffer" })
vim.api.nvim_set_hl(0,"Search", {   bg = gruber_darker_yellow,   fg = gruber_darker_black })
vim.api.nvim_set_hl(0,"MoreMsg", {   fg = gruber_darker_fg__2 })
vim.api.nvim_set_hl(0,"Conceal", {   bg = gruber_darker_bg,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"String", {   fg = gruber_darker_green,   italic = true })
vim.api.nvim_set_hl(0,"ModeMsg", {   link = "GruberDarkerFg2" })
vim.api.nvim_set_hl(0,"MatchParen", {   bg = gruber_darker_wisteria,   fg = gruber_darker_fg })
vim.api.nvim_set_hl(0,"Label", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"CursorLineNr", {   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"@preproc", {   link = "PreProc" })
vim.api.nvim_set_hl(0,"@float", {   link = "Float" })
vim.api.nvim_set_hl(0,"@conditional.ternary", {})
vim.api.nvim_set_hl(0,"@tag.delimiter", {   link = "Delimiter" })
vim.api.nvim_set_hl(0,"@tag.attribute", {   link = "@field" })
vim.api.nvim_set_hl(0,"@comment.luadoc", {   link = "@comment.documentation" })
vim.api.nvim_set_hl(0,"@tag", {   link = "Tag" })
vim.api.nvim_set_hl(0,"@comment.documentation", {   italic = true,   link = "GruberDarkerGreen" })
vim.api.nvim_set_hl(0,"@text.diff.change", {   link = "DiffChange" })
vim.api.nvim_set_hl(0,"@function.macro", {   link = "Macro" })
vim.api.nvim_set_hl(0,"@text.todo", {   link = "Todo" })
vim.api.nvim_set_hl(0,"@function.builtin", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"@debug", {   link = "Debug" })
vim.api.nvim_set_hl(0,"@text.uri", {   fg = gruber_darker_niagara,   underline = true })
vim.api.nvim_set_hl(0,"@none", {   bg = "NONE",   fg = "NONE" })
vim.api.nvim_set_hl(0,"@punctuation.delimiter", {   link = "Delimiter" })
vim.api.nvim_set_hl(0,"@text.warning", {   link = "WarningMsg" })
vim.api.nvim_set_hl(0,"@error", {})
vim.api.nvim_set_hl(0,"@text.underline", {   link = "Underlined" })
vim.api.nvim_set_hl(0,"@text.diff.delete", {   link = "DiffDelete" })
vim.api.nvim_set_hl(0,"@text.reference", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"@text.diff.add", {   link = "DiffAdd" })
vim.api.nvim_set_hl(0,"@text.literal", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@text.danger", {   link = "ErrorMsg" })
vim.api.nvim_set_hl(0,"@parameter", {   link = "Identifier" })
vim.api.nvim_set_hl(0,"@function", {   link = "Function" })
vim.api.nvim_set_hl(0,"@text", {   link = "Normal" })
vim.api.nvim_set_hl(0,"@text.note", {   link = "Comment" })
vim.api.nvim_set_hl(0,"@text.emphasis", {   link = "Italic" })
vim.api.nvim_set_hl(0,"@keyword", {   link = "Keyword" })
vim.api.nvim_set_hl(0,"@text.strong", {   link = "Bold" })
vim.api.nvim_set_hl(0,"@comment", {   link = "Comment" })
vim.api.nvim_set_hl(0,"@number", {   link = "Number" })
vim.api.nvim_set_hl(0,"@operator", {   link = "Operator" })
vim.api.nvim_set_hl(0,"@constructor", {   link = "Function" })
vim.api.nvim_set_hl(0,"@method", {   link = "Function" })
vim.api.nvim_set_hl(0,"@type", {   link = "Type" })
vim.api.nvim_set_hl(0,"@text.title", {   link = "Title" })
vim.api.nvim_set_hl(0,"@character.special", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@text.strike", {   strikethrough = true })
vim.api.nvim_set_hl(0,"@variable", {   link = "Identifier" })
vim.api.nvim_set_hl(0,"@string.special", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@type.definition", {   link = "Typedef" })
vim.api.nvim_set_hl(0,"@string.escape", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@property", {   link = "GruberDarkerDarkNiagara" })
vim.api.nvim_set_hl(0,"@string.regex", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@field", {   link = "GruberDarkerNiagara" })
vim.api.nvim_set_hl(0,"@string.documentation", {   link = "String" })
vim.api.nvim_set_hl(0,"@constant.macro", {   link = "Define" })
vim.api.nvim_set_hl(0,"@type.builtin", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"@constant.builtin", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"@conditional", {   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"@constant", {   link = "Constant" })
vim.api.nvim_set_hl(0,"@variable.builtin", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"@define", {   link = "Define" })
vim.api.nvim_set_hl(0,"@string", {   link = "String" })
vim.api.nvim_set_hl(0,"@boolean", {   link = "Boolean" })
vim.api.nvim_set_hl(0,"@storageclass", {   link = "StorageClass" })
vim.api.nvim_set_hl(0,"@punctuation.special", {   link = "GruberDarkerBrown" })
vim.api.nvim_set_hl(0,"@repeat", {   link = "Repeat" })
vim.api.nvim_set_hl(0,"@punctuation.bracket", {   link = "GruberDarkerWisteria" })
vim.api.nvim_set_hl(0,"@label", {   link = "Label" })
vim.api.nvim_set_hl(0,"@character", {   link = "Character" })
vim.api.nvim_set_hl(0,"CmpItemKindFunction", {   link = "Function" })
vim.api.nvim_set_hl(0,"CmpItemKindMethod", {   link = "Function" })
vim.api.nvim_set_hl(0,"CmpItemKindTypeParameter", {   link = "Identifier" })
vim.api.nvim_set_hl(0,"CmpItemKindText", {   fg = gruber_darker_fg__2 })
vim.api.nvim_set_hl(0,"CmpItemAbbrMatchFuzzy", {   link = "GruberDarkerBrownBold" })
vim.api.nvim_set_hl(0,"CmpItemAbbrMatch", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"CmpItemAbbr", {   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"CmpItemKindSnippet", {   link = "GruberDarkerDarkNiagara" })
vim.api.nvim_set_hl(0,"CmpItemAbbrDeprecated", {})
vim.api.nvim_set_hl(0,"CmpItemMenu", {   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"CmpItemKind", {   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"CmpItemKindEnum", {   link = "Type" })
vim.api.nvim_set_hl(0,"CmpItemKindOperator", {   link = "Operator" })
vim.api.nvim_set_hl(0,"CmpItemKindValue", {   link = "Type" })
vim.api.nvim_set_hl(0,"CmpItemKindEvent", {   fg = gruber_darker_brown })
vim.api.nvim_set_hl(0,"CmpItemKindUnit", {   link = "GruberDarkerDarkNiagara" })
vim.api.nvim_set_hl(0,"CmpItemKindStruct", {   link = "GruberDarkerNiagara" })
vim.api.nvim_set_hl(0,"CmpItemKindProperty", {   link = "GruberDarkerDarkNiagara" })
vim.api.nvim_set_hl(0,"CmpItemKindConstant", {   link = "Constant" })
vim.api.nvim_set_hl(0,"CmpItemKindModule", {   link = "Define" })
vim.api.nvim_set_hl(0,"CmpItemKindEnumMember", {   link = "Type" })
vim.api.nvim_set_hl(0,"CmpItemKindInterface", {   link = "Type" })
vim.api.nvim_set_hl(0,"CmpItemKindFolder", {   fg = gruber_darker_wisteria })
vim.api.nvim_set_hl(0,"CmpitemKindClass", {   link = "Type" })
vim.api.nvim_set_hl(0,"CmpItemKindReference", {   fg = gruber_darker_wisteria })
vim.api.nvim_set_hl(0,"CmpItemKindVariable", {   link = "Identifier" })
vim.api.nvim_set_hl(0,"CmpItemKindFile", {   fg = gruber_darker_wisteria })
vim.api.nvim_set_hl(0,"CmpItemKindField", {   link = "GruberDarkerNiagara" })
vim.api.nvim_set_hl(0,"CmpItemKindColor", {   fg = gruber_darker_yellow })
vim.api.nvim_set_hl(0,"CmpItemKindConstructor", {   link = "Function" })
vim.api.nvim_set_hl(0,"CmpItemKindKeyword", {   link = "Keyword" })
vim.api.nvim_set_hl(0,"TelescopeMultiSelection", {   link = "CursorLine" })
vim.api.nvim_set_hl(0,"TelescopeTitle", {   fg = gruber_darker_white })
vim.api.nvim_set_hl(0,"TelescopePromptPrefix", {   link = "GruberDarkerNiagara" })
vim.api.nvim_set_hl(0,"TelescopeBorder", {   link = "FloatBorder" })
vim.api.nvim_set_hl(0,"TelescopeMatching", {   link = "GruberDarkerYellowBold" })
vim.api.nvim_set_hl(0,"TelescopeSelectionCaret", {   link = "GruberDarkerYellow" })
vim.api.nvim_set_hl(0,"TelescopeNormal", {})
vim.api.nvim_set_hl(0,"TelescopeSelection", {   bg = gruber_darker_bg__1,   fg = gruber_darker_fg__2 })
