vim.api.nvim_set_hl(0, 'DiagnosticHint',{   fg = "#7B9695" })
vim.api.nvim_set_hl(0, '@label',{   fg = "#89B3B6" })
vim.api.nvim_set_hl(0, 'GitSignsCurrentLineBlame',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, 'ColorColumn',{   bg = "#34302C" })
vim.api.nvim_set_hl(0, 'CursorColumn',{link= 'ColorColumn'})
vim.api.nvim_set_hl(0, '@markup.heading',{link= 'Title'})
vim.api.nvim_set_hl(0, 'Todo',{   bold = true,   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, '@markup.raw',{link= '@string.special'})
vim.api.nvim_set_hl(0, 'SignColumn',{link= 'LineNr'})
vim.api.nvim_set_hl(0, 'LineNr',{   fg = "#867462" })
vim.api.nvim_set_hl(0, 'Whitespace',{   fg = "#867462" })
vim.api.nvim_set_hl(0, '@markup.math',{link= '@markup.raw'})
vim.api.nvim_set_hl(0, 'Visual',{   bg = "#403A36" })
vim.api.nvim_set_hl(0, 'DiagnosticError',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, 'NormalFloat',{   bg = "#34302C" })
vim.api.nvim_set_hl(0, 'DiffDelete',{   bg = "#7D2A2F",   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'DiffAdd',{   bg = "#233524" })
vim.api.nvim_set_hl(0, 'DiffText',{link= 'DiffAdd'})
vim.api.nvim_set_hl(0, '@markup.link',{   underline = true })
vim.api.nvim_set_hl(0, 'DiffChange',{   bg = "#422741" })
vim.api.nvim_set_hl(0, 'Delimiter',{   fg = "#8B7449" })
vim.api.nvim_set_hl(0, 'DiagnosticOk',{   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'DiagnosticWarn',{   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'Identifier',{   fg = "#ECE1D7" })
vim.api.nvim_set_hl(0, 'Boolean',{link= 'Number'})
vim.api.nvim_set_hl(0, 'Constant',{   fg = "#B380B0" })
vim.api.nvim_set_hl(0, 'Operator',{   fg = "#D47766" })
vim.api.nvim_set_hl(0, 'Function',{   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'Pmenu',{link= 'NormalFloat'})
vim.api.nvim_set_hl(0, 'GitSignsDelete',{link= 'MiniDiffSignDelete'})
vim.api.nvim_set_hl(0, 'GitSignsChange',{link= 'MiniDiffSignChange'})
vim.api.nvim_set_hl(0, 'GitSignsAdd',{link= 'MiniDiffSignAdd'})
vim.api.nvim_set_hl(0, 'Error',{   bg = "#7D2A2F" })
vim.api.nvim_set_hl(0, 'Question',{link= 'MoreMsg'})
vim.api.nvim_set_hl(0, '@lsp.typemod.comment.documentation',{link= '@comment.documentation'})
vim.api.nvim_set_hl(0, '@lsp.type.namespace',{link= 'Directory'})
vim.api.nvim_set_hl(0, '@lsp.type.enumMember',{link= 'Constant'})
vim.api.nvim_set_hl(0, 'DiagnosticDeprecated',{link= 'DiagnosticUnderlineError'})
vim.api.nvim_set_hl(0, '@tag.delimiter',{link= 'Delimiter'})
vim.api.nvim_set_hl(0, '@tag.attribute',{link= '@label'})
vim.api.nvim_set_hl(0, '@diff.delta',{link= 'DiffChange'})
vim.api.nvim_set_hl(0, '@diff.minus',{link= 'DiffDelete'})
vim.api.nvim_set_hl(0, '@diff.plus',{link= 'DiffAdd'})
vim.api.nvim_set_hl(0, '@markup.list',{link= 'Delimiter'})
vim.api.nvim_set_hl(0, '@markup.link.url',{link= '@string.special.url'})
vim.api.nvim_set_hl(0, '@markup.heading.6',{link= '@markup.heading.3'})
vim.api.nvim_set_hl(0, '@markup.heading.5',{link= '@markup.heading.2'})
vim.api.nvim_set_hl(0, '@comment.warning',{link= 'Todo'})
vim.api.nvim_set_hl(0, '@comment.todo',{link= 'Todo'})
vim.api.nvim_set_hl(0, '@comment.note',{link= 'Todo'})
vim.api.nvim_set_hl(0, '@comment.error',{link= 'Todo'})
vim.api.nvim_set_hl(0, '@keyword.directive',{link= 'PreProc'})
vim.api.nvim_set_hl(0, '@keyword.import',{link= 'PreProc'})
vim.api.nvim_set_hl(0, '@keyword.function',{link= 'PreProc'})
vim.api.nvim_set_hl(0, '@function.macro',{link= '@function'})
vim.api.nvim_set_hl(0, '@function.builtin',{link= '@function'})
vim.api.nvim_set_hl(0, 'markdownCode',{link= '@markup.raw'})
vim.api.nvim_set_hl(0, '@type.builtin',{link= '@type'})
vim.api.nvim_set_hl(0, 'markdownCodeBlock',{link= '@markup.raw.block'})
vim.api.nvim_set_hl(0, '@module.builtin',{link= '@module'})
vim.api.nvim_set_hl(0, '@module',{link= 'Identifier'})
vim.api.nvim_set_hl(0, '@constant.macro',{link= 'Constant'})
vim.api.nvim_set_hl(0, '@constant.builtin',{link= 'Constant'})
vim.api.nvim_set_hl(0, '@variable.builtin',{link= '@string.special.symbol'})
vim.api.nvim_set_hl(0, 'texOptSep',{link= '@punctuation.delimiter'})
vim.api.nvim_set_hl(0, 'DiffAdded',{link= 'DiffAdd'})
vim.api.nvim_set_hl(0, 'texOptEqual',{link= 'Operator'})
vim.api.nvim_set_hl(0, 'qfFileName',{link= 'Directory'})
vim.api.nvim_set_hl(0, 'SpecialKey',{link= 'Whitespace'})
vim.api.nvim_set_hl(0, 'texRefArg',{link= 'Constant'})
vim.api.nvim_set_hl(0, 'StatusLine',{link= 'NormalFloat'})
vim.api.nvim_set_hl(0, 'TabLine',{link= 'StatusLineNC'})
vim.api.nvim_set_hl(0, 'WildMenu',{link= 'NormalFloat'})
vim.api.nvim_set_hl(0, 'PmenuThumb',{link= 'PmenuSel'})
vim.api.nvim_set_hl(0, 'BlinkCmpLabelMatch',{   bold = true,   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'MiniTrailspace',{   link = "DiffRemoved" })
vim.api.nvim_set_hl(0, 'DiffRemoved',{link= 'DiffDelete'})
vim.api.nvim_set_hl(0, 'MiniTestPass',{   bold = true,   fg = "#233524" })
vim.api.nvim_set_hl(0, 'MiniTestFail',{   bold = true,   fg = "#7D2A2F" })
vim.api.nvim_set_hl(0, 'MiniTablineFill',{   link = "TabLineFill" })
vim.api.nvim_set_hl(0, 'TabLineFill',{link= 'StatusLine'})
vim.api.nvim_set_hl(0, 'MiniStatuslineModeVisual',{   bg = "#CF9BC2",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeOther',{   bg = "#78997A",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeCommand',{   bg = "#89B3B6",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeReplace',{   bg = "#D47766",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeInsert',{   bg = "#EBC06D",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineModeNormal',{   bg = "#C1A78E",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'MiniStatuslineFilename',{   bg = "#34302C",   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'MiniStatuslineDevinfo',{   bg = "#403A36",   fg = "#ECE1D7" })
vim.api.nvim_set_hl(0, 'MiniStarterQuery',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, 'MiniStarterSection',{   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'MiniStarterItemPrefix',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, 'MiniStarterFooter',{   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'MiniPickPrompt',{   bg = "#34302C",   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'MiniPickMatchCurrent',{   bg = "#403A36" })
vim.api.nvim_set_hl(0, 'MiniPickIconDirectory',{   fg = "#89B3B6" })
vim.api.nvim_set_hl(0, 'Normal',{   bg = "#292522",   fg = "#ECE1D7" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember',{link= '@field'})
vim.api.nvim_set_hl(0, 'MiniJump2dSpot',{   bold = true,   fg = "#B380B0",   nocombine = true })
vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol',{   fg = "#403A36",   nocombine = true })
vim.api.nvim_set_hl(0, 'MiniIconsYellow',{   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'MiniIconsRed',{   fg = "#D47766" })
vim.api.nvim_set_hl(0, 'Special',{   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'MiniIconsOrange',{   fg = "#8B7449" })
vim.api.nvim_set_hl(0, 'MiniIconsGrey',{   fg = "#ECE1D7" })
vim.api.nvim_set_hl(0, 'MiniIconsGreen',{   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'MiniIconsCyan',{   fg = "#7B9695" })
vim.api.nvim_set_hl(0, 'MiniIconsBlue',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, 'MiniIconsAzure',{   fg = "#A3A9CE" })
vim.api.nvim_set_hl(0, 'MiniFilesTitle',{   bg = "#34302C",   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'MiniDiffSignDelete',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, 'MiniDiffSignChange',{   fg = "#B380B0" })
vim.api.nvim_set_hl(0, 'MiniDiffSignAdd',{   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'MiniDepsChangeRemoved',{   link = "DiffDelete" })
vim.api.nvim_set_hl(0, 'MiniDepsChangeAdded',{   link = "DiffAdd" })
vim.api.nvim_set_hl(0, 'texTitleArg',{   bold = true })
vim.api.nvim_set_hl(0, 'netrwSymLink',{   fg = "#B380B0" })
vim.api.nvim_set_hl(0, 'netrwExe',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, '@lsp.typemod.variable.globalScope',{   italic = true })
vim.api.nvim_set_hl(0, '@lsp.type.parameter',{   bold = true,   fg = "#ECE1D7" })
vim.api.nvim_set_hl(0, '@lsp.type.macro',{})
vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary',{   sp = "#C1A78E",   undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk',{   sp = "#78997A",   undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint',{   sp = "#7B9695",   undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo',{   sp = "#7F91B2",   undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn',{   sp = "#EBC06D",   undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError',{   sp = "#BD8183",   undercurl = true })
vim.api.nvim_set_hl(0, '@markup.raw.block',{   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, '@markup.heading.3',{   bold = true,   fg = "#85B695" })
vim.api.nvim_set_hl(0, '@markup.heading.2',{   bold = true,   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, '@markup.underline',{   underline = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough',{   strikethrough = true })
vim.api.nvim_set_hl(0, '@markup.strong',{   bold = true })
vim.api.nvim_set_hl(0, '@markup.italic',{   italic = true })
vim.api.nvim_set_hl(0, '@comment.documentation',{   fg = "#C1A78E",   nocombine = true })
vim.api.nvim_set_hl(0, '@punctuation.delimiter',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, '@string.special.url',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, '@string.special.symbol',{   fg = "#ECE1D7",   italic = true })
vim.api.nvim_set_hl(0, '@string.special',{   fg = "#89B3B6" })
vim.api.nvim_set_hl(0, '@string.regexp',{   fg = "#A3A9CE" })
vim.api.nvim_set_hl(0, '@string.escape',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, '@string.documentation',{   fg = "#A3A9CE",   nocombine = true })
vim.api.nvim_set_hl(0, 'Ignore',{   fg = "#867462" })
vim.api.nvim_set_hl(0, 'Italic',{   italic = true })
vim.api.nvim_set_hl(0, 'MatchParen',{link= 'Substitute'})
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch',{   bold = true,   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'Underlined',{   underline = true })
vim.api.nvim_set_hl(0, 'PreProc',{   fg = "#85B695" })
vim.api.nvim_set_hl(0, 'Statement',{   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'Character',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, 'SpellRare',{   fg = "#EBC06D",   undercurl = true })
vim.api.nvim_set_hl(0, 'SpellLocal',{   fg = "#E49B5D",   undercurl = true })
vim.api.nvim_set_hl(0, 'SpellCap',{   fg = "#7F91B2",   undercurl = true })
vim.api.nvim_set_hl(0, 'ErrorMsg',{   bg = "#7D2A2F" })
vim.api.nvim_set_hl(0, 'SpellBad',{   fg = "#BD8183",   undercurl = true })
vim.api.nvim_set_hl(0, 'Comment',{   fg = "#C1A78E",   italic = true })
vim.api.nvim_set_hl(0, 'ModeMsg',{   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'Directory',{   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'Conceal',{   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'Substitute',{   bg = "#7D2A2F",   bold = true })
vim.api.nvim_set_hl(0, 'Search',{   bg = "#8B7449",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'CurSearch',{   bg = "#EBC06D",   bold = true,   fg = "#292522" })
vim.api.nvim_set_hl(0, 'TabLineSel',{   bg = "#34302C",   bold = true })
vim.api.nvim_set_hl(0, 'StatusLineNC',{   bg = "#34302C",   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'ComplMatchIns',{   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'PmenuMatchSel',{   reverse = true })
vim.api.nvim_set_hl(0, 'PmenuMatch',{   bold = true,   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'Folded',{   bg = "#253333",   fg = "#C1A78E" })
vim.api.nvim_set_hl(0, 'CursorLineNr',{   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'WinSeparator',{   fg = "#867462" })
vim.api.nvim_set_hl(0, 'FloatFooter',{   bg = "#34302C",   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'FloatTitle',{   bg = "#34302C",   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'String',{   fg = "#A3A9CE",   italic = true })
vim.api.nvim_set_hl(0, 'CmpItemKindValue',{link= '@constant'})
vim.api.nvim_set_hl(0, '@constant',{link= 'Identifier'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindTypeParameter',{link= '@type'})
vim.api.nvim_set_hl(0, 'MoreMsg',{   bold = true,   fg = "#78997A" })
vim.api.nvim_set_hl(0, 'MiniStatuslineFileinfo',{link= 'MiniStatuslineDevinfo'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindStruct',{link= '@type'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindConstant',{link= '@constant'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindEnumMember',{link= '@field'})
vim.api.nvim_set_hl(0, 'IblIndent',{link= 'MiniIndentscopeSymbol'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindFolder',{link= '@string.special.path'})
vim.api.nvim_set_hl(0, '@string.special.path',{link= 'Directory'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindReference',{link= '@type'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindFile',{link= '@string.special.path'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindColor',{link= '@constant'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindSnippet',{link= '@string.special'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindKeyword',{link= '@keyword'})
vim.api.nvim_set_hl(0, 'NonText',{link= 'Whitespace'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindEnum',{link= '@field'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindValue',{link= '@constant'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindUnit',{link= '@constant'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindProperty',{link= '@property'})
vim.api.nvim_set_hl(0, 'texMathDelimZone',{link= 'Statement'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindModule',{link= '@namespace'})
vim.api.nvim_set_hl(0, 'texMathZone',{link= '@markup.math'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindInterface',{link= '@type'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindClass',{link= '@type'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindVariable',{link= '@variable'})
vim.api.nvim_set_hl(0, '@variable',{link= 'Identifier'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindField',{link= '@field'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindConstructor',{link= '@constructor'})
vim.api.nvim_set_hl(0, '@constructor',{link= '@function'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindFunction',{link= '@function'})
vim.api.nvim_set_hl(0, 'texFileArg',{link= 'Constant'})
vim.api.nvim_set_hl(0, 'texItemLabelConcealed',{link= '@label'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindMethod',{link= '@method'})
vim.api.nvim_set_hl(0, 'PmenuSel',{   bg = "#403A36" })
vim.api.nvim_set_hl(0, 'texMathDelim',{link= 'Delimiter'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindText',{link= '@text'})
vim.api.nvim_set_hl(0, 'QuickFixLine',{link= 'PmenuMatch'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindEvent',{link= '@type'})
vim.api.nvim_set_hl(0, 'BlinkCmpKindOperator',{link= '@operator'})
vim.api.nvim_set_hl(0, 'CmpItemKindVariable',{link= '@variable'})
vim.api.nvim_set_hl(0, 'CmpItemKindUnit',{link= '@constant'})
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindText',{link= '@text'})
vim.api.nvim_set_hl(0, 'CmpItemKindStruct',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet',{link= '@string.special'})
vim.api.nvim_set_hl(0, 'CmpItemKindReference',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindProperty',{link= '@property'})
vim.api.nvim_set_hl(0, 'CmpItemKindOperator',{link= '@operator'})
vim.api.nvim_set_hl(0, 'CmpItemKindModule',{link= '@namespace'})
vim.api.nvim_set_hl(0, 'CmpItemKindMethod',{link= '@method'})
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword',{link= '@keyword'})
vim.api.nvim_set_hl(0, 'CmpItemKindInterface',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindFunction',{link= '@function'})
vim.api.nvim_set_hl(0, 'CmpItemKindFolder',{link= '@string.special.path'})
vim.api.nvim_set_hl(0, 'CmpItemKindFile',{link= '@string.special.path'})
vim.api.nvim_set_hl(0, 'CmpItemKindField',{link= '@field'})
vim.api.nvim_set_hl(0, 'CmpItemKindEvent',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindEnum',{link= '@type'})
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor',{link= '@constructor'})
vim.api.nvim_set_hl(0, 'CmpItemKindConstant',{link= '@constant'})
vim.api.nvim_set_hl(0, 'CmpItemKindColor',{link= '@constant'})
vim.api.nvim_set_hl(0, 'CmpItemKindClass',{link= '@type'})
vim.api.nvim_set_hl(0, 'WarningMsg',{   fg = "#BD8183" })
vim.api.nvim_set_hl(0, 'IblWhitespace',{link= 'IblIndent'})
vim.api.nvim_set_hl(0, 'NeoTreeFloatBorder',{link= 'Normal'})
vim.api.nvim_set_hl(0, 'NeoTreeNormal',{link= 'Pmenu'})
vim.api.nvim_set_hl(0, 'NeoTreeNormalNC',{link= 'NeoTreeNormal'})
vim.api.nvim_set_hl(0, 'NeoTreeCursorLine',{link= 'PmenuSel'})
vim.api.nvim_set_hl(0, 'NeoTreeWinSeparator',{   bg = "#292522",   fg = "#292522" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterRed',{   fg = "#D47766" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterYellow',{   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy',{   bold = true,   fg = "#EBC06D" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterGreen',{   fg = "#85B695" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterViolet',{   fg = "#B380B0" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterCyan',{   fg = "#89B3B6" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterOrange',{   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'RainbowDelimiterBlue',{   fg = "#A3A9CE" })
vim.api.nvim_set_hl(0, 'Type',{   fg = "#7B9695" })
vim.api.nvim_set_hl(0, 'Number',{   fg = "#CF9BC2" })
vim.api.nvim_set_hl(0, 'Bold',{   bold = true })
vim.api.nvim_set_hl(0, 'Title',{   bold = true,   fg = "#E49B5D" })
vim.api.nvim_set_hl(0, 'MiniJump2dSpotAhead',{   fg = "#7B9695",   nocombine = true })
vim.api.nvim_set_hl(0, 'MiniIconsPurple',{   fg = "#B380B0" })
vim.api.nvim_set_hl(0, 'MiniFilesCursorLine',{link= 'PmenuSel'})
vim.api.nvim_set_hl(0, 'texMathCmd',{link= 'Function'})
vim.api.nvim_set_hl(0, 'netrwClassify',{link= 'Delimiter'})
vim.api.nvim_set_hl(0, 'texMathSymbol',{link= 'Operator'})
vim.api.nvim_set_hl(0, 'LspReferenceText',{   bg = "#34302C",   underline = true })
vim.api.nvim_set_hl(0, 'netrwTreeBar',{link= 'Delimiter'})
vim.api.nvim_set_hl(0, 'texMathEnvArgName',{link= 'texEnvArgName'})
vim.api.nvim_set_hl(0, 'DiagnosticInfo',{   fg = "#7F91B2" })
vim.api.nvim_set_hl(0, 'CursorLine',{link= 'ColorColumn'})
vim.api.nvim_set_hl(0, '@markup.quote',{link= 'Comment'})
vim.api.nvim_set_hl(0, 'FoldColumn',{link= 'LineNr'})
