vim.api.nvim_set_hl(0,  "AlphaButtons" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "AlphaFooter" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "AlphaHeader" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "AlphaShortcut" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "Boolean" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "@boolean" , {   bg = "none",   fg = "none",   link = "Boolean",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferCurrent" , {   bg = "#26233a",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferCurrentIndex" , {   bg = "#26233a",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferCurrentMod" , {   bg = "#26233a",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferCurrentSign" , {   bg = "#26233a",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferCurrentTarget" , {   bg = "#26233a",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferInactive" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferInactiveIndex" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferInactiveMod" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferInactiveSign" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferInactiveTarget" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferTabpageFill" , {   bg = "#191724",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferVisible" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferVisibleIndex" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferVisibleMod" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferVisibleSign" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "BufferVisibleTarget" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "Character" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "@character" , {   bg = "none",   fg = "none",   link = "Character",   sp = "" } )
vim.api.nvim_set_hl(0,  "@character.special" , {   bg = "none",   fg = "none",   link = "@character",   sp = "" } )
vim.api.nvim_set_hl(0,  "@class" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemAbbr" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemAbbrDeprecated" , {   bg = "none",   fg = "#908caa",   sp = "",   strikethrough = true } )
vim.api.nvim_set_hl(0,  "CmpItemAbbrMatch" , {   bg = "none",   bold = true,   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemAbbrMatchFuzzy" , {   bg = "none",   bold = true,   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKind" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindClass" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindFunction" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindInterface" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindMethod" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindSnippet" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "CmpItemKindVariable" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "ColorColumn" , {   bg = "#26233a",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "Comment" , {   bg = "none",   fg = "#6e6a86",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "@comment" , {   bg = "none",   fg = "none",   link = "Comment",   sp = "" } )
vim.api.nvim_set_hl(0,  "Conceal" , {   bg = "none",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "Conditional" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@conditional" , {   bg = "none",   fg = "none",   link = "Conditional",   sp = "" } )
vim.api.nvim_set_hl(0,  "Constant" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "@constant" , {   bg = "none",   fg = "none",   link = "Constant",   sp = "" } )
vim.api.nvim_set_hl(0,  "@constant.builtin" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "@constant.macro" , {   bg = "none",   fg = "none",   link = "@constant",   sp = "" } )
vim.api.nvim_set_hl(0,  "@constructor" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "CurSearch" , {   bg = "none",   fg = "none",   link = "IncSearch",   sp = "" } )
vim.api.nvim_set_hl(0,  "Cursor" , {   bg = "#524f67",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "CursorColumn" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "CursorLine" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "CursorLineNr" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIBreakpointsCurrentLine" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIBreakpointsDisabledLine" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIBreakpointsInfo" , {   bg = "none",   fg = "none",   link = "DapUIThread",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIBreakpointsLine" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIBreakpointsPath" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIDecoration" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIFloatBorder" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIFrameName" , {   bg = "none",   fg = "none",   link = "Normal",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUILineNumber" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIModifiedValue" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIScope" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUISource" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIStoppedThread" , {   bg = "none",   fg = "none",   link = "DapUIBreakpointsPath",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIThread" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIValue" , {   bg = "none",   fg = "none",   link = "Normal",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIVariable" , {   bg = "none",   fg = "none",   link = "Normal",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIWatchesEmpty" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIWatchesError" , {   bg = "none",   fg = "none",   link = "DapUIWatchesEmpty",   sp = "" } )
vim.api.nvim_set_hl(0,  "DapUIWatchesValue" , {   bg = "none",   fg = "none",   link = "DapUIThread",   sp = "" } )
vim.api.nvim_set_hl(0,  "DarkenedPanel" , {   bg = "#1f1d2e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "DarkenedStatusline" , {   bg = "#1f1d2e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "DashboardCenter" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DashboardFooter" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DashboardHeader" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "DashboardShortcut" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "Debug" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "Define" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DefinitionCount" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "DefinitionIcon" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "DefintionPreviewTitle" , {   bg = "none",   bold = true,   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "Delimiter" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticDefaultError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticDefaultHint" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticDefaultInfo" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticDefaultWarn" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticFloatingError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticFloatingHint" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticFloatingInfo" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticFloatingWarn" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticHint" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticInfo" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticSignError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticSignHint" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticSignInfo" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticSignWarn" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticStatusLineError" , {   bg = "#1f1d2e",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticStatusLineHint" , {   bg = "#1f1d2e",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticStatusLineInfo" , {   bg = "#1f1d2e",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticStatusLineWarn" , {   bg = "#1f1d2e",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticUnderlineError" , {   bg = "none",   fg = "none",   sp = "#eb6f92",   undercurl = true } )
vim.api.nvim_set_hl(0,  "DiagnosticUnderlineHint" , {   bg = "none",   fg = "none",   sp = "#c4a7e7",   undercurl = true } )
vim.api.nvim_set_hl(0,  "DiagnosticUnderlineInfo" , {   bg = "none",   fg = "none",   sp = "#9ccfd8",   undercurl = true } )
vim.api.nvim_set_hl(0,  "DiagnosticUnderlineWarn" , {   bg = "none",   fg = "none",   sp = "#f6c177",   undercurl = true } )
vim.api.nvim_set_hl(0,  "DiagnosticVirtualTextError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticVirtualTextHint" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticVirtualTextInfo" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticVirtualTextWarn" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiagnosticWarn" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiffAdd" , {   bg = "#333C48",   blend = 20,   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "diffAdded" , {   bg = "none",   fg = "none",   link = "DiffAdd",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiffChange" , {   bg = "#26233a",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "diffChanged" , {   bg = "none",   fg = "none",   link = "DiffChange",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiffDelete" , {   bg = "#43293A",   blend = 20,   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "diffRemoved" , {   bg = "none",   fg = "none",   link = "DiffDelete",   sp = "" } )
vim.api.nvim_set_hl(0,  "DiffText" , {   bg = "#433842",   blend = 20,   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "Directory" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "Error" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "ErrorMsg" , {   bg = "none",   bold = true,   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "Exception" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@field" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "Float" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "FloatBorder" , {   bg = "#1f1d2e",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "FloatTitle" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "FoldColumn" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "Folded" , {   bg = "#1f1d2e",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "Function" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "@function" , {   bg = "none",   fg = "none",   link = "Function",   sp = "" } )
vim.api.nvim_set_hl(0,  "@function.builtin" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "@function.macro" , {   bg = "none",   fg = "none",   link = "@function",   sp = "" } )
vim.api.nvim_set_hl(0,  "GitSignsAdd" , {   bg = "#191724",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "GitSignsChange" , {   bg = "#191724",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "GitSignsDelete" , {   bg = "#191724",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "healthError" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "healthSuccess" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "healthWarning" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "HopNextKey1" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "HopNextKey2" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "HopNextKey" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "HopUnmatched" , {   bg = "none",   fg = "#524f67",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlArg" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlBold" , {   bg = "none",   bold = true,   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlEndTag" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlH1" , {   bg = "none",   bold = true,   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlH2" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlH3" , {   bg = "none",   bold = true,   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlH4" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlH5" , {   bg = "none",   bold = true,   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlItalic" , {   bg = "none",   fg = "none",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlLink" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlTag" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlTagName" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "htmlTagN" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "Identifier" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "Include" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@include" , {   bg = "none",   fg = "none",   link = "Include",   sp = "" } )
vim.api.nvim_set_hl(0,  "IncSearch" , {   bg = "#ebbcba",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "IndentBlanklineChar" , {   bg = "none",   fg = "#6e6a86",   nocombine = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "IndentBlanklineSpaceChar" , {   bg = "none",   fg = "#6e6a86",   nocombine = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "IndentBlanklineSpaceCharBlankline" , {   bg = "none",   fg = "#6e6a86",   nocombine = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "@interface" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "Keyword" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@keyword" , {   bg = "none",   fg = "none",   link = "Keyword",   sp = "" } )
vim.api.nvim_set_hl(0,  "@keyword.operator" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "Label" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "@label" , {   bg = "none",   fg = "none",   link = "Label",   sp = "" } )
vim.api.nvim_set_hl(0,  "LeapLabelPrimary" , {   bg = "none",   fg = "none",   link = "IncSearch",   sp = "" } )
vim.api.nvim_set_hl(0,  "LeapLabelSecondary" , {   bg = "#31748f",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "LeapMatch" , {   bg = "none",   fg = "none",   link = "MatchParen",   sp = "" } )
vim.api.nvim_set_hl(0,  "LineNr" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspCodeLens" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspCodeLensSeparator" , {   bg = "none",   fg = "#524f67",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspFloatWinBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspFloatWinNormal" , {   bg = "#1f1d2e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspReferenceRead" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspReferenceText" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspReferenceWrite" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaAutoPreview" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaCodeActionBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaCodeActionContent" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaCodeActionTitle" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaCodeActionTruncateLine" , {   bg = "none",   fg = "none",   link = "LspSagaCodeActionBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaDefPreviewBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaDiagnosticBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaDiagnosticHeader" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaDiagnosticTruncateLine" , {   bg = "none",   fg = "none",   link = "LspSagaDiagnosticBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaDocTruncateLine" , {   bg = "none",   fg = "none",   link = "LspSagaHoverBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaFinderSelection" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaHoverBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaLspFinderBorder" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaRenameBorder" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaRenamePromptPrefix" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaShTruncateLine" , {   bg = "none",   fg = "none",   link = "LspSagaSignatureHelpBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSagaSignatureHelpBorder" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "LspSignatureActiveParameter" , {   bg = "#26233a",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.comment" , {   bg = "none",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.enum" , {   bg = "none",   fg = "none",   link = "@type",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.interface" , {   bg = "none",   fg = "none",   link = "@interface",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.keyword" , {   bg = "none",   fg = "none",   link = "@keyword",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.typemod.function.defaultLibrary" , {   bg = "none",   fg = "none",   link = "Special",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.typemod.operator.injected" , {   bg = "none",   fg = "none",   link = "@operator",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.typemod.string.injected" , {   bg = "none",   fg = "none",   link = "@string",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.typemod.variable.defaultLibrary" , {   bg = "none",   fg = "none",   link = "@variable.builtin",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.typemod.variable.injected" , {   bg = "none",   fg = "none",   link = "@variable",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.namespace" , {   bg = "none",   fg = "none",   link = "@namespace",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.parameter" , {   bg = "none",   fg = "none",   link = "@parameter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.property" , {   bg = "none",   fg = "none",   link = "@property",   sp = "" } )
vim.api.nvim_set_hl(0,  "@lsp.type.variable" , {   bg = "none",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "Macro" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "@macro" , {   bg = "none",   fg = "none",   link = "Macro",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownDelimiter" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH1" , {   bg = "none",   bold = true,   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH1Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH1",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH2" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH2Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH2",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH3" , {   bg = "none",   bold = true,   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH3Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH3",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH4" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH4Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH4",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH5" , {   bg = "none",   bold = true,   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH5Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH5",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH6" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownH6Delimiter" , {   bg = "none",   fg = "none",   link = "markdownH6",   sp = "" } )
vim.api.nvim_set_hl(0,  "markdownLinkText" , {   bg = "none",   fg = "#c4a7e7",   sp = "#c4a7e7",   underline = true } )
vim.api.nvim_set_hl(0,  "markdownUrl" , {   bg = "none",   fg = "none",   link = "markdownLinkText",   sp = "" } )
vim.api.nvim_set_hl(0,  "MatchParen" , {   bg = "#403d52",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "@method" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "MiniIndentscopeSymbol" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "MiniIndentscopeSymbolOff" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdCode" , {   bg = "none",   fg = "#9ccfd8",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdCodeDelimiter" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdCodeEnd" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdCodeStart" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdFootnotes" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdID" , {   bg = "none",   fg = "#9ccfd8",   sp = "",   underline = true } )
vim.api.nvim_set_hl(0,  "mkdInlineURL" , {   bg = "none",   fg = "#c4a7e7",   sp = "",   underline = true } )
vim.api.nvim_set_hl(0,  "mkdLink" , {   bg = "none",   fg = "none",   link = "mkdInlineURL",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdLinkDef" , {   bg = "none",   fg = "none",   link = "mkdInlineURL",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdListItemLine" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdRule" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "mkdURL" , {   bg = "none",   fg = "none",   link = "mkdInlineURL",   sp = "" } )
vim.api.nvim_set_hl(0,  "ModeMsg" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "ModesCopy" , {   bg = "#f6c177",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "ModesDelete" , {   bg = "#eb6f92",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "ModesInsert" , {   bg = "#9ccfd8",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "ModesVisual" , {   bg = "#c4a7e7",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "MoreMsg" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "@namespace" , {   bg = "none",   fg = "none",   link = "@include",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsArray" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsBoolean" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsClass" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsConstant" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsConstructor" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsEnum" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsEnumMember" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsEvent" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsField" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsFile" , {   bg = "none",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsFunction" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsInterface" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsKey" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsKeyword" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsMethod" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsModule" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsNamespace" , {   bg = "none",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsNull" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsNumber" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsObject" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsOperator" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsPackage" , {   bg = "none",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsProperty" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsString" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsStruct" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsTypeParameter" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicIconsVariable" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicSeparator" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "NavicText" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeogitDiffAddHighlight" , {   bg = "#403d52",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeogitDiffContextHighlight" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeogitDiffDeleteHighlight" , {   bg = "#403d52",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeogitHunkHeader" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeogitHunkHeaderHighlight" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading1Prefix" , {   bg = "none",   bold = true,   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading1Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading1Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading2Prefix" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading2Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading2Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading3Prefix" , {   bg = "none",   bold = true,   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading3Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading3Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading4Prefix" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading4Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading4Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading5Prefix" , {   bg = "none",   bold = true,   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading5Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading5Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading6Prefix" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgHeading6Title" , {   bg = "none",   fg = "none",   link = "NeorgHeading6Prefix",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeorgMarkerTitle" , {   bg = "none",   bold = true,   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitAdded" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitConflict" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitDeleted" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitIgnored" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitModified" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitRenamed" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeGitUntracked" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NeoTreeTitleBar" , {   bg = "#31748f",   fg = "#1f1d2e",   sp = "" } )
vim.api.nvim_set_hl(0,  "NoiceCursor" , {   bg = "#e0def4",   fg = "#524f67",   sp = "" } )
vim.api.nvim_set_hl(0,  "NonText" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "Normal" , {   bg = "#191724",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NormalFloat" , {   bg = "#1f1d2e",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NormalNC" , {   bg = "#191724",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyDEBUGBorder" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyDEBUGIcon" , {   bg = "none",   fg = "none",   link = "NotifyDEBUGBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyDEBUGTitle" , {   bg = "none",   fg = "none",   link = "NotifyDEBUGBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyERRORBorder" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyERRORIcon" , {   bg = "none",   fg = "none",   link = "NotifyERRORBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyERRORTitle" , {   bg = "none",   fg = "none",   link = "NotifyERRORBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyINFOBorder" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyINFOIcon" , {   bg = "none",   fg = "none",   link = "NotifyINFOBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyINFOTitle" , {   bg = "none",   fg = "none",   link = "NotifyINFOBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyTRACEBorder" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyTRACEIcon" , {   bg = "none",   fg = "none",   link = "NotifyTRACEBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyTRACETitle" , {   bg = "none",   fg = "none",   link = "NotifyTRACEBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyWARNBorder" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyWARNIcon" , {   bg = "none",   fg = "none",   link = "NotifyWARNBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "NotifyWARNTitle" , {   bg = "none",   fg = "none",   link = "NotifyWARNBorder",   sp = "" } )
vim.api.nvim_set_hl(0,  "Number" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "@number" , {   bg = "none",   fg = "none",   link = "Number",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimInternalError" , {   bg = "#eb6f92",   fg = "#ffffff",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeEmptyFolderName" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileDeleted" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileDirty" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileMerge" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileNew" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileRenamed" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFileStaged" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFolderIcon" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeFolderName" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitDeleted" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitDirty" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitIgnored" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitMerge" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitNew" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitRenamed" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeGitStaged" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeImageFile" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeNormal" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeOpenedFile" , {   bg = "#403d52",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeOpenedFolderName" , {   bg = "none",   fg = "none",   link = "NvimTreeFolderName",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeRootFolder" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeSpecialFile" , {   bg = "none",   fg = "none",   link = "NvimTreeNormal",   sp = "" } )
vim.api.nvim_set_hl(0,  "NvimTreeWindowPicker" , {   bg = "#2E202F",   blend = 10,   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "Operator" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "@operator" , {   bg = "none",   fg = "none",   link = "Operator",   sp = "" } )
vim.api.nvim_set_hl(0,  "@parameter" , {   bg = "none",   fg = "#c4a7e7",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "Pmenu" , {   bg = "#1f1d2e",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "PmenuSbar" , {   bg = "#21202e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "PmenuSel" , {   bg = "#26233a",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "PmenuThumb" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "PounceAcceptBest" , {   bg = "#f6c177",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "PounceAccept" , {   bg = "#524f67",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "PounceGap" , {   bg = "none",   fg = "none",   link = "Search",   sp = "" } )
vim.api.nvim_set_hl(0,  "PounceMatch" , {   bg = "none",   fg = "none",   link = "Search",   sp = "" } )
vim.api.nvim_set_hl(0,  "PreCondit" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "PreProc" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "@preproc" , {   bg = "none",   fg = "none",   link = "PreProc",   sp = "" } )
vim.api.nvim_set_hl(0,  "@property" , {   bg = "none",   fg = "#9ccfd8",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "@punctuation" , {   bg = "none",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "@punctuation.bracket" , {   bg = "none",   fg = "none",   link = "@punctuation",   sp = "" } )
vim.api.nvim_set_hl(0,  "@punctuation.delimiter" , {   bg = "none",   fg = "none",   link = "@punctuation",   sp = "" } )
vim.api.nvim_set_hl(0,  "@punctuation.special" , {   bg = "none",   fg = "none",   link = "@punctuation",   sp = "" } )
vim.api.nvim_set_hl(0,  "Question" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "RedrawDebugClear" , {   bg = "#f6c177",   fg = "#ffffff",   sp = "" } )
vim.api.nvim_set_hl(0,  "RedrawDebugComposed" , {   bg = "#31748f",   fg = "#ffffff",   sp = "" } )
vim.api.nvim_set_hl(0,  "RedrawDebugRecompose" , {   bg = "#eb6f92",   fg = "#ffffff",   sp = "" } )
vim.api.nvim_set_hl(0,  "ReferencesCount" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "ReferencesIcon" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "@regexp" , {   bg = "none",   fg = "none",   link = "String",   sp = "" } )
vim.api.nvim_set_hl(0,  "Repeat" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@repeat" , {   bg = "none",   fg = "none",   link = "Repeat",   sp = "" } )
vim.api.nvim_set_hl(0,  "SagaShadow" , {   bg = "#26233a",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "Search" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "SignAdd" , {   bg = "none",   fg = "none",   link = "GitSignsAdd",   sp = "" } )
vim.api.nvim_set_hl(0,  "SignChange" , {   bg = "none",   fg = "none",   link = "GitSignsChange",   sp = "" } )
vim.api.nvim_set_hl(0,  "SignColumn" , {   bg = "#191724",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "SignDelete" , {   bg = "none",   fg = "none",   link = "GitSignsDelete",   sp = "" } )
vim.api.nvim_set_hl(0,  "Special" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "SpecialChar" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "SpecialComment" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "SpecialKey" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "SpellBad" , {   bg = "none",   fg = "none",   sp = "#908caa",   undercurl = true } )
vim.api.nvim_set_hl(0,  "SpellCap" , {   bg = "none",   fg = "none",   sp = "#908caa",   undercurl = true } )
vim.api.nvim_set_hl(0,  "SpellLocal" , {   bg = "none",   fg = "none",   sp = "#908caa",   undercurl = true } )
vim.api.nvim_set_hl(0,  "SpellRare" , {   bg = "none",   fg = "none",   sp = "#908caa",   undercurl = true } )
vim.api.nvim_set_hl(0,  "Statement" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "StatusLine" , {   bg = "#1f1d2e",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "StatusLineNC" , {   bg = "#191724",   fg = "#6e6a86",   sp = "" } )
vim.api.nvim_set_hl(0,  "StatusLineTerm" , {   bg = "none",   fg = "none",   link = "StatusLine",   sp = "" } )
vim.api.nvim_set_hl(0,  "StatusLineTermNC" , {   bg = "none",   fg = "none",   link = "StatusLineNC",   sp = "" } )
vim.api.nvim_set_hl(0,  "StorageClass" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "@storageclass" , {   bg = "none",   fg = "none",   link = "StorageClass",   sp = "" } )
vim.api.nvim_set_hl(0,  "String" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "@string" , {   bg = "none",   fg = "none",   link = "String",   sp = "" } )
vim.api.nvim_set_hl(0,  "@string.escape" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "@string.special" , {   bg = "none",   fg = "none",   link = "@string",   sp = "" } )
vim.api.nvim_set_hl(0,  "Structure" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "Substitute" , {   bg = "#eb6f92",   fg = "#191724",   sp = "" } )
vim.api.nvim_set_hl(0,  "@symbol" , {   bg = "none",   fg = "none",   link = "Identifier",   sp = "" } )
vim.api.nvim_set_hl(0,  "TabLine" , {   bg = "#1f1d2e",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "TabLineFill" , {   bg = "#1f1d2e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "TabLineSel" , {   bg = "#26233a",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "@tag.attribute" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "Tag" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "@tag" , {   bg = "none",   fg = "none",   link = "Tag",   sp = "" } )
vim.api.nvim_set_hl(0,  "@tag.delimiter" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "TargetWord" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeBorder" , {   bg = "#1f1d2e",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeMatching" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeNormal" , {   bg = "#1f1d2e",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopePromptNormal" , {   bg = "#1f1d2e",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopePromptPrefix" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeSelection" , {   bg = "#26233a",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeSelectionCaret" , {   bg = "#26233a",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "TelescopeTitle" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.danger" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.emphasis" , {   bg = "none",   fg = "none",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.environment" , {   bg = "none",   fg = "none",   link = "Macro",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.environment.name" , {   bg = "none",   fg = "none",   link = "Type",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.math" , {   bg = "none",   fg = "none",   link = "Special",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.note" , {   bg = "none",   fg = "none",   link = "SpecialComment",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.strike" , {   bg = "none",   fg = "none",   sp = "",   strikethrough = true } )
vim.api.nvim_set_hl(0,  "@text.strong" , {   bg = "none",   bold = true,   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.1.markdown" , {   bg = "none",   fg = "none",   link = "markdownH1",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.1.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH1Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.2.markdown" , {   bg = "none",   fg = "none",   link = "markdownH2",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.2.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH2Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.3.markdown" , {   bg = "none",   fg = "none",   link = "markdownH3",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.3.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH3Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.4.markdown" , {   bg = "none",   fg = "none",   link = "markdownH4",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.4.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH4Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.5.markdown" , {   bg = "none",   fg = "none",   link = "markdownH5",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.5.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH5Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.6.markdown" , {   bg = "none",   fg = "none",   link = "markdownH6",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title.6.marker.markdown" , {   bg = "none",   fg = "none",   link = "markdownH6Delimiter",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.title" , {   bg = "none",   fg = "none",   link = "Title",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.underline" , {   bg = "none",   fg = "none",   sp = "",   underline = true } )
vim.api.nvim_set_hl(0,  "@text.uri" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "@text.warning" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "Title" , {   bg = "none",   fg = "#e0def4",   sp = "" } )
vim.api.nvim_set_hl(0,  "Todo" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "@todo" , {   bg = "none",   fg = "none",   link = "Todo",   sp = "" } )
vim.api.nvim_set_hl(0,  "Type" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "@type" , {   bg = "none",   fg = "none",   link = "Type",   sp = "" } )
vim.api.nvim_set_hl(0,  "Typedef" , {   bg = "none",   fg = "none",   link = "Type",   sp = "" } )
vim.api.nvim_set_hl(0,  "Underlined" , {   bg = "none",   fg = "none",   sp = "",   underline = true } )
vim.api.nvim_set_hl(0,  "@variable" , {   bg = "none",   fg = "#e0def4",   italic = true,   sp = "" } )
vim.api.nvim_set_hl(0,  "@variable.builtin" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "VertSplit" , {   bg = "none",   fg = "#403d52",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader1" , {   bg = "none",   bold = true,   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader2" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader3" , {   bg = "none",   bold = true,   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader4" , {   bg = "none",   bold = true,   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader5" , {   bg = "none",   bold = true,   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeader6" , {   bg = "none",   bold = true,   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHeaderChar" , {   bg = "none",   fg = "#31748f",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiHR" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiLink" , {   bg = "none",   fg = "#c4a7e7",   sp = "",   underline = true } )
vim.api.nvim_set_hl(0,  "VimwikiList" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "VimwikiNoExistsLink" , {   bg = "none",   fg = "#eb6f92",   sp = "" } )
vim.api.nvim_set_hl(0,  "Visual" , {   bg = "#403d52",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "WarningMsg" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKey" , {   bg = "none",   fg = "#c4a7e7",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKeyDesc" , {   bg = "none",   fg = "#f6c177",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKeyFloat" , {   bg = "#1f1d2e",   fg = "none",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKeyGroup" , {   bg = "none",   fg = "#9ccfd8",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKeySeparator" , {   bg = "none",   fg = "#908caa",   sp = "" } )
vim.api.nvim_set_hl(0,  "WhichKeyValue" , {   bg = "none",   fg = "#ebbcba",   sp = "" } )
vim.api.nvim_set_hl(0,  "WildMenu" , {   bg = "none",   fg = "none",   link = "IncSearch",   sp = "" } )
