vim.api.nvim_set_hl( 0, "@variable.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@type.qualifier" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@type.definition" , { default = true, link = "Typedef" }  )
vim.api.nvim_set_hl( 0, "@type.builtin" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@type" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@todo" , { default = true, link = "Todo" }  )
vim.api.nvim_set_hl( 0, "@text.warning" , { default = true, link = "Todo" }  )
vim.api.nvim_set_hl( 0, "@text.uri" , { default = true, link = "Underlined" }  )
vim.api.nvim_set_hl( 0, "@text.underline" , { underline = true }  )
vim.api.nvim_set_hl( 0, "@text.title" , { default = true, link = "Title" }  )
vim.api.nvim_set_hl( 0, "@text.strong" , { bold = true, default = true }  )
vim.api.nvim_set_hl( 0, "@text.strike" , { strikethrough = true }  )
vim.api.nvim_set_hl( 0, "@text.reference" , { default = true, link = "Constant" }  )
vim.api.nvim_set_hl( 0, "@text.note" , { default = true, link = "SpecialComment" }  )
vim.api.nvim_set_hl( 0, "@text.math" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@text.literal" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@text.environment.name" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@text.environment" , { default = true, link = "Macro" }  )
vim.api.nvim_set_hl( 0, "@text.emphasis" , { default = true, italic = true }  )
vim.api.nvim_set_hl( 0, "@text.danger" , { default = true, link = "WarningMsg" }  )
vim.api.nvim_set_hl( 0, "@text" , { default = true, link = "@none" }  )
vim.api.nvim_set_hl( 0, "@none" , { default = true }  )
vim.api.nvim_set_hl( 0, "@tag.delimiter" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@tag.attribute" , { default = true, link = "@property" }  )
vim.api.nvim_set_hl( 0, "@property" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@tag" , { default = true, link = "Label" }  )
vim.api.nvim_set_hl( 0, "@symbol" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@string.special" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@string.regex" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@string.escape" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@string" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@storageclass" , { default = true, link = "StorageClass" }  )
vim.api.nvim_set_hl( 0, "@repeat" , { default = true, link = "Repeat" }  )
vim.api.nvim_set_hl( 0, "@punctuation.special" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@punctuation.delimiter" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@punctuation.bracket" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@preproc" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "@parameter.reference" , { default = true, link = "@parameter" }  )
vim.api.nvim_set_hl( 0, "@parameter" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@operator" , { default = true, link = "Operator" }  )
vim.api.nvim_set_hl( 0, "@number" , { default = true, link = "Number" }  )
vim.api.nvim_set_hl( 0, "@namespace" , { default = true, link = "Include" }  )
vim.api.nvim_set_hl( 0, "@method.call" , { default = true, link = "@method" }  )
vim.api.nvim_set_hl( 0, "@method" , { default = true, link = "Function" }  )
vim.api.nvim_set_hl( 0, "@label" , { default = true, link = "Label" }  )
vim.api.nvim_set_hl( 0, "@keyword.return" , { default = true, link = "@keyword" }  )
vim.api.nvim_set_hl( 0, "@keyword" , { default = true, link = "Keyword" }  )
vim.api.nvim_set_hl( 0, "@keyword.operator" , { default = true, link = "@operator" }  )
vim.api.nvim_set_hl( 0, "@keyword.function" , { default = true, link = "Keyword" }  )
vim.api.nvim_set_hl( 0, "@include" , { default = true, link = "Include" }  )
vim.api.nvim_set_hl( 0, "@function.macro" , { default = true, link = "Macro" }  )
vim.api.nvim_set_hl( 0, "@function.call" , { default = true, link = "@function" }  )
vim.api.nvim_set_hl( 0, "@function" , { default = true, link = "Function" }  )
vim.api.nvim_set_hl( 0, "@function.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@float" , { default = true, link = "Float" }  )
vim.api.nvim_set_hl( 0, "@field" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@exception" , { default = true, link = "Exception" }  )
vim.api.nvim_set_hl( 0, "@define" , { default = true, link = "Define" }  )
vim.api.nvim_set_hl( 0, "@debug" , { default = true, link = "Debug" }  )
vim.api.nvim_set_hl( 0, "@constructor" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@constant.macro" , { default = true, link = "Define" }  )
vim.api.nvim_set_hl( 0, "@constant.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@constant" , { default = true, link = "Constant" }  )
vim.api.nvim_set_hl( 0, "@conditional" , { default = true, link = "Conditional" }  )
vim.api.nvim_set_hl( 0, "@comment" , { default = true, link = "Comment" }  )
vim.api.nvim_set_hl( 0, "@character.special" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@character" , { default = true, link = "Character" }  )
vim.api.nvim_set_hl( 0, "@boolean" , { default = true, link = "Boolean" }  )
vim.api.nvim_set_hl( 0, "@attribute" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "@annotation" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitDeleted" , { fg = "#914c54" }  )
vim.api.nvim_set_hl( 0, "NormalNC" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitDirty" , { fg = "#6183ba" }  )
vim.api.nvim_set_hl( 0, "NvimTreeRootFolder" , { bold = true, fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NvimTreeNormalNC" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "MoreMsg" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "MsgArea" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "ModeMsg" , { bold = true, fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "MatchParen" , { bold = true, fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NeotestTarget" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "CursorLineNr" , { fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "LineNr" , { fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NeotestAdapterName" , { bold = true, fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "SignColumnSB" , { bg = "#e9e9ec", fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NeotestIndent" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "FoldColumn" , { bg = "#e1e2e7", fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "Special" , { fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "Folded" , { bg = "#a8aecb", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NeotestFocused" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "Character" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "VertSplit" , { fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "EndOfBuffer" , { fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "DiffText" , { bg = "#92a6d5" }  )
vim.api.nvim_set_hl( 0, "Directory" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "CursorLine" , { bg = "#c4c8da" }  )
vim.api.nvim_set_hl( 0, "CursorColumn" , { bg = "#c4c8da" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffAddHighlight" , { bg = "#aecde6", fg = "#2c6c75" }  )
vim.api.nvim_set_hl( 0, "CursorIM" , { bg = "#3760bf", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "lCursor" , { bg = "#3760bf", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "Cursor" , { bg = "#3760bf", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "Conceal" , { fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "NeogitRemote" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "ColorColumn" , { bg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "Foo" , { bg = "#d20065", fg = "#d20065" }  )
vim.api.nvim_set_hl( 0, "diffLine" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "diffFile" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "WarningMsg" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "@variable.builtin" , { fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "@text.warning" , { bg = "#8c6c3e", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "@text.reference" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "@text.danger" , { bg = "#c64343", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "@property" , { fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "Identifier" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "Statement" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "@string.regex" , { fg = "#2e5857" }  )
vim.api.nvim_set_hl( 0, "@string.escape" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "TabLineSel" , { bg = "#2e7de9", fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "TabLineFill" , { bg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "@punctuation.special" , { fg = "#006a83" }  )
vim.api.nvim_set_hl( 0, "@punctuation.delimiter" , { fg = "#006a83" }  )
vim.api.nvim_set_hl( 0, "@punctuation.bracket" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "@parameter" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "@operator" , { fg = "#006a83" }  )
vim.api.nvim_set_hl( 0, "@label" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "@keyword" , { fg = "#7847bd", italic = true }  )
vim.api.nvim_set_hl( 0, "@keyword.function" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "@field" , { fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "StatusLine" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "@constructor" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "Visual" , { bg = "#99a7df" }  )
vim.api.nvim_set_hl( 0, "MiniTrailspace" , { bg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "MiniTestPass" , { bold = true, fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "MiniTestFail" , { bold = true, fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "MiniTestEmphasis" , { bold = true }  )
vim.api.nvim_set_hl( 0, "MiniTablineVisible" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "MiniTablineTabpagesection" , { bg = "#e9e9ec", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedVisible" , { bg = "#e9e9ec", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedHidden" , { bg = "#e9e9ec", fg = "#7b613d" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedCurrent" , { bg = "#a8aecb", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "MiniTablineHidden" , { bg = "#e9e9ec", fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "MiniTablineFill" , { bg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniTablineCurrent" , { bg = "#a8aecb", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "MiniSurround" , { bg = "#b15c00", fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextHint" , { bg = "#acd7eb", fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeReplace" , { bg = "#f52a65", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeOther" , { bg = "#118c74", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextError" , { bg = "#e0d3dd", fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeInsert" , { bg = "#587539", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeCommand" , { bg = "#8c6c3e", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineInactive" , { bg = "#e9e9ec", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextWarn" , { bg = "#d0cccf", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineFileinfo" , { bg = "#c4c8da", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineDevinfo" , { bg = "#c4c8da", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextInfo" , { bg = "#b7d3ed", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineHint" , { sp = "#118c74", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineError" , { sp = "#c64343", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineWarn" , { sp = "#8c6c3e", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineInfo" , { sp = "#07879d", undercurl = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterInactive" , { fg = "#848cb5", italic = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterHeader" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "MiniStarterFooter" , { fg = "#8c6c3e", italic = true }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeVisual" , { bg = "#9854f1", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeNormal" , { bg = "#2e7de9", bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineFilename" , { bg = "#a8aecb", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "CmpItemMenu" , { bg = "NONE", fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "MiniStarterQuery" , { fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "MiniStarterSection" , { fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "MiniStarterItemPrefix" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbr" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrDeprecated" , { bg = "NONE", fg = "#a8aecb", strikethrough = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterItemBullet" , { fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "MiniStarterItem" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "DiffDelete" , { bg = "#dfccd4" }  )
vim.api.nvim_set_hl( 0, "Underlined" , { underline = true }  )
vim.api.nvim_set_hl( 0, "LspSignatureActiveParameter" , { fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "GitSignsChange" , { fg = "#526c9e" }  )
vim.api.nvim_set_hl( 0, "@text.literal.markdown_inline" , { bg = "#a1a6c5", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "SpecialKey" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "Keyword" , { fg = "#007197", italic = true }  )
vim.api.nvim_set_hl( 0, "Search" , { bg = "#7890dd", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "TelescopeBorder" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "TroubleCount" , { bg = "#a8aecb", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "Substitute" , { bg = "#f52a65", fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "NeogitHunkHeader" , { bg = "#c4c8da", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "Error" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "DiffAdd" , { bg = "#aecde6" }  )
vim.api.nvim_set_hl( 0, "illuminatedWord" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "Bold" , { bold = true }  )
vim.api.nvim_set_hl( 0, "ErrorMsg" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOBody" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "WinSeparator" , { bold = true, fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "Comment" , { fg = "#848cb5", italic = true }  )
vim.api.nvim_set_hl( 0, "GitGutterDelete" , { fg = "#b2555b" }  )
vim.api.nvim_set_hl( 0, "diffIndexLine" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "NeogitBranch" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "diffRemoved" , { fg = "#914c54" }  )
vim.api.nvim_set_hl( 0, "GitGutterChange" , { fg = "#526c9e" }  )
vim.api.nvim_set_hl( 0, "TSNodeKey" , { bold = true, fg = "#d20065" }  )
vim.api.nvim_set_hl( 0, "NeogitHunkHeaderHighlight" , { bg = "#a8aecb", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "diffChanged" , { fg = "#6183ba" }  )
vim.api.nvim_set_hl( 0, "GitGutterAdd" , { fg = "#266d6a" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffContextHighlight" , { bg = "#c3c6d8", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffDeleteHighlight" , { bg = "#dfccd4", fg = "#914c54" }  )
vim.api.nvim_set_hl( 0, "diffAdded" , { fg = "#2c6c75" }  )
vim.api.nvim_set_hl( 0, "NeotestRunning" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "Normal" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NeotestFailed" , { fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "NeotestSkipped" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NeotestTest" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NeotestNamespace" , { fg = "#38919f" }  )
vim.api.nvim_set_hl( 0, "NeotestFile" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "NeotestDir" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveMod" , { bg = "#e9e9ec", fg = "#7b613d" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveIndex" , { bg = "#e9e9ec", fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "BufferInactive" , { bg = "#e9e9ec", fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleTarget" , { bg = "#e9e9ec", fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "NormalSB" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "DiffChange" , { bg = "#d6d8e3" }  )
vim.api.nvim_set_hl( 0, "FloatBorder" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "Todo" , { bg = "#8c6c3e", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "IncSearch" , { bg = "#b15c00", fg = "#e9e9ed" }  )
vim.api.nvim_set_hl( 0, "PmenuSbar" , { bg = "#d8d8dc" }  )
vim.api.nvim_set_hl( 0, "PmenuThumb" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "Question" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "WhichKeyGroup" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitNew" , { fg = "#2c6c75" }  )
vim.api.nvim_set_hl( 0, "NvimTreeWinSeparator" , { bg = "#e9e9ec", fg = "#e9e9ec" }  )
vim.api.nvim_set_hl( 0, "PreProc" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "CurSearch" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "SpellBad" , { bg = "#c64343", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SpellCap" , { bg = "#8c6c3e", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SignColumn" , { bg = "#e1e2e7", fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "SpellLocal" , { bg = "#07879d", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SpellRare" , { bg = "#118c74", undercurl = true }  )
vim.api.nvim_set_hl( 0, "NvimTreeNormal" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "TabLine" , { bg = "#e9e9ec", fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "VisualNOS" , { bg = "#99a7df" }  )
vim.api.nvim_set_hl( 0, "NavicIconsOperator" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "WildMenu" , { bg = "#99a7df" }  )
vim.api.nvim_set_hl( 0, "TelescopeNormal" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "Title" , { bold = true, fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNull" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "DiagnosticHint" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "GitSignsDelete" , { fg = "#b2555b" }  )
vim.api.nvim_set_hl( 0, "DiagnosticInfo" , { fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "Italic" , { italic = true }  )
vim.api.nvim_set_hl( 0, "Constant" , { fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "DiagnosticWarn" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "qfLineNr" , { fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "DiagnosticError" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "qfFileName" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "Function" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "htmlH1" , { bold = true, fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNumber" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsString" , { bg = "NONE", fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "NavicIconsConstant" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "htmlH2" , { bold = true, fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "mkdCodeDelimiter" , { bg = "#a1a6c5", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "mkdCodeStart" , { bold = true, fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "Type" , { fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "mkdCodeEnd" , { bold = true, fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "markdownHeadingDelimiter" , { bold = true, fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "markdownCode" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "markdownCodeBlock" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "markdownH1" , { bold = true, fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "markdownH2" , { bold = true, fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "markdownLinkText" , { fg = "#2e7de9", underline = true }  )
vim.api.nvim_set_hl( 0, "@punctuation.special.markdown" , { bold = true, fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "TSNote" , { bg = "#07879d", fg = "#e1e2e7" }  )
vim.api.nvim_set_hl( 0, "debugPC" , { bg = "#e9e9ec" }  )
vim.api.nvim_set_hl( 0, "debugBreakpoint" , { bg = "#b7d3ed", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "LspInfoBorder" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "ALEErrorSign" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "ALEWarningSign" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "GitSignsAdd" , { fg = "#266d6a" }  )
vim.api.nvim_set_hl( 0, "@variable" , {}  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrMatch" , { bg = "NONE", fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrMatchFuzzy" , { bg = "NONE", fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "rainbowcol1" , { fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "rainbowcol2" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "NonText" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "rainbowcol4" , { fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "rainbowcol5" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "rainbowcol6" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "rainbowcol7" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "TroubleText" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindMethod" , { bg = "NONE", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "TroubleNormal" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "illuminatedCurWord" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordText" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NeotestMarked" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NeotestWinSelect" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NeotestExpandMarker" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "Whitespace" , { fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NeotestBorder" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "Operator" , { fg = "#006a83" }  )
vim.api.nvim_set_hl( 0, "StatusLineNC" , { bg = "#e9e9ec", fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "MiniStarterCurrent" , { nocombine = true }  )
vim.api.nvim_set_hl( 0, "rainbowcol3" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "MiniJump2dSpot" , { bold = true, fg = "#d20065", nocombine = true }  )
vim.api.nvim_set_hl( 0, "MiniJump" , { bg = "#d20065", fg = "#474747" }  )
vim.api.nvim_set_hl( 0, "MiniIndentscopePrefix" , { nocombine = true }  )
vim.api.nvim_set_hl( 0, "MiniIndentscopeSymbol" , { fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "MiniCursorwordCurrent" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "MiniCursorword" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "MiniCompletionActiveParameter" , { underline = true }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEBody" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGBody" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "PmenuSel" , { bg = "#b3b8d1" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNBody" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORBody" , { bg = "#e1e2e7", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACETitle" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGTitle" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOTitle" , { fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNTitle" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORTitle" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEIcon" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGIcon" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOIcon" , { fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNIcon" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORIcon" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEBorder" , { bg = "#e1e2e7", fg = "#b9b3cd" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGBorder" , { bg = "#e1e2e7", fg = "#c4c6d6" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOBorder" , { bg = "#e1e2e7", fg = "#44bbe2" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNBorder" , { bg = "#e1e2e7", fg = "#c0a388" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORBorder" , { bg = "#e1e2e7", fg = "#dbb6bb" }  )
vim.api.nvim_set_hl( 0, "YankyYanked" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "YankyPut" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "ScrollbarMisc" , { bg = "NONE", fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "ScrollbarMiscHandle" , { bg = "#c4c8da", fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHint" , { bg = "NONE", fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHintHandle" , { bg = "#c4c8da", fg = "#118c74" }  )
vim.api.nvim_set_hl( 0, "ScrollbarInfo" , { bg = "NONE", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "ScrollbarInfoHandle" , { bg = "#c4c8da", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "ScrollbarWarn" , { bg = "NONE", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "ScrollbarWarnHandle" , { bg = "#c4c8da", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "ScrollbarError" , { bg = "NONE", fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "ScrollbarErrorHandle" , { bg = "#c4c8da", fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "ScrollbarSearch" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "ScrollbarSearchHandle" , { bg = "#c4c8da", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHandle" , { bg = "#c4c8da", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "IndentBlanklineContextChar" , { fg = "#7847bd", nocombine = true }  )
vim.api.nvim_set_hl( 0, "IndentBlanklineChar" , { fg = "#a8aecb", nocombine = true }  )
vim.api.nvim_set_hl( 0, "NavicSeparator" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NavicText" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NavicIconsTypeParameter" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindDefault" , { bg = "NONE", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEvent" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsStruct" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEnumMember" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "Pmenu" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NavicIconsKeyword" , { bg = "NONE", fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "NavicIconsKey" , { bg = "NONE", fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "NavicIconsObject" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsArray" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsBoolean" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "LspReferenceWrite" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "LspReferenceRead" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "LspReferenceText" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NavicIconsVariable" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "NavicIconsFunction" , { bg = "NONE", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NavicIconsInterface" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEnum" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsConstructor" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsField" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "NavicIconsProperty" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "NavicIconsMethod" , { bg = "NONE", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NavicIconsClass" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "NavicIconsPackage" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNamespace" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "NavicIconsModule" , { bg = "NONE", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "NavicIconsFile" , { bg = "NONE", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindSnippet" , { bg = "NONE", fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindOperator" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEnumMember" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindTypeParameter" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindField" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindProperty" , { bg = "NONE", fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindModule" , { bg = "NONE", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindUnit" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEnum" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEvent" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindStruct" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindInterface" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindClass" , { bg = "NONE", fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindConstructor" , { bg = "NONE", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NormalFloat" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindFunction" , { bg = "NONE", fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindValue" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindReference" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindConstant" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindVariable" , { bg = "NONE", fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindKeyword" , { bg = "NONE", fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "CmpDocumentationBorder" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "CmpDocumentation" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "LightspeedUnlabeledMatch" , { bold = true, fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "LightspeedShortcut" , { bg = "#d20065", bold = true, fg = "#3760bf", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedPendingOpArea" , { bg = "#d20065", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "LightspeedOneCharMatch" , { bg = "#d20065", bold = true, fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "LightspeedMaskedChar" , { fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelOverlapped" , { fg = "#d20065", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelDistantOverlapped" , { fg = "#38919f", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelDistant" , { bold = true, fg = "#387068", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabel" , { bold = true, fg = "#d20065", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedGreyWash" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "LeapBackdrop" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "LeapLabelSecondary" , { bold = true, fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "LeapLabelPrimary" , { bold = true, fg = "#d20065" }  )
vim.api.nvim_set_hl( 0, "LeapMatch" , { bg = "#d20065", bold = true, fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "TSNodeUnmatched" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "LspCodeLens" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "HopUnmatched" , { fg = "#8990b3" }  )
vim.api.nvim_set_hl( 0, "HopNextKey2" , { fg = "#168aa3" }  )
vim.api.nvim_set_hl( 0, "HopNextKey1" , { bold = true, fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "NeotestPassed" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "HopNextKey" , { bold = true, fg = "#d20065" }  )
vim.api.nvim_set_hl( 0, "SneakScope" , { bg = "#99a7df" }  )
vim.api.nvim_set_hl( 0, "Sneak" , { bg = "#9854f1", fg = "#c4c8da" }  )
vim.api.nvim_set_hl( 0, "BufferTabpage" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "BufferTabpages" , { bg = "#e9e9ec", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveTarget" , { bg = "#e9e9ec", fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveSign" , { bg = "#e9e9ec", fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "diffNewFile" , { fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "diffOldFile" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordWrite" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordRead" , { bg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleSign" , { bg = "#e9e9ec", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleMod" , { bg = "#e9e9ec", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleIndex" , { bg = "#e9e9ec", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "BufferVisible" , { bg = "#e9e9ec", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentTarget" , { bg = "#a8aecb", fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentSign" , { bg = "#a8aecb", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentMod" , { bg = "#a8aecb", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentIndex" , { bg = "#a8aecb", fg = "#07879d" }  )
vim.api.nvim_set_hl( 0, "BufferCurrent" , { bg = "#a8aecb", fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "BufferLineIndicatorSelected" , { fg = "#6183ba" }  )
vim.api.nvim_set_hl( 0, "healthWarning" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "healthSuccess" , { fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "healthError" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "TargetWord" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "ReferencesIcon" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "DefinitionIcon" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "DefinitionCount" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "ReferencesCount" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "LspSagaSignatureHelpBorder" , { fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionContent" , { fg = "#7847bd" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionTitle" , { fg = "#188092" }  )
vim.api.nvim_set_hl( 0, "LspSagaFinderSelection" , { fg = "#99a7df" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionBorder" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "LspSagaDefPreviewBorder" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "LspSagaRenameBorder" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "LspSagaHoverBorder" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "LspSagaBorderTitle" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "LspFloatWinBorder" , { fg = "#7890dd" }  )
vim.api.nvim_set_hl( 0, "LspFloatWinNormal" , { bg = "#e9e9ec" }  )
vim.api.nvim_set_hl( 0, "DiagnosticInformation" , { link = "DiagnosticInfo" }  )
vim.api.nvim_set_hl( 0, "DiagnosticWarning" , { link = "DiagnosticWarn" }  )
vim.api.nvim_set_hl( 0, "WhichKeyValue" , { fg = "#68709a" }  )
vim.api.nvim_set_hl( 0, "WhichKeyFloat" , { bg = "#e9e9ec" }  )
vim.api.nvim_set_hl( 0, "WhichKeySeparator" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "WhichKeySeperator" , { fg = "#848cb5" }  )
vim.api.nvim_set_hl( 0, "WhichKeyDesc" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "String" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "WhichKey" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "AlphaButtons" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "AlphaFooter" , { fg = "#8c6c3e", italic = true }  )
vim.api.nvim_set_hl( 0, "AlphaHeaderLabel" , { fg = "#b15c00" }  )
vim.api.nvim_set_hl( 0, "AlphaHeader" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "AlphaShortcut" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "DashboardFooter" , { fg = "#8c6c3e", italic = true }  )
vim.api.nvim_set_hl( 0, "DashboardCenter" , { fg = "#9854f1" }  )
vim.api.nvim_set_hl( 0, "DashboardHeader" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "DashboardShortCut" , { fg = "#007197" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette9" , { fg = "#f52a65" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette7" , { fg = "#3760bf" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette6" , { fg = "#387068" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette4" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette3" , { fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette2" , { fg = "#587539" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette1" , { fg = "#c64343" }  )
vim.api.nvim_set_hl( 0, "QuickFixLine" , { bg = "#99a7df", bold = true }  )
vim.api.nvim_set_hl( 0, "FernBranchText" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NeoTreeNormalNC" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NeoTreeNormal" , { bg = "#e9e9ec", fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NvimTreeFolderIcon" , { bg = "NONE", fg = "#8c6c3e" }  )
vim.api.nvim_set_hl( 0, "NvimTreeSymlink" , { fg = "#2e7de9" }  )
vim.api.nvim_set_hl( 0, "NvimTreeImageFile" , { fg = "#6172b0" }  )
vim.api.nvim_set_hl( 0, "NvimTreeIndentMarker" , { fg = "#a8aecb" }  )
vim.api.nvim_set_hl( 0, "NvimTreeSpecialFile" , { fg = "#7847bd", underline = true }  )
vim.api.nvim_set_hl( 0, "NvimTreeOpenedFile" , { bg = "#c4c8da" }  )

vim.api.nvim_set_hl(0, "TelescopeSelection" , {link = "ScrollbarHintHandle"} )
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret" , {link = "ScrollbarHintHandle"} )
vim.api.nvim_set_hl(0, "TelescopeMatching" , {link = "ScrollbarSearchHandle"} )
