vim.api.nvim_set_hl( 0, "@variable.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@type.qualifier" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@type.definition" , { default = true, link = "Typedef" }  )
vim.api.nvim_set_hl( 0, "@type.builtin" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@type" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@todo" , { default = true, link = "Todo" }  )
vim.api.nvim_set_hl( 0, "@text.warning" , { default = true, link = "Todo" }  )
vim.api.nvim_set_hl( 0, "@text.uri" , { default = true, link = "Underlined" }  )
vim.api.nvim_set_hl( 0, "@text.underline" , { underline = true }  )
vim.api.nvim_set_hl( 0, "@text.title" , { default = true, link = "Title" }  )
vim.api.nvim_set_hl( 0, "@text.strong" , { bold = true, default = true }  )
vim.api.nvim_set_hl( 0, "@text.strike" , { strikethrough = true }  )
vim.api.nvim_set_hl( 0, "@text.reference" , { default = true, link = "Constant" }  )
vim.api.nvim_set_hl( 0, "@text.note" , { default = true, link = "SpecialComment" }  )
vim.api.nvim_set_hl( 0, "@text.math" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@text.literal" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@text.environment.name" , { default = true, link = "Type" }  )
vim.api.nvim_set_hl( 0, "@text.environment" , { default = true, link = "Macro" }  )
vim.api.nvim_set_hl( 0, "@text.emphasis" , { default = true, italic = true }  )
vim.api.nvim_set_hl( 0, "@text.danger" , { default = true, link = "WarningMsg" }  )
vim.api.nvim_set_hl( 0, "@text" , { default = true, link = "@none" }  )
vim.api.nvim_set_hl( 0, "@none" , { default = true }  )
vim.api.nvim_set_hl( 0, "@tag.delimiter" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@tag.attribute" , { default = true, link = "@property" }  )
vim.api.nvim_set_hl( 0, "@property" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@tag" , { default = true, link = "Label" }  )
vim.api.nvim_set_hl( 0, "@symbol" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@string.special" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@string.regex" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@string.escape" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@string" , { default = true, link = "String" }  )
vim.api.nvim_set_hl( 0, "@storageclass" , { default = true, link = "StorageClass" }  )
vim.api.nvim_set_hl( 0, "@repeat" , { default = true, link = "Repeat" }  )
vim.api.nvim_set_hl( 0, "@punctuation.special" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@punctuation.delimiter" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@punctuation.bracket" , { default = true, link = "Delimiter" }  )
vim.api.nvim_set_hl( 0, "@preproc" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "@parameter.reference" , { default = true, link = "@parameter" }  )
vim.api.nvim_set_hl( 0, "@parameter" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@operator" , { default = true, link = "Operator" }  )
vim.api.nvim_set_hl( 0, "@number" , { default = true, link = "Number" }  )
vim.api.nvim_set_hl( 0, "@namespace" , { default = true, link = "Include" }  )
vim.api.nvim_set_hl( 0, "@method.call" , { default = true, link = "@method" }  )
vim.api.nvim_set_hl( 0, "@method" , { default = true, link = "Function" }  )
vim.api.nvim_set_hl( 0, "@label" , { default = true, link = "Label" }  )
vim.api.nvim_set_hl( 0, "@keyword.return" , { default = true, link = "@keyword" }  )
vim.api.nvim_set_hl( 0, "@keyword" , { default = true, link = "Keyword" }  )
vim.api.nvim_set_hl( 0, "@keyword.operator" , { default = true, link = "@operator" }  )
vim.api.nvim_set_hl( 0, "@keyword.function" , { default = true, link = "Keyword" }  )
vim.api.nvim_set_hl( 0, "@include" , { default = true, link = "Include" }  )
vim.api.nvim_set_hl( 0, "@function.macro" , { default = true, link = "Macro" }  )
vim.api.nvim_set_hl( 0, "@function.call" , { default = true, link = "@function" }  )
vim.api.nvim_set_hl( 0, "@function" , { default = true, link = "Function" }  )
vim.api.nvim_set_hl( 0, "@function.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@float" , { default = true, link = "Float" }  )
vim.api.nvim_set_hl( 0, "@field" , { default = true, link = "Identifier" }  )
vim.api.nvim_set_hl( 0, "@exception" , { default = true, link = "Exception" }  )
vim.api.nvim_set_hl( 0, "@define" , { default = true, link = "Define" }  )
vim.api.nvim_set_hl( 0, "@debug" , { default = true, link = "Debug" }  )
vim.api.nvim_set_hl( 0, "@constructor" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@constant.macro" , { default = true, link = "Define" }  )
vim.api.nvim_set_hl( 0, "@constant.builtin" , { default = true, link = "Special" }  )
vim.api.nvim_set_hl( 0, "@constant" , { default = true, link = "Constant" }  )
vim.api.nvim_set_hl( 0, "@conditional" , { default = true, link = "Conditional" }  )
vim.api.nvim_set_hl( 0, "@comment" , { default = true, link = "Comment" }  )
vim.api.nvim_set_hl( 0, "@character.special" , { default = true, link = "SpecialChar" }  )
vim.api.nvim_set_hl( 0, "@character" , { default = true, link = "Character" }  )
vim.api.nvim_set_hl( 0, "@boolean" , { default = true, link = "Boolean" }  )
vim.api.nvim_set_hl( 0, "@attribute" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "@annotation" , { default = true, link = "PreProc" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitDeleted" , { fg = "#e26a75" }  )
vim.api.nvim_set_hl( 0, "NormalNC" , { bg = "#2f334d", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitDirty" , { fg = "#7ca1f2" }  )
vim.api.nvim_set_hl( 0, "NvimTreeRootFolder" , { bold = true, fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NvimTreeNormalNC" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "MoreMsg" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "MsgArea" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "ModeMsg" , { bold = true, fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "MatchParen" , { bold = true, fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NeotestTarget" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "CursorLineNr" , { fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "LineNr" , { fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NeotestAdapterName" , { bold = true, fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "SignColumnSB" , { bg = "#1e2030", fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NeotestIndent" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "FoldColumn" , { bg = "#222436", fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "Special" , { fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "Folded" , { bg = "#3b4261", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NeotestFocused" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "Character" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "VertSplit" , { fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "EndOfBuffer" , { fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "DiffText" , { bg = "#394b70" }  )
vim.api.nvim_set_hl( 0, "Directory" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "CursorLine" , { bg = "#2f334d" }  )
vim.api.nvim_set_hl( 0, "CursorColumn" , { bg = "#2f334d" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffAddHighlight" , { bg = "#273849", fg = "#b8db87" }  )
vim.api.nvim_set_hl( 0, "CursorIM" , { bg = "#c8d3f5", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "lCursor" , { bg = "#c8d3f5", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "Cursor" , { bg = "#c8d3f5", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "Conceal" , { fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "NeogitRemote" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "ColorColumn" , { bg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "Foo" , { bg = "#ff007c", fg = "#ff007c" }  )
vim.api.nvim_set_hl( 0, "diffLine" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "diffFile" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "WarningMsg" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "@variable.builtin" , { fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "@text.warning" , { bg = "#ffc777", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "@text.reference" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "@text.danger" , { bg = "#c53b53", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "@property" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "Identifier" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "Statement" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "@string.regex" , { fg = "#b4f9f8" }  )
vim.api.nvim_set_hl( 0, "@string.escape" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "TabLineSel" , { bg = "#82aaff", fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "TabLineFill" , { bg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "@punctuation.special" , { fg = "#89ddff" }  )
vim.api.nvim_set_hl( 0, "@punctuation.delimiter" , { fg = "#89ddff" }  )
vim.api.nvim_set_hl( 0, "@punctuation.bracket" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "@parameter" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "@operator" , { fg = "#89ddff" }  )
vim.api.nvim_set_hl( 0, "@label" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "@keyword" , { fg = "#fca7ea", italic = true }  )
vim.api.nvim_set_hl( 0, "@keyword.function" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "@field" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "StatusLine" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "@constructor" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "Visual" , { bg = "#3654a7" }  )
vim.api.nvim_set_hl( 0, "MiniTrailspace" , { bg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "MiniTestPass" , { bold = true, fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "MiniTestFail" , { bold = true, fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "MiniTestEmphasis" , { bold = true }  )
vim.api.nvim_set_hl( 0, "MiniTablineVisible" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "MiniTablineTabpagesection" , { bg = "#1e2030", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedVisible" , { bg = "#1e2030", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedHidden" , { bg = "#1e2030", fg = "#bd9664" }  )
vim.api.nvim_set_hl( 0, "MiniTablineModifiedCurrent" , { bg = "#3b4261", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "MiniTablineHidden" , { bg = "#1e2030", fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "MiniTablineFill" , { bg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniTablineCurrent" , { bg = "#3b4261", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "MiniSurround" , { bg = "#ff966c", fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextHint" , { bg = "#273644", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeReplace" , { bg = "#ff757f", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeOther" , { bg = "#4fd6be", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextError" , { bg = "#322639", fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeInsert" , { bg = "#c3e88d", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeCommand" , { bg = "#ffc777", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineInactive" , { bg = "#1e2030", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextWarn" , { bg = "#38343d", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineFileinfo" , { bg = "#2f334d", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineDevinfo" , { bg = "#2f334d", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "DiagnosticVirtualTextInfo" , { bg = "#203346", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineHint" , { sp = "#4fd6be", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineError" , { sp = "#c53b53", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineWarn" , { sp = "#ffc777", undercurl = true }  )
vim.api.nvim_set_hl( 0, "DiagnosticUnderlineInfo" , { sp = "#0db9d7", undercurl = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterInactive" , { fg = "#7a88cf", italic = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterHeader" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "MiniStarterFooter" , { fg = "#ffc777", italic = true }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeVisual" , { bg = "#c099ff", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineModeNormal" , { bg = "#82aaff", bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "MiniStatuslineFilename" , { bg = "#3b4261", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "CmpItemMenu" , { bg = "NONE", fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "MiniStarterQuery" , { fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "MiniStarterSection" , { fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "MiniStarterItemPrefix" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbr" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrDeprecated" , { bg = "NONE", fg = "#3b4261", strikethrough = true }  )
vim.api.nvim_set_hl( 0, "MiniStarterItemBullet" , { fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "MiniStarterItem" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "DiffDelete" , { bg = "#3a273a" }  )
vim.api.nvim_set_hl( 0, "Underlined" , { underline = true }  )
vim.api.nvim_set_hl( 0, "LspSignatureActiveParameter" , { fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "GitSignsChange" , { fg = "#485a86" }  )
vim.api.nvim_set_hl( 0, "@text.literal.markdown_inline" , { bg = "#444a73", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "SpecialKey" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "Keyword" , { fg = "#86e1fc", italic = true }  )
vim.api.nvim_set_hl( 0, "Search" , { bg = "#3e68d7", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "TelescopeBorder" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "TroubleCount" , { bg = "#3b4261", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "Substitute" , { bg = "#ff757f", fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "NeogitHunkHeader" , { bg = "#2f334d", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "Error" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "DiffAdd" , { bg = "#273849" }  )
vim.api.nvim_set_hl( 0, "illuminatedWord" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "Bold" , { bold = true }  )
vim.api.nvim_set_hl( 0, "ErrorMsg" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOBody" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "WinSeparator" , { bold = true, fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "Comment" , { fg = "#7a88cf", italic = true }  )
vim.api.nvim_set_hl( 0, "GitGutterDelete" , { fg = "#b55a67" }  )
vim.api.nvim_set_hl( 0, "diffIndexLine" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "NeogitBranch" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "diffRemoved" , { fg = "#e26a75" }  )
vim.api.nvim_set_hl( 0, "GitGutterChange" , { fg = "#485a86" }  )
vim.api.nvim_set_hl( 0, "TSNodeKey" , { bold = true, fg = "#ff007c" }  )
vim.api.nvim_set_hl( 0, "NeogitHunkHeaderHighlight" , { bg = "#3b4261", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "diffChanged" , { fg = "#7ca1f2" }  )
vim.api.nvim_set_hl( 0, "GitGutterAdd" , { fg = "#627259" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffContextHighlight" , { bg = "#2f334c", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NeogitDiffDeleteHighlight" , { bg = "#3a273a", fg = "#e26a75" }  )
vim.api.nvim_set_hl( 0, "diffAdded" , { fg = "#b8db87" }  )
vim.api.nvim_set_hl( 0, "NeotestRunning" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "Normal" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NeotestFailed" , { fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "NeotestSkipped" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NeotestTest" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NeotestNamespace" , { fg = "#41a6b5" }  )
vim.api.nvim_set_hl( 0, "NeotestFile" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "NeotestDir" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveMod" , { bg = "#1e2030", fg = "#bd9664" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveIndex" , { bg = "#1e2030", fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "BufferInactive" , { bg = "#1e2030", fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleTarget" , { bg = "#1e2030", fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "NormalSB" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "DiffChange" , { bg = "#252a3f" }  )
vim.api.nvim_set_hl( 0, "FloatBorder" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "Todo" , { bg = "#ffc777", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "IncSearch" , { bg = "#ff966c", fg = "#1b1d2b" }  )
vim.api.nvim_set_hl( 0, "PmenuSbar" , { bg = "#292b3a" }  )
vim.api.nvim_set_hl( 0, "PmenuThumb" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "Question" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "WhichKeyGroup" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NvimTreeGitNew" , { fg = "#b8db87" }  )
vim.api.nvim_set_hl( 0, "NvimTreeWinSeparator" , { bg = "#1e2030", fg = "#1e2030" }  )
vim.api.nvim_set_hl( 0, "PreProc" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "CurSearch" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "SpellBad" , { sp = "#c53b53", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SpellCap" , { sp = "#ffc777", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SignColumn" , { bg = "#222436", fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "SpellLocal" , { sp = "#0db9d7", undercurl = true }  )
vim.api.nvim_set_hl( 0, "SpellRare" , { sp = "#4fd6be", undercurl = true }  )
vim.api.nvim_set_hl( 0, "NvimTreeNormal" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "TabLine" , { bg = "#1e2030", fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "VisualNOS" , { bg = "#3654a7" }  )
vim.api.nvim_set_hl( 0, "NavicIconsOperator" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "WildMenu" , { bg = "#3654a7" }  )
vim.api.nvim_set_hl( 0, "TelescopeNormal" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "Title" , { bold = true, fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNull" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "DiagnosticHint" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "GitSignsDelete" , { fg = "#b55a67" }  )
vim.api.nvim_set_hl( 0, "DiagnosticInfo" , { fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "Italic" , { italic = true }  )
vim.api.nvim_set_hl( 0, "Constant" , { fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "DiagnosticWarn" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "qfLineNr" , { fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "DiagnosticError" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "qfFileName" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "Function" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "htmlH1" , { bold = true, fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNumber" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsString" , { bg = "NONE", fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "NavicIconsConstant" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "htmlH2" , { bold = true, fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "mkdCodeDelimiter" , { bg = "#444a73", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "mkdCodeStart" , { bold = true, fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "Type" , { fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "mkdCodeEnd" , { bold = true, fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "markdownHeadingDelimiter" , { bold = true, fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "markdownCode" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "markdownCodeBlock" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "markdownH1" , { bold = true, fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "markdownH2" , { bold = true, fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "markdownLinkText" , { fg = "#82aaff", underline = true }  )
vim.api.nvim_set_hl( 0, "@punctuation.special.markdown" , { bold = true, fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "TSNote" , { bg = "#0db9d7", fg = "#222436" }  )
vim.api.nvim_set_hl( 0, "debugPC" , { bg = "#1e2030" }  )
vim.api.nvim_set_hl( 0, "debugBreakpoint" , { bg = "#203346", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "LspInfoBorder" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "ALEErrorSign" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "ALEWarningSign" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "GitSignsAdd" , { fg = "#627259" }  )
vim.api.nvim_set_hl( 0, "@variable" , {}  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrMatch" , { bg = "NONE", fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "CmpItemAbbrMatchFuzzy" , { bg = "NONE", fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "rainbowcol1" , { fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "rainbowcol2" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "NonText" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "rainbowcol4" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "rainbowcol5" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "rainbowcol6" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "rainbowcol7" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "TroubleText" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindMethod" , { bg = "NONE", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "TroubleNormal" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "illuminatedCurWord" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordText" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NeotestMarked" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NeotestWinSelect" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NeotestExpandMarker" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "Whitespace" , { fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NeotestBorder" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "Operator" , { fg = "#89ddff" }  )
vim.api.nvim_set_hl( 0, "StatusLineNC" , { bg = "#1e2030", fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "MiniStarterCurrent" , { nocombine = true }  )
vim.api.nvim_set_hl( 0, "rainbowcol3" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "MiniJump2dSpot" , { bold = true, fg = "#ff007c", nocombine = true }  )
vim.api.nvim_set_hl( 0, "MiniJump" , { bg = "#ff007c", fg = "#ffffff" }  )
vim.api.nvim_set_hl( 0, "MiniIndentscopePrefix" , { nocombine = true }  )
vim.api.nvim_set_hl( 0, "MiniIndentscopeSymbol" , { fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "MiniCursorwordCurrent" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "MiniCursorword" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "MiniCompletionActiveParameter" , { underline = true }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEBody" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGBody" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "PmenuSel" , { bg = "#363c58" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNBody" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORBody" , { bg = "#222436", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACETitle" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGTitle" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOTitle" , { fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNTitle" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORTitle" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEIcon" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGIcon" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOIcon" , { fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNIcon" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORIcon" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "NotifyTRACEBorder" , { bg = "#222436", fg = "#634b6c" }  )
vim.api.nvim_set_hl( 0, "NotifyDEBUGBorder" , { bg = "#222436", fg = "#3c4264" }  )
vim.api.nvim_set_hl( 0, "NotifyINFOBorder" , { bg = "#222436", fg = "#1c5166" }  )
vim.api.nvim_set_hl( 0, "NotifyWARNBorder" , { bg = "#222436", fg = "#64554a" }  )
vim.api.nvim_set_hl( 0, "NotifyERRORBorder" , { bg = "#222436", fg = "#532b3f" }  )
vim.api.nvim_set_hl( 0, "YankyYanked" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "YankyPut" , { link = "IncSearch" }  )
vim.api.nvim_set_hl( 0, "ScrollbarMisc" , { bg = "NONE", fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "ScrollbarMiscHandle" , { bg = "#2f334d", fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHint" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHintHandle" , { bg = "#2f334d", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "ScrollbarInfo" , { bg = "NONE", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "ScrollbarInfoHandle" , { bg = "#2f334d", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "ScrollbarWarn" , { bg = "NONE", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "ScrollbarWarnHandle" , { bg = "#2f334d", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "ScrollbarError" , { bg = "NONE", fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "ScrollbarErrorHandle" , { bg = "#2f334d", fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "ScrollbarSearch" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "ScrollbarSearchHandle" , { bg = "#2f334d", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "ScrollbarHandle" , {  bg = "#2f334d", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "IndentBlanklineContextChar" , { fg = "#fca7ea", nocombine = true }  )
vim.api.nvim_set_hl( 0, "IndentBlanklineChar" , { fg = "#3b4261", nocombine = true }  )
vim.api.nvim_set_hl( 0, "NavicSeparator" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NavicText" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NavicIconsTypeParameter" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindDefault" , { bg = "NONE", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEvent" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsStruct" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEnumMember" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "Pmenu" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NavicIconsKeyword" , { bg = "NONE", fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "NavicIconsKey" , { bg = "NONE", fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "NavicIconsObject" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsArray" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsBoolean" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "LspReferenceWrite" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "LspReferenceRead" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "LspReferenceText" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NavicIconsVariable" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "NavicIconsFunction" , { bg = "NONE", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NavicIconsInterface" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsEnum" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsConstructor" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsField" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "NavicIconsProperty" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "NavicIconsMethod" , { bg = "NONE", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NavicIconsClass" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "NavicIconsPackage" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NavicIconsNamespace" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "NavicIconsModule" , { bg = "NONE", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "NavicIconsFile" , { bg = "NONE", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindSnippet" , { bg = "NONE", fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindOperator" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEnumMember" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindTypeParameter" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindField" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindProperty" , { bg = "NONE", fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindModule" , { bg = "NONE", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindUnit" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEnum" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindEvent" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindStruct" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindInterface" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindClass" , { bg = "NONE", fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindConstructor" , { bg = "NONE", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NormalFloat" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindFunction" , { bg = "NONE", fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindValue" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindReference" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindConstant" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindVariable" , { bg = "NONE", fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "CmpItemKindKeyword" , { bg = "NONE", fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "CmpDocumentationBorder" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "CmpDocumentation" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "LightspeedUnlabeledMatch" , { bold = true, fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "LightspeedShortcut" , { bg = "#ff007c", bold = true, fg = "#c8d3f5", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedPendingOpArea" , { bg = "#ff007c", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "LightspeedOneCharMatch" , { bg = "#ff007c", bold = true, fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "LightspeedMaskedChar" , { fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelOverlapped" , { fg = "#ff007c", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelDistantOverlapped" , { fg = "#41a6b5", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabelDistant" , { bold = true, fg = "#4fd6be", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedLabel" , { bold = true, fg = "#ff007c", underline = true }  )
vim.api.nvim_set_hl( 0, "LightspeedGreyWash" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "LeapBackdrop" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "LeapLabelSecondary" , { bold = true, fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "LeapLabelPrimary" , { bold = true, fg = "#ff007c" }  )
vim.api.nvim_set_hl( 0, "LeapMatch" , { bg = "#ff007c", bold = true, fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "TSNodeUnmatched" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "LspCodeLens" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "HopUnmatched" , { fg = "#545c7e" }  )
vim.api.nvim_set_hl( 0, "HopNextKey2" , { fg = "#157d97" }  )
vim.api.nvim_set_hl( 0, "HopNextKey1" , { bold = true, fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "NeotestPassed" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "HopNextKey" , { bold = true, fg = "#ff007c" }  )
vim.api.nvim_set_hl( 0, "SneakScope" , { bg = "#3654a7" }  )
vim.api.nvim_set_hl( 0, "Sneak" , { bg = "#c099ff", fg = "#2f334d" }  )
vim.api.nvim_set_hl( 0, "BufferTabpage" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "BufferTabpages" , { bg = "#1e2030", fg = "NONE" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveTarget" , { bg = "#1e2030", fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "BufferInactiveSign" , { bg = "#1e2030", fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "diffNewFile" , { fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "diffOldFile" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordWrite" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "IlluminatedWordRead" , { bg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleSign" , { bg = "#1e2030", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleMod" , { bg = "#1e2030", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "BufferVisibleIndex" , { bg = "#1e2030", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "BufferVisible" , { bg = "#1e2030", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentTarget" , { bg = "#3b4261", fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentSign" , { bg = "#3b4261", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentMod" , { bg = "#3b4261", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "BufferCurrentIndex" , { bg = "#3b4261", fg = "#0db9d7" }  )
vim.api.nvim_set_hl( 0, "BufferCurrent" , { bg = "#3b4261", fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "BufferLineIndicatorSelected" , { fg = "#7ca1f2" }  )
vim.api.nvim_set_hl( 0, "healthWarning" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "healthSuccess" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "healthError" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "TargetWord" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "ReferencesIcon" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "DefinitionIcon" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "DefinitionCount" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "ReferencesCount" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "LspSagaSignatureHelpBorder" , { fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionContent" , { fg = "#fca7ea" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionTitle" , { fg = "#65bcff" }  )
vim.api.nvim_set_hl( 0, "LspSagaFinderSelection" , { fg = "#3654a7" }  )
vim.api.nvim_set_hl( 0, "LspSagaCodeActionBorder" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "LspSagaDefPreviewBorder" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "LspSagaRenameBorder" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "LspSagaHoverBorder" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "LspSagaBorderTitle" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "LspFloatWinBorder" , { fg = "#3e68d7" }  )
vim.api.nvim_set_hl( 0, "LspFloatWinNormal" , { bg = "#1e2030" }  )
vim.api.nvim_set_hl( 0, "DiagnosticInformation" , { link = "DiagnosticInfo" }  )
vim.api.nvim_set_hl( 0, "DiagnosticWarning" , { link = "DiagnosticWarn" }  )
vim.api.nvim_set_hl( 0, "WhichKeyValue" , { fg = "#737aa2" }  )
vim.api.nvim_set_hl( 0, "WhichKeyFloat" , { bg = "#1e2030" }  )
vim.api.nvim_set_hl( 0, "WhichKeySeparator" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "WhichKeySeperator" , { fg = "#7a88cf" }  )
vim.api.nvim_set_hl( 0, "WhichKeyDesc" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "String" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "WhichKey" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "AlphaButtons" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "AlphaFooter" , { fg = "#ffc777", italic = true }  )
vim.api.nvim_set_hl( 0, "AlphaHeaderLabel" , { fg = "#ff966c" }  )
vim.api.nvim_set_hl( 0, "AlphaHeader" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "AlphaShortcut" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "DashboardFooter" , { fg = "#ffc777", italic = true }  )
vim.api.nvim_set_hl( 0, "DashboardCenter" , { fg = "#c099ff" }  )
vim.api.nvim_set_hl( 0, "DashboardHeader" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "DashboardShortCut" , { fg = "#86e1fc" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette9" , { fg = "#ff757f" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette7" , { fg = "#c8d3f5" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette6" , { fg = "#4fd6be" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette4" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette3" , { fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette2" , { fg = "#c3e88d" }  )
vim.api.nvim_set_hl( 0, "GlyphPalette1" , { fg = "#c53b53" }  )
vim.api.nvim_set_hl( 0, "QuickFixLine" , { bg = "#3654a7", bold = true }  )
vim.api.nvim_set_hl( 0, "FernBranchText" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NeoTreeNormalNC" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NeoTreeNormal" , { bg = "#1e2030", fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NvimTreeFolderIcon" , { bg = "NONE", fg = "#ffc777" }  )
vim.api.nvim_set_hl( 0, "NvimTreeSymlink" , { fg = "#82aaff" }  )
vim.api.nvim_set_hl( 0, "NvimTreeImageFile" , { fg = "#828bb8" }  )
vim.api.nvim_set_hl( 0, "NvimTreeIndentMarker" , { fg = "#3b4261" }  )
vim.api.nvim_set_hl( 0, "NvimTreeSpecialFile" , { fg = "#fca7ea", underline = true }  )
vim.api.nvim_set_hl( 0, "NvimTreeOpenedFile" , { bg = "#2f334d" }  )


vim.api.nvim_set_hl(0, "TelescopeSelection" , {link = "ScrollbarHintHandle"} )
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret" , {link = "ScrollbarHintHandle"} )
vim.api.nvim_set_hl(0, "TelescopeMatching" , {link = "ScrollbarSearchHandle"} )
