let g:quickr_cscope_keymaps = 0
nnoremap <leader>fs  <plug>(quickr_cscope_symbols)     
nnoremap <leader>fg  <plug>(quickr_cscope_global)
nnoremap <leader>fc  <plug>(quickr_cscope_callers)
nnoremap <leader>ff  <plug>(quickr_cscope_files)
nnoremap <leader>fi  <plug>(quickr_cscope_includes)
nnoremap <leader>ft  <plug>(quickr_cscope_text)
nnoremap <leader>fe  <plug>(quickr_cscope_egrep)
nnoremap <leader>fd  <plug>(quickr_cscope_functions)
nnoremap <leader>fa  <plug>(quickr_cscope_assignments)
